kubernetes-sigs/headlamp

- frontend/src/components/cluster/Chooser.js
If we have just one cluster configured, there's no point in showing the cluster chooser.
Instead we just jupm straight into the configured cluster, and we don't use a button in the top left.
> Don't use the cluster chooser on single cluster

- frontend/src/components/common/EditorDialog.tsx
The docs' view is supposed to react to the contents of the editor. So
when the editor has a certain object kind and api version, the docs
should show the documentation for that object.
However, if there was an error shown (because e.g. the docs were not
found, or the contents were empty) then even if the contents were
corrected by the user, the error would remain.
To fix the mentioned issue, this patch resets the docs' error info
whenever the contents are changed.
> frontend: Reset docs when the editor contents change

- plugins-pkg/.gitignore
- plugins-pkg/bin/headlamp-plugin.js
- plugins-pkg/config/webpack.config.js
- plugins-pkg/package-lock.json
- plugins-pkg/package.json
Now that we support external plugins, the infrastructure to compile
those plugins was still not easy to configure. In order to make that
easier and also to provide other useful modules (like types, libs,
etc.) related to the plugins, this patch creates a new NPM package that
developers can use for building the Headlamp plugins externally.
> Add plugins NPM pkg

- frontend/src/lib/k8s/clusterRoleBinding.ts
- frontend/src/lib/k8s/index.ts
The class names have not been set in a consistent way: some are using
a capital first letter, and as a result the names in
k8s.resourceClasses were not the expected ones. We should make the
class names consistent but that has implications in the routes and
the sidebar, so for now we just capitalize the first letter when
adding the classes to k8s.resourceClasses. This is a temporary
measure until we have made de class names consistent.
> frontend: Make class names in k8s.resourceClasses consistent

- frontend/src/lib/k8s/cronJob.ts
- frontend/src/lib/k8s/daemonSet.ts
- frontend/src/lib/k8s/deployment.ts
- frontend/src/lib/k8s/ingress.ts
- frontend/src/lib/k8s/job.ts
- frontend/src/lib/k8s/statefulSet.ts
- frontend/src/lib/router.tsx
The back links for some views was broken because they don't have their own individual list view.
> Fix backlinks

- .dockerignore
- Makefile
This PR makes `make image` work. I'm not sure if the produced image works but at least we get an image.
It also adds `node_modules` to `.dockerignore` since this directory is huge and there is no need to send it to the Docker daemon when building images.
> Makefile: Specify Docker build path and ignore node_modules

- Makefile
Disabling the Docker cache greatly increases the time it takes to rebuild an image during development.
To test this PR, run `make image` twice in a row. The 2nd run should complete nearly instantly.
> Makefile: Remove --no-cache Docker flag

- frontend/src/components/role/Details.tsx
Some of those rules details are undefined, so we need to default to
empty lists.
> frontend: Fix joining rules details in the Role details view

- frontend/src/components/workload/Charts.tsx
The color should be black and not blue.
> frontend: Set right color for workload charts' foreground

- frontend/src/components/common/Resource.tsx
The UID is not very important to show in this view.
> frontend: Remove the UID from the MetadataDisplay component

- frontend/src/lib/k8s/cluster.ts
- frontend/src/lib/k8s/node.ts
These hooks are supposed to make it very easy to use a results/error
associated with the resources we want, but while the error does reset
the list (sets it to null), the opposite is not true and this led to
an issue of not showing results after an error occurs (even if the
error is no longer happening).
This patch resets the error in the context explained above, which
fixes this issue.
> frontend: Reset error when getting results on useList / useMetrics

- frontend/src/components/cluster/Chooser.tsx
If there is only one cluster configured, then we should show the cluster
name in the UI as the user context should be enough, and when deployed
in-cluster it was just showing "Cluster: main".
> frontend: Don't show a cluster name if there's only one cluster

- backend/cmd/headlamp.go
The URL scheme used for the OIDC redirect URL was dependent on having
the TLS presence in the /oidc request, but TLS may have been delegated
to the k8s deployment. So this patch enforces https unless the host
being used is the localhost one. This is not a great solution but we
can use it for now and think about a more complete one later.
> backend: Use https scheme for all OIDC redirect URL

- frontend/src/components/common/Resource.tsx
We were showing the plugins' header actions after the default ones but
this means that the UI is less consistent among views, e.g.: if a plugin
added a header button in pods' details but not in the deployments', then
the other buttons would be pushed left. This was even more evident if
the plugin took a while to add the button (even leading to a misclick).
This patch makes the plugins' header action components be added to the
left, so the rest of the buttons don't move in such case.
> frontend: Show plugins' header actions before others

- kubernetes-headlamp.yaml
Based on a patch by Saiyam Pathak (saiyam1814 on Github).
There was a typo in the plugins-dir flag of the K8s YAML file, and this
was preventing Headlamp to start in the image.
fixes #111
> kubernetes-headlamp.yaml: Fix plugins-dir flag typo

- frontend/src/components/common/Resource.tsx
The secrets should be decoded from base64 when the user requests to
view them.
> frontend: Decode secrets when showing them

- app/electron/main.js
Enable shell to be used while spawning the server
To validate this pr 
Generate a windows build of the desktop app and run it, earlier it was crashing because of server failure but now it wont
Yes
Testing done before submitting the pr: 
On windows generated the exe build and ran it 
To generate the exe I did the following steps
1. npm run build 
2. npm run package
> Fix windows build server failure

- Makefile
This patch adds make targets for desktop app build for all three
platforms.
run make app to generate desktop app builds for all three platforms 
use app-win for windows build generation
use app-mac for mac specific build generation
use app-linux for linux build generation
> Add make targets for desktop app builds

- docs/development/_index.md
- docs/development/plugins/how-to.md
- docs/installation/_index.md
- docs/installation/desktop/_index.md
The links we were using had no .md extensions even when they referred to
markdown documents because we read the docs now in a Hugo powered
renderer: https://kinvolk.io/docs .
That system now does support .md extensions in links, so let's bring
back the extensions which make the docs readable also on Github.
> docs: Use portable links

- kubernetes-headlamp.yaml
This allows the pod to be annotated with the matching service name when
it is scheduled.
Commit message fixed from #121 .
> kubernetes-headlamp.yaml: Services should come before the deployment

- .github/workflows/backend.yml
With a recent update to github set-env and add-path commands were deprecated 
Read more here => https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
and because actions/setup-go uses internally these commands our ci was failing
> Github actions: Fix backend workflow

- backend/cmd/headlamp.go
Allow oidc flow with custom certificates when run in insecure mode
Done!! tested with setting up oidc auth flow with dex followed by untrusted cert
fixes #127
> Allow custom certificates in oidc mode

- backend/cmd/headlamp.go
Plugins are optional in Headlamp, so we shouldn't print an error if the
folder doesn't exist.
> backend: Don't print an error when the plugins folder doesn't exist

- frontend/src/components/serviceaccount/Details.tsx
On the service account details view page we want to connect the secret name to its own page this will reduce copy pasting and manually looking for that secret name in secrets list.
> Link service account Details view to secret details view

- backend/cmd/headlamp.go
Our current method for preparing the default path for kubeconfig doesn't works on windows platform.
This patch updates how we prepare that path considering what is the homedir for current user
Testing done
Yes on linux and windows
> backend: Fix how we get home directory for preparing kubeconfig path

- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/common/Link.tsx
- frontend/src/components/common/Resource.tsx
- frontend/src/components/workload/Details.tsx
- frontend/src/components/workload/Overview.tsx
- frontend/src/lib/k8s/deployment.ts
- frontend/src/lib/router.tsx
When visiting a workload details view from the workload overview, then the back button (of the details view) should go back to the workloads overview, but when visiting it from the actual workload type list it should go back to it.
We could achieve this behavior with a "history.goBack()" function, but we don't want to go back to any page in the history. And thus this PR adds extra functionality to the ResourceLink and Link components which is also useful for other use cases.
> Workload navigation

- docs/development/plugins/_index.md
The initial sentence had many "and" words and very easily lost the concentration of the reader.
Not applicable
Not applicable; documentation only
> Update _index.md for clarity

- .gitignore
- Makefile
- app/.gitignore
- app/package.json
package the app on windows and try running the desktop app 
earlier it was only showing a infinite spinner because of server not running, this is fixed now.
yes
> Update backend target to produce a server excutable when on windows

- Makefile
Instead of repeating the "npm run build" command in all the 3 app
related targets, we now create an app-build target for that, and also
run "npm install" in it, as it's a needed first step.
> Makefile: Improve the app related targets

- backend/cmd/kubeconfig.go
Attempts to fix one of the problems causing https://github.com/kinvolk/headlamp/issues/112, especially the panic described in https://github.com/kinvolk/headlamp/issues/112#issuecomment-762148606
1. Create a kubeconfig context referencing a user that does not exist
```yaml
...
contexts:
- context:
cluster: my-existing-cluster
user: non-existing
name: my-context
...
```
2. Execute the backend
```nohighlight
$ make backend
cd backend && go build -o ./server ./cmd
$ backend/server
2021/01/18 17:42:18 Not adding context my-context because authInfo is nil!
*** Headlamp Server ***
API Routers:
...
```
> Check for nil in context parsing

- backend/cmd/kubeconfig.go
Continuing on from the PR https://github.com/kinvolk/headlamp/pull/170 related to https://github.com/kinvolk/headlamp/issues/112#issuecomment-762148606
There was a segfault in the backend when the user was not there, or not existing.
1. Create a kubeconfig context referencing a user that does not exist
```yaml
...
contexts:
- context:
cluster: my-existing-cluster
user: non-existing
name: my-context
...
```
Another case is where there is no user mentioned at all.
```yaml
...
contexts:
- context:
cluster: my-existing-cluster
name: my-context
...
```
2. Execute the backend
```nohighlight
$ make backend run-backend
2021/01/21 15:09:48 Not adding context: my-context because user:non-existing could not be found!
*** Headlamp Server ***
API Routers:
...
```
It shows this for when the user is not …
> Check for nil and empty username in context parsing (#170)

- frontend/src/components/authchooser/index.tsx
So that the login screen is shown again as it was in v0.1.3
See https://github.com/kinvolk/headlamp/issues/182
It would be worthwhile to refactor this code so that the states are clear and tested (as started in https://github.com/kinvolk/headlamp/pull/168 ) but this is not done in this PR.
Login against an OIDC configuration.
See that there is a choice between Login, and using a token.
Before it was going to the enter token state.
Now it's showing a choice.
> Add login screen back for OIDC configurations

- frontend/src/components/common/EditButton.tsx
- frontend/src/components/common/ViewButton.tsx
Users logged in via a read only token can also see resource YAML(in read-only mode)
fixes #175
> Allow viewing resource YAML even if its read-only token

- frontend/.storybook/HeadlampTheme.js
- frontend/.storybook/manager.js
With logo, link, and description.
`npm run storybook --no-manager-cache`
(The extra --no-manager-cache argument is needed to work around a bug where storybook doesn't refresh the theme always. It's not needed the first time people run it, only when making a storybook theme.)
Related: https://github.com/kinvolk/headlamp/issues/205
> frontend: Add a basic storybook theme

- docs/installation/base-url.md
Some documentation about how people should take care if using headlamp on a base-url with other apps.
> Add a same origin warning to the base-url docs

- app/electron/main.ts
On at least linux the server process continued in the background after closing the app.
This uses a different method of stopping the process using the
detached option which puts all the processes in a separate group.
To see the issue: Make the linux app, open it, close it, and the server process is still there. On the second opening of the app, it shows an authentication problem to the user because the server process can not start with the port already open.
There's an article on this topic here: https://azimi.me/2014/12/31/kill-child_process-node-js.html
```bash
rm -rf app/dist/ && make app-linux 
cd app/dist
tar xf Headlamp.tar.gz
cd Headlamp
./headlamp
ps aux | grep server # should show no electron server processes.
```
> Stop server running in background when closing app

- .gitignore
- Makefile
- docs/development/api/_index.md
- docs/development/api/interfaces/_index.md
- docs/development/api/interfaces/util.filterstate.md
- docs/development/api/modules/_index.md
- docs/development/api/modules/k8s.md
- docs/development/api/modules/util.md
- docs/development/frontend.md
- frontend/package-lock.json
- frontend/package.json
- frontend/tsconfig.json
We generate `api` under docs/development.
Using typedoc for the generated `api` files.
`make docs`
`make docs` outputs static markdown, and you can view that in the following folders:
- docs/development/api
With the website using the docs branch at (https://github.com/kinvolk/docs/pull/14) inside the website repo you can do `make docs run` and have it serve the api folder with hugo.
- http://localhost:1313/docs/headlamp/0.2/development/api/
> Add "make docs" with typedoc for docs/developer/api

- .gitignore
- Dockerfile
- backend/cmd/headlamp.go
- backend/cmd/plugins.go
- backend/cmd/server.go
- backend/go.mod
- docs/development/_index.md
- docs/development/plugins/building.md
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/plugin/index.tsx
```bash
make backend run-backend
make run-frontend
```
> App using plugins, and live reload of plugins

- .dockerignore
- Dockerfile
Copying the plugins was failing if the plugins folder was empty, because
in the Dockerfile we tried to copy from /headlamp/plugins but we first
had moved any plugins folder to plugins-old and if the folder was empty,
then the copy command wouldn't create the final plugins directory again.
Fixing that just required creating the mentioned plugins folder after
the move, but there was also the problem that the copy command was
copying everything in each plugins folder and not just the main.js file.
> Fix copying innexistent plugins

- frontend/src/App.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
The main motivation for this change is to not having plugins' components in the top bar being placed between the theme change and the account buttons.
On the other hand, we should in any case have the theme being set through redux as we may need it later.
> Use redux for theme

- frontend/src/components/cronjob/List.tsx
I found a bug in Headlamp app v0.2.1 & 0.3.0-beta: when you click on "workloads->cronjobs" button in a cluster that do have an cronjobs, you got an empty white screen. I investigated into this problem and found that frontend got TypeError after pressing the button. This patch should fix it.
I test it by hands with the same cluster, where the bug occurs, now it should work fine
> cronjob: fix TypeError in getSchedule()

- docs/development/plugins/building.md
- plugins/examples/pod-counter/package.json
- plugins/headlamp-plugin/README.md
- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/package.json
- plugins/headlamp-plugin/template/package.json
`headlamp-plugin build` changes:
- So that the build command can build a package or folder of packages given (defaults to cwd as before).
- Stop printing the watch message for building production packages.
- Stop copying the built plugins to the config/plugins folder for production builds.
```bash
node plugins/headlamp-plugin/bin/headlamp-plugin build plugins/examples/pod-counter
ls -la plugins/examples/pod-counter/dist
rm plugins/examples/pod-counter/dist/main.js
node plugins/headlamp-plugin/bin/headlamp-plugin build plugins/examples/
ls -la plugins/examples/pod-counter/dist
rm plugins/examples/pod-counter/dist/main.js
cd plugins/examples/pod-counter
node plugins/headlamp-plugin/bin/headlamp-plugin build # works as before
ls dist/
cd ../../../
node …
```
> Add optional folder support to headlamp-plugin build command

- app/electron/main.ts
For people who have buggy graphics drivers.
`headlamp --disable-gpu`
Then you should see this message:
```
› Disabling GPU hardware acceleration.
```
Electron docs: https://www.electronjs.org/docs/api/app#appdisablehardwareacceleration
> Add a --disable-gpu option for the app

- README.md
- docs/_index.md
- docs/installation/desktop/headless.md
- docs/installation/desktop/linux-installation.md
- README: Add links to the desktop platforms installation docs directly
- docs: Mention Flatpak in the Linux installation
I would like to add badges for the different platforms, much like [Joplin](https://joplinapp.org/#desktop-applications) has. But this is enough ATM.
> Flatpak Docs

- Dockerfile
- Makefile
icu-data package is used to support better locale formatting.
Alpine 3.13.x comes with Nodejs 14.x which has plenty of improvements,
but one area it improves greatly is locale based formatting.
https://alpinelinux.org/posts/Alpine-3.13.0-released.html
https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.13
Related to [ [RFE] Support i18n #246 ](https://github.com/kinvolk/headlamp/issues/246)
> docker: Upgrade alpine linux 3.13.5 add icu-data package

- README.md
- docs/platforms.md
We want to keep a list of platforms where we've tested Headlamp in order
to share not only works and what doesn't, but also any useful remarks
about the deployment.
@vbatts : We have tried it on Azure as well but need to do it again in
order to capture any gotchas (hence it showing as `?`).
I have also chosen to add it to the docs instead of the README as it looks out of place and a misleading (from a "tested" to a "supported" vibe somehow) there.
fixes #248
> docs: Add platforms list

- docs/platforms.md
As reported in https://github.com/kinvolk/headlamp/issues/266 , let's add EKS as "works".
fixes #266
> docs: Add EKS to the list of tested platforms that work

- frontend/src/components/cluster/Chooser.tsx
Instead of focusing the title, we focus the first cluster button:
For the [Accessibility improvements](https://github.com/kinvolk/headlamp/issues/245) issue.
> Change cluster modal to focus first cluster button

- frontend/src/App.tsx
- frontend/src/components/common/Resource/EditorDialog.tsx
- frontend/src/lib/themes.ts
- frontend/src/redux/reducers/ui.tsx
If the user makes a preference by selecting the theme from the UI, then it uses that preference instead. Once the user preference is selected it always uses that preference from then on.
The localStorage key was prefixed with headlamp to try and avoid nameclashes. The older key was ignored, since it was set without a user selecting a preference. This way the browser/OS preference is used until they change it manually.
Also make the theme preference change reactive. So it changes when the os/browser preference changes.
https://user-images.githubusercontent.com/9541/122554287-13de9680-d039-11eb-905d-08b9e5b6bdd7.mov
To test, use the browser/OS to set a darkmode/lightmode theme preference. There is no way to clear the user preference except to delete the local storage "themePreference" key. …
> Use Browser or OS light/dark theme preference

- frontend/src/App.tsx
- frontend/src/components/cluster/Chooser.tsx
- frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
- frontend/src/i18n/electronI18n.tsx
- frontend/src/lib/router.tsx
- With pt selected, when starting app fresh the pt locale is used for menu items and other parts
- there is a locale selecter on the front page (under the cluster list)
> Fix Electron integration, show lang selector on front page, generate LocaleSelect options from config

- frontend/src/i18n/locales/es/cluster.json
- frontend/src/i18n/locales/es/glossary.json
Fix two minor typos in Spanish locale.
> locales/es: Fix two minor typos

- .github/cr.yaml
- .github/ct.yaml
- .github/workflows/helm-chart-lint-test.yml
- .github/workflows/helm-chart-release.yml
- charts/headlamp/.helmignore
- charts/headlamp/Chart.yaml
- charts/headlamp/README.md
- charts/headlamp/templates/NOTES.txt
- charts/headlamp/templates/_helpers.tpl
- charts/headlamp/templates/clusterrolebinding.yaml
- charts/headlamp/templates/deployment.yaml
- charts/headlamp/templates/ingress.yaml
- charts/headlamp/templates/service.yaml
- charts/headlamp/templates/serviceaccount.yaml
- charts/headlamp/values.yaml
This patch adds helm chart, thus allowing
users to easily deploy headlamp in their cluster
Signed-off-by: yolossn <nssvlr@gmail.com>
> deploy: Add Helm chart

- charts/headlamp/Chart.yaml
We want to release again because now we do have the gh-page
published.
> charts: Bump chart version so we get it released

- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/configmap/List.tsx
- frontend/src/components/crd/List.tsx
- frontend/src/components/cronjob/List.tsx
- frontend/src/components/daemonset/List.tsx
- frontend/src/components/deployments/List.tsx
- frontend/src/components/job/List.tsx
- frontend/src/components/namespace/List.tsx
- frontend/src/components/pod/List.tsx
- frontend/src/components/replicaset/List.tsx
- frontend/src/components/role/BindingList.tsx
- frontend/src/components/role/List.tsx
- frontend/src/components/secret/List.tsx
- frontend/src/components/service/List.tsx
- frontend/src/components/serviceaccount/List.tsx
- frontend/src/components/statefulset/List.tsx
- frontend/src/components/storage/ClaimList.tsx
- frontend/src/components/storage/ClassList.tsx
- frontend/src/components/storage/VolumeList.tsx
- frontend/src/components/workload/Overview.tsx
- frontend: Allow to set the SimpleTable's sort function as a getter
- frontend: Enable sorting in (almost) every column
> Sort almost everything

- frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
- frontend/src/i18n/ThemeProviderNexti18n.tsx
Useful for different browser functionality including a11y tools.
Also fixes an issue where the language direction was being set incorrectly at startup for a brief moment (you could see it sometimes on the first screen before the locale loaded).
Switch language, inspect html lang attribute.
> Change html lang when switching locales

- frontend/src/components/common/SimpleTable.stories.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/role/BindingList.tsx
- frontend/src/components/role/List.tsx
- frontend/src/components/secret/List.tsx
- frontend/src/components/service/List.tsx
- frontend/src/components/workload/Overview.tsx
Allow to search by type and add facility of searching by other properties as well
Go to any view which has a type column try using the search filter and you now should be able to search by type as well
Try using the search filter on a view that has a type column and you will see you are now able to search by type and namespace both
> Add type search

- app/electron/main.ts
- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
- app: Allow to override the app version with an env var
- frontend: Ensure the current app version is always set
- frontend: Catch any errors when getting the release information
> Make release notes more resilient

- frontend/src/components/App/TopBar.tsx
- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
- frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.tsx
- frontend/src/components/common/ReleaseNotes/UpdatePopup.tsx
- frontend/src/i18n/locales/en/frequent.json
- frontend/src/i18n/locales/en/release.json
- frontend/src/i18n/locales/es/frequent.json
- frontend/src/i18n/locales/es/release.json
- frontend/src/i18n/locales/pt/frequent.json
- frontend/src/i18n/locales/pt/release.json
- frontend: Set the release notes' version string as translatable
- frontend: Add a margin between the release notes title and body
- frontend: Use frequent namespace on TopBar translations
- i18n: Use release namespace for an update release string
- i18n: Add missing translations
> Fix showing the version in the release notes

- backend/cmd/headlamp.go
Instead of guessing (which would return HTTP for localhost and HTTPS for every other situation – which is not always correct), check TLS property of a request object. It is `nil` for plain connection, and not `nil` if HTTPS is used.
Not a new functionality.
> backend: better way of determining the URL scheme

- .github/workflows/frontend.yml
- Makefile
- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/template/package-lock.json
- plugins/headlamp-plugin/test-headlamp-plugin.sh
We rely on just calling the "headlamp-plugin build" command without
any arguments, but the build command expected a positional argument as
required, so the default and advised case for building plugins was
failing.
> headlamp-plugin: Make the package arg of the build command optional

- backend/cmd/headlamp.go
- frontend/src/helpers/index.ts
If coming in from a URL like /c/main then the static file
paths will be "./c/main/static/nnn.css" rather than "/static/nnn.css"
This results in a white empty page where the app does not load without any error shown, as seen in: https://github.com/kinvolk/headlamp/issues/345
```
eval $(minikube docker-env)
docker build . -t me/headlamp 
Change in ./kubernetes-headlamp.yaml 
image: me/headlamp:latest
imagePullPolicy: Never
kubectl apply -f ./kubernetes-headlamp.yaml 
kubectl -n kube-system create serviceaccount headlamp-admin
kubectl create clusterrolebinding headlamp-admin --serviceaccount=kube-system:headlamp-admin --clusterrole=cluster-admin
kubectl -n kube-system get secrets | grep headlamp-admin
kubectl -n kube-system describe secret headlamp-admin-token-XXXXX
kubectl port-forward -n …
```
> Fix static resource paths when the URL is not /

- .github/workflows/draft-release.yml
Turns out the action used before is discontinued, so this one replaces it and also simplifies the logic.
> github: Simplify the release draft action

- frontend/src/components/common/Resource/EditorDialog.stories.tsx
- frontend/src/components/common/Resource/EditorDialog.tsx
- frontend/src/components/common/Resource/__snapshots__/EditorDialog.stories.storyshot
- frontend/src/components/common/index.ts
- frontend/src/lib/router.tsx
- frontend/src/plugin/index.tsx
This PR fixes and adds a few things that are required for the plugins to work correctly.
1. The ```createRouteURL``` method in ```frontend/src/lib/router.tsx``` doesn't considers routes from redux store which could be a problem when a plugin wants to render a link and the only way the plugin can communicate it's route params is through the store so we have to make the createRouteURL method aware of the store routes.
2. We need the Editor component exported because it will come in useful when we want to modify a kube object.
3. We need  APIs such as ```useLocation``` or ```useHistory``` etc. from react-router package so it makes sense to export it as well
> Fix plugin related issues

- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/lib/router.tsx
We have default routes and dynamic ones (set in redux, by plugins), and
so far we've been considering the default ones first. This meant that
routes couldn't be overridden by plugins and this makes things less
flexible for them.
This patch considers default routes last, so it opens a lot of
flexibility for plugins to replace a route completely.
> Consider dynamic routes first

- frontend/src/plugin/index.tsx
This is a temporary solution for now until we have something solid either from notistack or we have a better approach of handling peer dependency of plugin packages
https://github.com/iamhosseindhv/notistack/issues/335
https://github.com/iamhosseindhv/notistack/issues/421
> frontend: Add notistack to pluginLib object

- frontend/src/components/role/BindingDetails.tsx
The RoleBinding and ClusterRoleBinding resources were being used
without and with the namespace, respectively, but it should be the
other way around.
> frontend: Fix fetching the resource in the RoleBindingDetails view

- frontend/src/components/Sidebar/VersionButton.tsx
Due to how the VersionButton was fetching the version details, it
could end up trying to change the state after the button was no longer
mounted. This patch changes that by ensuring we have not unmounted it.
> frontend: Do not change state on VersionButton after it's unmounted

- app/electron/main.ts
- app/package.json
- docs/installation/desktop/_index.md
- frontend/src/components/cluster/Chooser.tsx
This PR adds the possibility of running Headlamp with a different kube config, by using either a `KUBECONFIG` env var, or the new positional argument: `headlamp /path/to/my/different/kubeconfig`.
fixes #370 
fixes #357 
cc/ @sgandon , it's not loading an entire dir by default, but I hope this makes sense.
> desktop: Use a different kubeconfig

- frontend/src/components/cluster/Charts.tsx
The overview chart was showing pods that are running or not, but it's
more interesting and useful to show the pods that are ready and not
ready instead.
> frontend: Correctly filter ready pods in the overview chart

- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/lib/k8s/event.ts
The events list shows important occurrences in the cluster, and it's
very useful to have a way to go right to the resource in question.
So this patch adds a link to the involved object, when possible.
> frontend: Add links to the events list

- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/role/BindingList.tsx
- frontend/src/components/role/List.tsx
- frontend/src/components/secret/List.tsx
- frontend/src/components/service/List.tsx
- frontend/src/components/workload/Overview.tsx
- frontend/src/lib/util.ts
The advanced filter search (searching by non-default criteria) was
not working correctly because it was mixing non-filtered matches with
the matched ones, e.g. if we selected a namespace and then used the
advance filter matching (by matching the "kind" in the workload
overview), it was showing the correctly matched kind, but with data
from all namespaces.
This patch not only fixes that issue, but also simplifies how the
advanced filter is implemented (in the filter function rather than
in the SimpleTable component) and uses JSONPath to make it a bit more
powerful as well.
> frontend: Simplify and fix advanced search

- .github/ct.yaml
We don't need this when testing/linting the charts' PRs.
> build: Don't check for a chart version bump

- .github/workflows/app.yml
- app/package-lock.json
- app/package.json
export, mkdir -p, and `''` quoting were problematic
Additionally. the github app windows build now doesn't use bash with npm. This is a test which shows this PR works without bash on windows now.
ps. Note: server.exe will hang around on app close. So make sure to kill that with task manager if you are testing.  There's a PR for that here: https://github.com/kinvolk/headlamp/pull/395
> Compiling Headlamp app on Windows fixes

- .github/workflows/frontend.yml
- app/electron/main.ts
Related to issue: https://github.com/kinvolk/headlamp/issues/389
Check task manager for a server.exe process still around when the app quits.
Or with cmd you can find it with:
```
tasklist | findstr /c:"server.exe"
```
> Fix windows app not closing server.exe on quit

- frontend/src/components/common/Resource/Resource.tsx
The ConfigMap details view was using the editor to display data always
in the dark theme. This patch makes it aware of the theme changes and
lets it change accordingly.
> frontend: Use the current theme for the ConfigMaps' editor

- frontend/src/lib/k8s/apiProxy.ts
Some APIs do not have a group and we were parsing the YAML added to
the creation dialog in a way that it expected to have a group.
> frontend: Fix applying non-grouped API resources

- frontend/src/components/cluster/Charts.tsx
This prevents the issue of calling a function on a variable that may
be undefined.
> frontend: Check for a pod's conditions before using them

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/account/Auth.tsx
- frontend/src/components/authchooser/index.tsx
- frontend/src/components/cluster/Chooser.tsx
- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/common/Label.tsx
- frontend/src/components/common/LogViewer.tsx
- frontend/src/components/common/Resource/EditorDialog.tsx
- frontend/src/components/common/Resource/MetadataDisplay.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/common/SectionFilterHeader.tsx
- frontend/src/components/common/SectionHeader.tsx
- frontend/src/components/common/Terminal.tsx
- frontend/src/components/node/Details.tsx
- frontend/src/components/workload/Overview.tsx
- frontend: Replace Grid's justify prop by justifyContent
- frontend: Don't use deprecated props for dialogs
- frontend: Don't use deprecated onBackdropClick property on dialogs
> Fix UI warnings

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/workload/Details.tsx
- frontend/src/lib/k8s/cronJob.ts
- frontend/src/lib/k8s/daemonSet.ts
- frontend/src/lib/k8s/job.ts
- frontend/src/lib/k8s/statefulSet.ts
The back link from their details view would go to the workloads'
list view but it should go to the resources' own list view.
> frontend: Make workload details go back to the correct list view

- .github/workflows/app.yml
- .github/workflows/frontend.yml
- Dockerfile
- Makefile
- app/package-lock.json
- app/package.json
Because Nodejs 16 is now LTS node, and it has various improvements including better support for javascript modules.
- Current node LTS is now [node 16](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md) see https://nodejs.org/en/about/releases/
- Node 12 End of life is in a few months April 30(2022-04-30.), so we stop testing on that.
- Alpine linux 3.15.0 https://alpinelinux.org/posts/Alpine-3.15.0-released.html contains node 16, (and pg 14, linux LTS)
- electron-builder version we had didn't work with node 16. Version 22.11.2 of electron-builder contains a nodejs 16 fix: https://github.com/electron-userland/electron-builder/releases/tag/v22.11.2 So we use that version, since not as much has changed... and it should be a less risky dep upgrade than the latest.
> Upgrade Nodejs 16 versions, and Alpine linux 3.15.0

- frontend/src/App.tsx
- frontend/src/plugin/index.ts
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/clusterAction.tsx
- frontend/src/redux/reducers/config.tsx
- frontend/src/redux/reducers/filter.tsx
- frontend/src/redux/reducers/ui.tsx
I have taken a look at why plugins some times re-render twice and this PR fixes that.
@ashu8912 do you know if this is enough for #323 ?
@illume , I don't know why I had made it so that the plugins would be reloaded on theme change (there's still an issue with the themes in the config maps' editors, but that's happening in main as well). Since you touched it, maybe you can at least confirm there's nothing I'm missing by removing this dependency.
> Fix plugin reinitialization

- Dockerfile
So that if a backend part is changed, then the frontend image is not rebuilt and vice versa.
Also if a frontend/src change is made, docker build doesn't do an npm install again.
> Dockerfile: Fix alpine version typo, and separate front and back building

- .github/workflows/app-artifacts-mac.yml
The newly used electron-build version no longer requires that rename
as it honors the passed architecture.
> .github: Remove file rename from app-artifacts-mac action

- backend/cmd/headlamp.go
The conditions used to decide urlScheme for an http callback URI for oidc was broken
> backend: Update how we handle http callback URLs for oidc

- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
- plugins/headlamp-plugin/test-headlamp-plugin-published.sh
- bumped headlamp-plugin to 0.4.1
- modified the plugin test to test published versions
```bash
cd plugins/headlamp-plugin
./test-headlamp-plugin-published.sh 0.4.1-rc1
echo $?
./test-headlamp-plugin-published.sh 0.4.0
echo $?
```
> Headlamp plugin 0.4.1 and a test for published packages

- frontend/src/components/pod/Pod.stories.tsx
refer https://stackoverflow.com/questions/40935886/components-using-date-objects-produce-different-snapshots-in-different-timezones
Using toLocaleString makes the CI fail at times
> frontend: Don't use toLocaleString to generate date for tests

- frontend/src/plugin/index.ts
- plugins/examples/pod-counter/package.json
- plugins/examples/pod-counter/src/index.tsx
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
- fix traceback cross origin issue, so the real error can be shown (without having a look into the dev console)
- Add missing React import in pod-counter plugin example
- K8s.ResourceClasses.Pod.useList(); needed to be used in pod-counter plugin example
- Updated @kinvolk/headlamp-plugin version to 0.4.2
Note, the types are not in the distributed headlamp-plugin package. I think `npm run build` was forgotten, or the publish script is somehow broken.
```
cd plugins/examples/pod-counter
npm install
npm run start
```
After copying in the types made with `cd headlamp-plugin; npm run build && cp -a types/* node_modules/@kinvolk/headlamp-plugin/types` the pod-counter plugin works inside headlamp.
> Plugin example fixes

- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
- plugins/headlamp-plugin/types/.gitignore
- plugins/headlamp-plugin/types/.npmignore
We want to ignore the presence of generated types (types folder) in
git, but we want them to be shipped in the module. However, npm does
check .gitignore if a .npmignore file is missing, which meant that no
types were being packed/shipped.
This commit adds a .npmignore file that doesn't ignore the types,
effectively making npm pack the mentioned types.
> plugins/headlamp-plugin: Do not ignore types when packing

- backend/cmd/headlamp.go
In an oidc auth flow the id token is used for authentication and that is
what should be send in the redirect URI of the oidc callback so that
id_token is used to make request to the kubernetes cluster.
Access token should not be used because they are part of oauth 2.0 flow
and are used for authorization purposes.
Tested with cognito and EKS setup 
The fix is contained in this image  ```docker.io/ashu8912/headlamp-test```
> backend: Fix oidc redirect url token type

- plugins/headlamp-plugin/config/plugins-tsconfig.json
- plugins/headlamp-plugin/template/src/index.tsx
- plugins/headlamp-plugin/template/tsconfig.json
headlamp-plugin was adding a tsconfig.json file through a template.
However this left around a file in each plugin which could not be
easily updated.
This files prevents that by shipping a plugins-tsconfig.json in the
headlamp-plugin module, and including it from the templated tsconfig.
fixes #433
> plugins/headlamp-plugins: Use internal tsconfig for plugins

- frontend/src/lib/k8s/index.ts
- frontend/src/lib/k8s/networkpolicy.tsx
We would be needing the networkpolicy API for the security advisor
plugin. This patch adds the required API for it.
Tested by calling NetworkPolicies.useList to see if we get any network policies and we do get it with this PR
> frontend: Add networkpolicy API

- app/electron/main.ts
- backend/cmd/headlamp.go
- backend: Fix serving the static frontend only if needed
- app: Fix passing static dir arg for headless mode
```bash
make app-linux
cd app/dist/linux-unpacked
./headlamp --headless
```
- `--headless` mode with app works
- `make run-frontend` / `make run-backend` still works
> Headless app fix

- plugins/headlamp-plugin/config/plugins-tsconfig.json
This is another attempt at making the plugins' imports easy.
1. Do the following in VSCode (and use the values/types).
```typescript
import { KubeObjectInterface } from '@kinvolk/headlamp-plugin/lib/K8s/cluster';
import { makeCustomResourceClass } from '@kinvolk/headlamp-plugin/lib/K8s/crd';
```
2. Set your plugin's tsconfig as the following:
```json
{
"extends": "./node_modules/@kinvolk/headlamp-plugin/config/plugins-tsconfig.json"
}
```
3. Click + hover the module part of the import to see that it's resolved. (And also, no errors should be reported/underlined by VSCode)
4. Change an import to a non-existing module to check if there's an error reported by VSCode.
5. Run `npm run tsc` in the plugin to see that there are no complaints about the imports.
If there are VSCode complaints, in a …
> Fix plugin imports again

- plugins/examples/pod-counter/src/index.tsx
Adds an example of styling inside a plugin.
```
cd plugins/examples/pod-counter
npm run start
```
> plugins: Show how to use styles inside a plugin

- .github/workflows/app.yml
This way we are testing with a particular version, rather than using the latest version even if it hasn't been tested.
> github: Fix golang version to one version

- .github/workflows/frontend.yml
- Makefile
- docs/development/frontend.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/404/index.tsx
- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/components/App/TopBar.tsx
- frontend/src/components/account/Auth.tsx
- frontend/src/components/account/__snapshots__/AuthToken.stories.storyshot
- frontend/src/components/authchooser/index.tsx
- frontend/src/components/cluster/Chooser.tsx
- frontend/src/components/common/Dialog.tsx
- frontend/src/components/common/Resource/__snapshots__/MetadataDisplay.stories.storyshot
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/i18n/ThemeProviderNexti18n.tsx
- frontend/src/index.tsx
- frontend/src/lib/router.tsx
- Issues are logged _last_ in the console. To make them easier to read whilst the console is noisy.
- If any issues remain, an alert() is done to warn developers when Headlamp is run in development mode. 
Hopefully these measures will help prevent more issues escaping review, since the console log was quite noisy and can be forgotten.
Additionally:
- Started a section in the documentation on a11y tools.
- fixes a number of the reported a11y issues
- storybook was broken because of an iconify issue (added test of storybook to CI)
- apart from a11y messages in the console, it removes a few more lines from the dev console related to i18n
During development
- "axe react" a11y messages should be printed at the end of the development console now (rather than somewhere in the middle).
- an alert …
> Add better a11y error reporting, fix storybook, fix reported a11y issues

- backend/cmd/cluster.go
- backend/cmd/headlamp.go
- backend/cmd/headlamp_test.go
- backend/cmd/server.go
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/plugin/lib.ts
- plugins/examples/dynamic-clusters/.gitignore
- plugins/examples/dynamic-clusters/README.md
- plugins/examples/dynamic-clusters/jsconfig.json
- plugins/examples/dynamic-clusters/package-lock.json
- plugins/examples/dynamic-clusters/package.json
- plugins/examples/dynamic-clusters/src/index.tsx
- plugins/examples/dynamic-clusters/tsconfig.json
fixes #456 
- Set up a new cluster, and remove details from your `~/.kube/config` 
- add the cluster details to the `plugins/examples/dynamic-clusters/src/index.tsx` source
- cd `plugins/examples/dynamic-clusters/ && npm start` the plugin
- start headlamp
- click the "New Cluster" button in the app bar at the top
- headlamp should reload with the new cluster
> Add clusters dynamically

- .github/workflows/app-artifacts-linux.yml
- .github/workflows/app-artifacts-mac.yml
- .github/workflows/app-artifacts-win.yml
- .github/workflows/backend.yml
There's an incompatibility with some libraries in the latest version.
> github: Fix golang version to be 1.17 rather than latest

- kubernetes-headlamp.yaml
The other has been deprecated since kubernetes v1.14
Updates the node selector to get rid off this warning:
```
service/headlamp created
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
deployment.apps/headlamp created
```
> Update: nodeSelector

- frontend/src/components/common/Terminal.tsx
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/pod.ts
This commit improves the terminal UX by:
1. Go to a pod where you can exec into
2. Press the terminal button
3. Type something like: ls -la
4. Shrink the browser window so the results from the previous command have to be wrapped
5. Verify that only the terminal console gets a scrollbar
6. With a terminal connected to the shell, type exit and verify that the terminal is closed; open it again and it'll be connected without an issue
> Improve terminal UX

- app/electron/main.ts
When the app is quitting, if we try to kill the Headlamp server
process asynchronously, there's a race condition which may end up in
the electron process being quit before the server kill instruction is
actually done. The result was that the Headlamp server would be left
running in Windows most of the times.
Testing done:
1. Launch the app, verify there's a headlamp-server process running
2. Quit the app: verify there's no headlamp-server process running
> app: Kill Headlamp server process synchronously

- app/electron/locales/en/app.json
- app/electron/locales/es/app.json
- app/electron/locales/pt/app.json
- app/electron/main.ts
- app/package-lock.json
- app/package.json
I reflected more on the discussion about whether we should ask users to terminate running Headlamp server processes and remembered that any users of current Headlamp versions on Windows will hit this problem until they update to the new version.
So I started fixing this, working from Linux, and noticed that Linux was also leaving its headlamp-server processes running after the app quit. It also had an issue (we were killing the PID using its negative version, for killing a process group, but on Linux the process doesn't run detached, so there was an uncaught exception...)
Therefore, I worked again on making sure that we can start and finish the headlamp-server process from within the app without resorting to killing it by PID (since we do have a subprocess wrapper for it). This was not …
> Fix (again) + help quitting server

- app/package.json
Adding this patch from #516 so we have it in the release now, in case users with a 0.10.0 need to use this in the future.
> desktop: Add headlamp as the custom protocol

- frontend/src/components/common/Resource/Resource.tsx
Just hit an error when apparently the labels of a pod are null/undefined but they are not expected to be so in the OwnedPodsSection.
> frontend: Fix unexpected undefined value in OwnedPodsSection

- .github/workflows/draft-release.yml
These emojis have been used for a couple of releases. Let's add
them. Also adds a link to the container image URL.
> github: Add emojis to the release draft creation action

- frontend/src/index.tsx
If there are multiple a11y issues reported by axe, then the UI
becomes unusable with the alert notifications that need to be
acknowledged.
This may lead developers to just run all the time with the skipped
a11y alerts.
So this patch tries to prevent that by allowing only a one-time alert
per session (i.e. if the user refreshes, they should see it again).
fixes #554
> frontend: Only alert about a11y issues once per session

- frontend/src/components/Sidebar/prepareRoutes.ts
When items were set up in the sidebar from a plugin, the object they
were using was the one set up in redux. This meant that any children
of that sidebar entry would be appended to the object's "subList" in
redux and hence that list would grow with multiple equal entries
every time the sidebar was rendered.
This patch prevents that by deep cloning the object before using it.
> frontend: Do not duplicate children in dynamic sidebar items

- .github/workflows/app-artifacts-win.yml
- app/package.json
Before we were building the app on windows using bash.
This now works on windows with cmd (and make installed):
```bash
make app-win
cd app
npm run copy-icons
npm run prod-deps
npm run copy-plugins
```
> app github: Build windows app without bash

- app/package.json
We want to provide Windows users with installation options.
> app: Do not create a one-click installer for Windows

- frontend/src/components/cluster/Overview.tsx
By mistake, the events table in Overview was sorting events by
namespace when it should be doing it by date.
This patch fixes that and also allows now to sort events by Reason
too.
> frontend: Improve event default sorting

- frontend/src/components/cluster/Charts.tsx
- frontend/src/components/common/Resource/CircularChart.tsx
- frontend/src/components/common/Resource/index.tsx
- frontend/src/lib/k8s/node.ts
- frontend/src/lib/util.ts
This PR is about exporting the ResourceCircularChart, used to create the cluster's overview charts, and also to export the Headlamp's lib/* modules.
In a plugin (with the new version of headlamp-plugin), add:
```typescript
import { auth, units } from '@kinvolk/headlamp-plugin/lib/Utils';
console.log('VERIFY', units, auth)
```
Look for the logs to see if they show valid modules.
PS. We need to really integrate testing in plugins imports.
> Export resource chart and lib

- CODE_OF_CONDUCT.md
- README.md
This is so Github finds it and sets the badge in the repo.
> Add Code of Conduct directly to the repo

- frontend/src/components/common/SimpleTable.tsx
- frontend/src/helpers/index.ts
Due to a mistake, the default page rows was being set as 5.
Testing:
> frontend: Do not default page rows to 5

- frontend/src/plugin/registry.tsx
- plugins/examples/details-view/src/index.tsx
It needed to return null when not matching.
> plugins: Fix details-view on not-kind view

- frontend/src/components/common/NamespacesAutocomplete.tsx
When multiple namespaces were selected, the input could show several
lines and that made the header for the contents very large vertically,
which didn't look good.
This patch changes how the namespaces are shown, so that only up to
a certain number of chars are visible for the namespace name and after
that it shows how many other namespaces are selected.
Here are examples:
Long name namespace selected + another one:
A single and short namespace selected:
If two namespaces' names fit the char limit (12 chars), then they may be displayed with the `+N` part.
fixes #593
> frontend: Make the namespaces filter values occupy just one line

- frontend/src/components/common/ActionButton/ActionButton.stories.tsx
- frontend/src/components/common/ActionButton/ActionButton.tsx
- frontend/src/components/common/ActionButton/__snapshots__/ActionButton.stories.storyshot
This fixes the Create resource button being invisible.
Open Headlamp see the Create + icon is visible.
`npm run storybook` also shows the ActionButtons with different colors / widths.
> Fix ActionButton color and width problems

- app/electron/main.ts
- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
Today I ran into the issue as described in #512 . Indeed the appVersion is sent only when the DOM is ready, but the component that acts on the received appVersion was not ready yet.
To fix this, this PR changes how the appVersion is sent. Now it's sent only when requested, guaranteeing that the component is in fact ready.
> Fix new version checks

- frontend/src/components/cluster/Chooser.tsx
- frontend/src/components/common/Dialog.tsx
This fixes #622 .
The problem was that the logo component was added to an SvgIcon which is something that is intended to be used with icons, not with generic images. Adding the component directly, fixed it.
Not sure if there are any a11y implications, but that's not an important part of the dialog for understand what it is, so I guess it's fine.
I have also added a patch to drop the typography from DialogTitle components when the respective attribute is present.
> Fix logo getting trimmed

- frontend/src/components/common/Resource/CircularChart.tsx
It was being exported only by default from its module, so it was not getting name-exported by common/index.tsx.
> Fix exporting circular chart

- frontend/src/components/common/index.test.ts
- frontend/src/components/common/index.ts
This new test allows us to check whether we have modules in `common/` that cannot be imported from `common/index.tsx`. It may require more complexity for adding whatever corner cases I may have forgotten, but it's a good start IMO.
By running it I have noticed that Charts.tsx was not being exported and started exporting it.
> Add checks for exported common components

- app/electron/main.ts
- app/electron/preload.ts
- app/package-lock.json
- app/package.json
- app/scripts/after-pack.js
- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
This is a proposal for adding a way to build Headlamp's app without having it check for updates.
@illume , I am open to a better alternative to having the options in app/package.json.
Testing:
> Allow to build without checking for updates

- frontend/src/App.test.tsx
- frontend/src/components/App/Layout.tsx
Fixes #454
The plugins can change a route, so waiting for the plugin to load stops flash-of-route-that-has-changed problem.
Change a route with a plugin, and then the default view should not be shown before the plugin is loaded.
Use the following plugin that overrides "namespaces" and go to http://localhost:3000/c/minikube/namespaces
There should be "Namespaces is overridden." text.
```tsx
import { registerRoute } from '@kinvolk/headlamp-plugin/lib';
import { SectionBox } from '@kinvolk/headlamp-plugin/lib/CommonComponents';
import Typography from '@material-ui/core/Typography';
// A component to go along with the URL path.
registerRoute({
path: '/namespaces',
sidebar: 'namespaces',
name: 'namespaces',
exact: true,
component: () => (
<SectionBox title="Feedback" textAlign="center" …
```
> Wait for plugins to load before showing views

- frontend/package-lock.json
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
After a new headlamp-plugin is released, the example plugins can be updated to the latest version and their audit issues will be gone too.
- headlamp-plugin still works locally
- frontend still runs locally
> frontend headlamp-plugin: Audit fix dependency updates

- frontend/src/components/App/Layout.tsx
- frontend/src/components/Sidebar/HeadlampButton.tsx
- frontend/src/components/Sidebar/NavigationTabs.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/common/SectionHeader.tsx
- frontend/src/components/common/SimpleTable.tsx
These changes do:
* Remove an extra left margin when on sm
* Prevent the image ID from expanding the details views horizontally
* Remove the now unneeded overflow-wrap from the image name
* Add the navigation tabs when the sidebar is the narrow static version (width=sm)
* Wrap section titles so they fit better on small screens
Testing:
> Width cosmetic fixes

- frontend/src/components/common/Resource/Resource.tsx
We should show the ports used by a container in the pod's container details.
Testing:
Go to a pod that has a container which declares ports and verify they're shown in the UI.
> frontend: Show containers' ports in UI

- frontend/src/lib/router.tsx
Add name for cluster chooser route
Go to / with a cluster chooser.
See the page has a `<title>Choose a cluster</title>`
> Add name for cluster chooser route

- frontend/src/components/App/TopBar.tsx
In a recent change, we stopped using the cluster related hooks in the
PureTopBar component as it led to conditionally using hooks. However,
those hooks (and info from them) need to be used from the wrapping
component (TopBar), otherwise no cluster chooser button will be shown.
> frontend: Fix showing cluster chooser on top bar

- frontend/src/components/App/TopBar.tsx
> Center cluster chooser

- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
It was breaking because it did not consider headlamp-plugin releases.
Use the app.
In the app, check the console for a ReleaseNotes related error that isn't there anymore.
> frontend ReleaseNotes: Fix query for latest release

- frontend/src/plugin/index.ts
Fix Plugin class based plugins not loading. Such as app-menus.
Use with app-menus.
app-menus example works again.
> frontend: Fix Plugin class based plugins not loading

- frontend/src/plugin/index.ts
So that plugins that use initialize() will not crash the system if they have an error in them.
Introduce an error into a plugin that uses the Plugin `initialize()` method of registration (like plugin/examples/app-menus) and it should not stop other plugins running.
> frontend: Catch and log Plugin initialize() errors

- frontend/src/lib/util.ts
We need to compare static dates when testing, otherwise snapshots
become outdated.
> frontend: Ensure timeAgo always uses the date + 90 days when testing

- frontend/src/plugin/index.ts
- plugins/headlamp-plugin/config/webpack.config.js
Add Material UI labs
```bash
cd plugins/headlamp-plugin
npm run build && npm run pack
cd your-plugin
npm install ../path-to/plugins/headlamp-plugin/*.tgz
```
tried to use ToggleButton in a plugin
```tsx
import { K8s, registerAppBarAction } from '@kinvolk/headlamp-plugin/lib';
import { Typography } from '@material-ui/core';
import ToggleButton from '@material-ui/lab/ToggleButton';
import ToggleButtonGroup from '@material-ui/lab/ToggleButtonGroup';
import { makeStyles } from '@material-ui/styles';
import React from 'react';
export default function ToggleButtons() {
const [alignment, setAlignment] = React.useState('left');
const handleAlignment = (event, newAlignment) => {
setAlignment(newAlignment);
};
return (
<ToggleButtonGroup
value={alignment}
exclusive
onChange={handleAlignment} …
```
> frontend headlamp-plugin: Add material ui labs

- .dockerignore
- .github/workflows/build-container.yml
- Dockerfile
- app/package.json
- frontend/.gitignore
- frontend/make-env.js
- frontend/package.json
- frontend/src/make-env.test.js
Somehow the code to generate the .env was not included and thus the version dialog was not getting correctly filled.
This PR adds those changes + a test.
Testing:
> Fix frontend version

- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/lib/router.tsx
- plugins/examples/sidebar/src/index.tsx
noCluster has been confusing to a few people. This is an attempt to improve things.
Why useClusterURL and not noCluster?
- noCluster is confusing because it's a negatively named variable
- useClusterURL is used elsewhere (when registering sidebar entries)
- useClusterURL has URL in the name, so it's a bit more descriptive
```bash
cd plugins/examples/sidebar
npm i
npm start
```
Read sidebar example; does useClusterURL make sense?
Is /no-cluster-link not a 404?
Does useClusterURL option make more sense now?
> plugins: Add useClusterURL, noAuthRequired to sidebar example

- .github/workflows/frontend.yml
- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/test-headlamp-plugin.js
An upgrade command for upgrading plugins (and folders of plugins).
For https://github.com/kinvolk/headlamp/issues/426
```bash
node plugins/headlamp-plugin/bin/headlamp-plugin.js upgrade plugins/examples
```
```bash
npx @kinvolk/headlamp-plugin upgrade plugins/examples
```
```bash
cd plugins/examples/sidebar
npx @kinvolk/headlamp-plugin upgrade
```
> plugins/headlamp-plugin: Add upgrade command

- frontend/src/components/common/Resource/MetadataDisplay.tsx
Ones that we can't get a routeName from skip.
See https://github.com/kinvolk/headlamp/issues/649
...
> frontend: Fix MetadataDisplay to skip ResourceClasses

- plugins/headlamp-plugin/README.md
- plugins/headlamp-plugin/bin/headlamp-plugin.js
headlamp-plugin upgrade improvements - check after upgrade, fail better, README.
- Check after upgrade: run lint, tsc, and such after upgrading.
- Run npm audit --fix after upgrading.
- Add the upgrade command to the README.md
- Turn on the type checker so it type checks headlamp-plugin.js
Run `node ./plugins/headlamp-plugin/bin/headlamp-plugin.js upgrade plugins/examples/pod-counter` or on another package.
Ran on some existing plugins, and there's a test in CI for the upgrade command already.
> headlamp-plugin upgrade improvements - check and audit after upgrade, fail better, README

- kubernetes-headlamp.yaml
This adds a Secret section to our sample yaml snippet.
Kubernetes 1.24+
- https://kinvolk.github.io/headlamp/docs/latest/installation/#create-a-service-account-token
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade
The relevant section from the CHANGELOG above is:
> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the …
> kubernetes-headlamp.yaml: Add Secret section for new k8s

- docs/development/plugins/functionality.md
- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/prepareRoutes.ts
- frontend/src/plugin/index.ts
- frontend/src/plugin/registry.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
- plugins/examples/sidebar/README.md
- plugins/examples/sidebar/src/index.tsx
- plugins/headlamp-plugin/lib/index.ts
Add registerRouteFilter and registerSidebarEntryFilter,
which allows plugins to remove routes, and sidebar menu items.
```tsx
import { registerRouteFilter, registerSidebarEntryFilter } from '@kinvolk/headlamp-plugin/lib';
// Remove workloads top level sidebar item
registerSidebarEntryFilter(entry => (entry.name === 'workloads' ? null : entry));
// Remove workloads route
registerRouteFilter(route => (route.path === '/workloads' ? null : route));
```
Closes #445
See plugins/examples/sidebar
```bash
cd plugins/headlamp-plugin
npm run build && npm run pack
cd ../examples/sidebar
npm i ../../headlamp-plugin/*.tgz
npm start
```
> plugins: Add registerRouteFilter and registerSidebarEntryFilter

- backend/cmd/cluster.go
- backend/cmd/headlamp.go
this patch makes sure that headlamp still works for
other clusters when one of the cluster certificate
authority is misconfigured.
Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>
> backend: Handle CA file not found error without panic

- .github/workflows/build-container.yml
- e2e-tests/kubernetes-headlamp-ci.yaml
Runs minikube, and then checks the service URL is serving minikube.
Look at the build container check.
> Add basic test of container image on minikube

- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/components/App/TopBar.tsx
- frontend/src/lib/router.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
- plugins/examples/sidebar/src/index.tsx
So plugins can hide the app bar at the top.
Closes #681
See bottom of plugins/examples/sidebar
Add "hideAppBar: true" to the route options in registerRoute.
```bash
cd plugins/headlamp-plugin
npm run build && npm run pack
cd ../examples/sidebar
npm i ../../headlamp-plugin/*.tgz
npm start
```
http://localhost:3000/c/minikube/feedback4
http://localhost:3000/no-cluster-link
> frontend plugins: Add hideAppBar option to routes

- frontend/src/components/common/Terminal.tsx
Hopefully fixes the white space additions for long lines that wrap.
Closes #697
See #697 on how to reproduce.
I tested this on a windows container, and it fixes it:
1) paste this into terminal
``` bash
echo "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" > a
type a
```
2) copy the result of "type a".
3) paste somewhere and see it is pasted as one long line.
> frontend Terminal: Use xterm.js windowsMode on Windows

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend: Don't allow objects as SimpleTable data (should be arrays)
- Fix critical crash bug due to empty object in simple table
> Fix simple table data type

- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
> Set default namespace

- frontend/src/components/common/Resource/EditorDialog.tsx
> frontend: Add fullscreen options to EditorDialog

- plugins/README.md
A couple were missing in the README.
> plugins: Fix README to mention missing examples

- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
The headlamp-plugin upgrade test was failing (causing CI to fail on unrelated PRs), because `npm audit fix` couldn't update a package properly.
- update packages for dependencies warned about by npm audit.
- turn `npm audit fix` failures into warnings.
A better fix will have to be discovered later. It should be possible for us to update dependency versions and have them work for our plugins too. Currently it's not using the correct versions of dependencies when the plugin does `npm install`. Probably the "dependency resolution" is done in a different way for sub-dependencies when they aren't all specified at the top level.
recharts has some "security issues" mentioned in some d3 dependencies. There's no new recharts release yet. For plugins they don't get the updated version even when …
> headlamp-plugin: Update recharts dependency, warn for `npm audit fix` failures

- frontend/src/test/index.tsx
- frontend/src/test/mocker.ts
These changes allow to deeply simplify the stories we have and to create them also for views which use the list/get API with data coming from the URL (namespace, name).
see an example at #744
> Simplify testing

- frontend/src/components/common/SimpleTable.stories.tsx
- frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
- frontend/src/lib/util.ts
When items to be matched in the filter are numbers, the filter was
not matching them because it first verified whether the matched items
were string.
How to test:
> frontend: Fix filter/search when items are numbers

- .github/workflows/pr-to-update-homebrew.yml
- .github/workflows/pr-to-update-minikube.yml
This patch creates a PR to update homebrew and minikube versions. The GitHub action will get triggered once the [Publish Container](https://github.com/kinvolk/headlamp/blob/main/.github/workflows/container-publish.yml) workflow completes, this ensures that the container used in minikube is the latest one. Refer to the following example PRs created by the workflow
https://github.com/yolossn/minikube/pull/4
https://github.com/yolossn/homebrew-cask/pull/5
To Dos
> Build: Create gh action to create PR

- frontend/src/components/common/ActionsNotifier.tsx
Due to how the useSelector from redux works, we were triggering
changes to the ActionsNotifier whenever anything in the redux state
was changing, so this resulted in continuously processing the cluster
actions even when those didn't change. This had side-effects like
always moving moving back to the "startUrl" when changing routes
while deleting a resource.
This patch adds the evaluation function to the mentioned selector, so
it will only trigger when actually the actions change.
We should still move the URL processing of the actions to somewhere
where it can be better controlled, or to remove it completely and
allow actions to define callbacks for each action state instead
(cancelled/errored), meaning they'd call the route changes themselves
when desired.
fixes #715 
How to test:
1. Go …
> frontend: Ensure cluster actions are only processed when they change

- frontend/src/lib/k8s/apiProxy.ts
In connecStream, the original way will cause duplicated protocol pushed into variables which additionalProtocols refer to.
> frontend: Fix duplicated protocol in reference

- .github/workflows/pr-to-update-homebrew.yml
This patch fixes the auth issue that occurred in gh action, there was an extra space which is removed now.
> ci: Fix homebrew gh action auth issue

- frontend/src/lib/k8s/apiProxy.ts
According to code comment, set reconnectOnFailure as true by default if the failCb has not been provided. So, it should be single exclamation mark.
> frontend: Fix reconnectOnFailure according to comments

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
In Resource.ts, list pod in OwnedPodsSection with query parameters. If users only have namespace access, list all pods isn't available.
Instead of filtering pods list, OwnedPodsSection query pods with label selectors and field selectors.
Test list pods in deployment with query parameters.
> frontend: List pods in OwnedPodsSection with query parameters

- frontend/src/components/pod/List.tsx
- frontend/src/lib/k8s/cluster.ts
- frontend/src/lib/k8s/pod.ts
- frontend/src/lib/util.ts
Print pod status following kubectl convention. https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L759
The pod status in Headlamp cannot describe the full picture of the container status. It is confusing when user see running pod status marked with yellow. So, I change status and restarts by following the link I provide above. 
In this PR.
Current situation.
This is pretty wired 
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
> frontend: Print pod status following kubectl

- frontend/src/components/cluster/Overview.tsx
Allow to search by type for events table
Go to cluster overview page go to events table search with a resource type and it would filter the table based on resource type
fixes #769
> frontend: Add filter by type for events section

- frontend/src/lib/k8s/cluster.ts
This function was setting its state every time new data was returned
by the API function, but that data may be the same as before, which
would still trigger a change in any component using it. Thus, this
patch makes it so that the state only changes if the resourceVersion
changes.
fixes #783
> frontend: Optimize KubeObjectClass.useGet so it updates iff needed

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
- frontend/src/lib/k8s/index.test.ts
- frontend/src/lib/k8s/index.ts
In Resource.ts, list pod in OwnedPodsSection with query parameters. If users only have namespace access, list all pods isn't available.
Branch created from #760 so we can rework the PR a bit.
cc/ @lijianzhi01 
Instead of filtering pods list, OwnedPodsSection query pods with label selectors and field selectors.
* Test list pods in deployment with query parameters. 
* Run `make frontend-test` to run the unit tests for the query conversion function.
> Fetch pods by labels

- frontend/src/components/common/Terminal.tsx
Toggle full screen without resizing terminal. Text will not auto fit into columns. 
Fit after toggle.
> frontend: Resize terminal in toggle fullscreen

- frontend/src/i18n/ThemeProviderNexti18n.tsx
Before it wasn't setting it on page load. So, if you were already in a non-english language then the attribute would not be set.
This causes the browser confusion about the language being used.
- Set Headlamp to non-en language. 
- Reload the page. 
- It should have set the html lang attribute correctly. eg. `<html lang="uk">`
see how to use ^
> frontend i18n: Set the html lang when page loads too

- frontend/src/components/App/Notifications/index.tsx
- frontend/src/helpers/helpers.test.ts
- frontend/src/helpers/index.ts
- frontend/src/lib/notification.tsx
- frontend/src/redux/reducers/ui.tsx
This PR limits the message field of the notifications to 250 chars, and the number of notifications stored to 200 (by default).
Maybe we should limit more fields in the notification class, but this was an obvious one that we should control.
**How to test:**
- Frontend tests are also added
fixes #815
> Limit notifications

- frontend/src/lib/util.ts
So this is not changed according to the developer's locale when
creating new snapshots.
> frontend: Force 12 hour clock when under tests

- frontend/src/lib/util.ts
Snapshots were failing if the locale of the developers' machines is
not the same.
These changes specify the mentioned locale and update the snapshots.
> frontend: Specify the locale for localeDates when testing

- frontend/src/components/App/Notifications/List.tsx
- frontend/src/components/App/Notifications/index.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
- frontend/src/components/Sidebar/Sidebaritem.stories.tsx
- frontend/src/components/common/SectionFilterHeader.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/lib/router.tsx
This patch adds two route entries /notifications and /cluster-chooser  and also add a "view all notifications" to notification popup.
Go to notification popup click on view all notification and you will be taken to notification list view
fixes #644
> Add notification and cluster-chooser page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/ActionButton/ActionButton.tsx
- frontend/src/components/common/LogViewer.tsx
- frontend/src/components/pod/Details.tsx
- frontend/src/components/pod/PodLogs.stories.tsx
- frontend/src/lib/k8s/pod.ts
- frontend/src/setupTests.ts
This PR changes how the logs are rendered, it namely:
* Allows selected text to remain selected even if new logs arrive
* Allows copying logs
* Improves the performance by only rendering the logs that have not yet been shown
* Adds search to logs
* Allows to stop following logs (pauses the stream)
fixes https://github.com/kinvolk/headlamp/issues/785
Testing:
* There's a new story for checking logs in the Storybook
* Go to a pod that has logs or create a [pod that logs constantly](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/debug/counter-pod.yaml) and click the logs button
> Render logs using xterm

- frontend/.storybook/preview.tsx
- frontend/src/lib/k8s/apiProxy.ts
- Fix storybook config to add port to mocked URLs
- Fix errCb guard to see if it's a function
This was the error shown in the console.
```ts
Failed to load resource: net::ERR_CONNECTION_REFUSED
apiProxy.ts:204 
Unable to parse error json at url: http://localhost:4466/api/v1/namespaces Object with request data: Object
request @ apiProxy.ts:204
apiProxy.ts:583 
Error in api request Object
run @ apiProxy.ts:583
apiProxy.ts:584 
Uncaught (in promise) TypeError: errCb is not a function
at run (apiProxy.ts:584:1)
```
- Go to SimpleTable story http://localhost:6006/?path=/story/simpletable--name-search
- See no error (after this PR).
see ^
> small storybook fixes for SimpleTable

- .gitignore
- docs/development/frontend.md
- frontend/src/components/common/Resource/ResourceTable.tsx
- frontend/src/components/common/SimpleTable.stories.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
- frontend/src/components/crd/Details.tsx
- frontend/src/components/daemonset/Details.tsx
- frontend/src/components/endpoints/Details.tsx
- frontend/src/components/endpoints/EndpointDetails.stories.tsx
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/ingress/Details.tsx
- frontend/src/components/pod/Details.tsx
- frontend/src/components/pod/List.tsx
- frontend/src/components/role/BindingDetails.tsx
- frontend/src/components/role/Details.tsx
- frontend/src/components/service/Details.tsx
- frontend/src/lib/util.ts
- frontend/src/test/index.tsx
These changes introduce a new useURLState which is the same as React.useState but reflects that state as a URL search parameter. For flexibility it can also be used as a plain useState, if the key passed to it is false.
It also makes sure that all tables in Headlamp are reflected in the URL.
The default values of the page and rowsPerPage are not shown in the URL (maybe for the latter it'd be a good idea since users may have a different default number for it but I haven't changed it).
BTW, I can also add the reflectURL logic as a new TableWithPropsInURL rather than having a `reflectInURL` prop (but it's been a while since the `SimpleTable` is simple, we might as well just call it table 😛 ).
**Tests:**
Go to a view that has a table; change the page and rows per page -> you should see those …
> Reflect table pages in the URL

- frontend/src/components/cluster/Chooser.tsx
fixes #623
- have more than one cluster
- use the change-logo plugin
- open the cluster chooser
see ^
> frontend: Fix cluster chooser title to use custom logo

- frontend/src/lib/util.ts
- frontend: Don't replace the location when updating URL params
- frontend: Optimize reflecting default states in the URL
How to test:
> Fix navigation when URL params are enabled

- frontend/src/components/App/Notifications/List.tsx
- frontend/src/components/common/SectionFilterHeader.tsx
When the user moves to a different route, the search filter is reset
(to an empty string), but this goes through redux, so when the new
route is rendered, the search filter is still the old one. Eventually,
the redux state will be updated, but at this point we already have the
filter being shown (when it should actually be shown). OTOH, if we
always hide the filter when the search (and namespace) are empty, it
will also hide when the user deletes the whole string, and that's not
desireable (because they may want to keep writing and at that point the
filter has een hidden and input is lost).
To solve this, we keep track of whether the filter has been shown by
the user, in which case we don't hide it even when the search is empty.
fixes #837 
**How to test (filter means filter header)**
> frontend: Show/hide filter depending on the search + who triggered it

- frontend/src/components/Sidebar/Sidebar.tsx
The special sidebar should not have the plus nor the version buttons,
since they are tied to the concept of having a current cluster.
> frontend: Don't show bottom buttons in special sidebar

- app/windows/chocolatey/choco-bump.sh
- app/windows/chocolatey/headlamp.nuspec
- app/windows/chocolatey/tools/chocolateyinstall.ps1
- app: Fix choco-bump.sh's processing of paths with spaces
- app: Bump chocolatey version to Headlamp 0.14.0
> choco headlamp 0.14.0

- frontend/src/components/common/Resource/__snapshots__/ResourceTable.stories.storyshot
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointList.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/pod/__snapshots__/Volumedetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassList.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.stories.storyshot
So that other header cells still have the opportunity to wrap if they want to. Meaning there's less chance of a problem with header cells that used to fit with wrapping.
**Important:** The PR #835 was closed by mistake after I pushed what I believed was just the PR rebased on main. This PR has the changes @illume had made to it + rebased on main, so it should be fine.
> frontend SimpleTable: Make nowrap only on sort having header cells

- frontend/src/plugin/index.ts
- frontend/src/plugin/lib.ts
- plugins/examples/app-menus/src/index.tsx
The return code for `Plugin.initialize()`:
- was never used by anything. Don't require a return value
- is now `void | boolean` not `void` for backwards compatibility
Just a code cleanup.
> frontend: The Plugin.initialize return value isn't used, remove

- frontend/src/components/common/Resource/EditButton.tsx
The onSave function from the EditorDialog is now called with an array
of resources instead of just one resource, but the EditButton logic
was not changed to accommodate that.
This patch fixes that as well as the typing for the EditButton which
was expecting a KubeServiceAccount by mistake.
fixes #858 
How to test:
-  [ ] Edit any resource: it should allow to do so.
> frontend: Fix editing resources

- frontend/src/components/common/Resource/EditorDialog.tsx
We were assuming that if the code is JSON, it should have either a
starting { or [, or an ending ] or }. However, the code can very well
be YAML and end in ]. So this patch makes Headlamp only consider the
starting character of the mentioned logic.
For example, this YAML was being interpreted as JSON and thus not let the user apply it from the UI:
```YAML
kind: Pod
apiVersion: v1
metadata:
name: test
spec:
containers:
- name: cont-1
image: ubuntu
command: ["/bin/bash", "-c", 
"while true; do echo Hello-Coder; sleep 5 ; done"]
```
**How to test:**
> frontend: Fix failed assumption of JSON code

- frontend/src/components/common/Terminal.tsx
When connecting or connected to a container (via exec), if it fails and Headlamp runs through the list of available shells, then there's no way to retry them (except for refreshing the page).
See #866 for a report where this happens. Even though this patch doesn't try to fix the cause for which the connection is lost after a couple of minutes (not even sure if we can avoid it), it does allow the user to recover because after it runs through the list of terminals it will display a message "Press enter to reconnect" and retry all shells again once the user presses enter.
In the future we shall add UI to select/enter a shell command and to directly refresh it, but for now this is a very non-intrusive solution.
fixes #866 
**How to test:**
> Allow terminal to reconnect after failure

- frontend/src/components/common/Resource/AuthVisible.tsx
- frontend/src/components/common/Resource/DeleteButton.tsx
- frontend/src/components/common/Resource/EditButton.tsx
- frontend/src/components/common/Resource/ScaleButton.tsx
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/pod/Details.tsx
- frontend/src/components/pod/PodLogs.stories.tsx
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/lib/k8s/cluster.ts
This PR adds a component that verifies the permissions for some action and only renders its children if those are valid.
It replaces the repeated logic for checking for permissions for actions such as edit/delete/etc.
This PR also makes the logs and exec actions based on permissions.
fixes #767 
**How to test:**
> Add easier auth buttons + make logs/exec dependent on permissions

- .github/workflows/app-artifacts-linux.yml
- .github/workflows/app-artifacts-mac.yml
- .github/workflows/app-artifacts-win.yml
- .github/workflows/app.yml
- .github/workflows/build-container.yml
- .github/workflows/frontend.yml
- .github/workflows/helm-chart-lint-test.yml
- .github/workflows/helm-chart-release.yml
- Dockerfile
- Makefile
Update Node 18LTS, Ubuntu 22LTS, Alpine 3.17 stable
- https://www.releases.ubuntu.com/22.04/
- https://nodejs.org/en/blog/announcements/v18-release-announce/
- https://www.alpinelinux.org/posts/Alpine-3.17.0-released.html
This means, we should use Node 18 and the corresponding new npm (8.19) locally for front end package updates.
Note, we already moved to go 1.19 in the images, but the new alpine also includes go 1.19 by default.
It should work as before, just with newer dependencies.
> Update Node 18LTS, Ubuntu 22LTS, Alpine 3.17 stable

- frontend/src/components/common/Resource/__snapshots__/MetadataDisplay.stories.storyshot
- frontend/src/components/common/Resource/__snapshots__/ResourceTable.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointList.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassList.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.stories.storyshot
- frontend/src/lib/util.ts
Node has changes how they format the dates when using "toLocaleString",
introducing a special character (U+202f) instead of a space.
Our first instinct was to lower the Node version and wait for a fix,
but according to [1], Node doesn't seem to be reverting it soon and
mentions one shouldn't use localized strings for testing...
So, in order to avoid this, this patch makes the dates show up in
ISO format.
[1] https://github.com/nodejs/node/issues/46123
> frontend: Use ISO format for dates tests

- frontend/src/lib/auth.ts
- frontend/src/plugin/registry.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
We want to have the ability for the plugins to override the getToken and setToken methods and this patch provides the mechanism to do that.
> Allow Overriding token management

- frontend/src/components/common/Resource/DocsViewer.tsx
- frontend/src/index.tsx
With a recent CRA update node related modules are not shipped with CRA anymore. This broke the doc viewer as it was using the buffer module. We already had a patch earlier that added the polyfill but one problem with polyfilling it in a place like index.tsx is that when building the frontend for production, the polyfill is not included. The correct place to polyfill is to include it at the place where it is being used.
> frontend: Fix doc viewer breaking

- app/.babelrc
- app/electron/main.ts
- app/package-lock.json
- app/package.json
There was an issue with @babel/runtime not loading the correct module when running the app. This was fixed by using @babel/polyfill moreover we don't need the entire @babel/runtime and @babel/plugin-transform-runtime when we only have two typescript files to be compiled.
Run the app and all the preload related settings will start working now
> app: Remove @babel/runtime instead use regenerator-runtime

- frontend/src/components/App/Notifications/List.stories.tsx
- frontend/src/components/App/Notifications/__snapshots__/List.stories.storyshot
- frontend/src/helpers/index.ts
- frontend/src/lib/notification.tsx
The message was being stored as _message in the local storage due to being its variable name in the class and it would not get correctly assigned nor would the stored notifications be unmarshalled as Notification objects.
This patch fixes that and guarantees that the notifications' marshalling is under control.
How to test:
[ ] Verify that the notifications do have a title when they before didn't.
> Fix notifications

- frontend/src/components/App/Notifications/List.tsx
- frontend/src/components/App/settings/index.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
- frontend/src/components/common/BackLink/BackLink.tsx
- frontend/src/components/common/BackLink/index.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/common/SectionBox.tsx
- frontend/src/components/common/index.test.ts
- frontend/src/components/common/index.ts
Now that we have a settings and notifications view, the sidebar's back link button can be very confusing to use.
So these changes implement the new design, which allows to go back or to go to the home view where the user can choose the cluster.
> Update settings/notifications view sidebar and navigation

- backend/cmd/cluster.go
- backend/cmd/headlamp.go
- backend/cmd/kubeconfig.go
This patch adds support for using an HTTP proxy with clusters that
have it set up in their kubeconfig.
This is related to #916 .
@yolossn I am not sure if this is enough. Maybe you can help test this out.
> Support http proxy from the kubeconfig

- frontend/src/components/common/ObjectEventList.tsx
This patch fixes how the age columns is getting calculated and also
moves it to be the last column, in order to be consistent with how we
order the columns across Headlamp.
> frontend: Format age column in event list (in resources' section)

- frontend/src/components/portforward/index.tsx
We were not filtering out the list view of portforward based on the cluster they are part of, this patch fixes that and only shows portforwards that are part of the current cluster.
> Fix portforward list

- frontend/src/plugin/index.ts
So plugins can use it.
window.pluginLib.Crd should be available.
This is required so tests can use lib/k8s/crd. To make it more convenient for future headlamp-plugin versions, the headlamp needs to expose this. Related to https://github.com/headlamp-k8s/headlamp/pull/795
> frontend: Add pluginLib.Crd for exposing lib/k8s/crd

- frontend/src/components/Sidebar/Sidebar.tsx
How to test:
- Go to settings, choose a non-English locale
- Go to the cluster chooser or some other area
- Click settings again, and then click the Settings sidebar entry or the Notifications one -> it should still show the special sidebar (Cluster + Notifications + Settings) as opposed to the regular sidebar
> Fix sidebar on locale

- charts/headlamp/README.md
- docker-extension/Dockerfile
This only updates the instances of the `kinvolk.github.io` URLs to `headlamp-k8s.github.io` as GitHub Pages doesn't do automatic redirects which means the docs don't work to add the Helm repo.
Any `github.com/kinvolk/headlamp` references have been left as-is.
> helm: update chart URL to headlamp-k8s namespace

- app/scripts/push-release-assets.js
Otherwise the assets don't actually get pushed.
> app: Update repo org in push-release-assets script

- .github/workflows/app-artifacts-win.yml
- .github/workflows/docker-extension-release.yml
- .github/workflows/draft-release.yml
- Makefile
- README.md
- app/electron/main.ts
- app/package.json
- app/windows/chocolatey/headlamp.nuspec
- app/windows/chocolatey/tools/chocolateyinstall.ps1
- backend/cmd/server.go
- backend/go.mod
- backend/pkg/config/config_test.go
- charts/headlamp/Chart.yaml
- charts/headlamp/README.md
- charts/headlamp/values.yaml
- docker-extension/Dockerfile
- docker-extension/docker-compose.yml
- docs/contributing.md
- docs/development/_index.md
- docs/development/frontend.md
- docs/platforms.md
- e2e-tests/kubernetes-headlamp-ci.yaml
- plugins/headlamp-plugin/template/README.md
We have recently moved the org from kinvolk to headlamp-k8s but we
left certain things still mentioning the kinvolk org because there
are redirects in place, but they don't work for certain things like
git clones, container registries, etc.
> Replace kinvolk by headlamp-k8s in a lot of content

- frontend/src/components/common/Resource/MetadataDisplay.tsx
> frontend: Fix formatting owner references for CRs

- frontend/src/components/App/Notifications/__snapshots__/List.stories.storyshot
- frontend/src/components/App/settings/__snapshots__/Settings.stories.storyshot
- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/common/SectionFilterHeader.tsx
- frontend/src/components/common/SectionHeader.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/common/__snapshots__/SectionBox.stories.storyshot
- frontend/src/components/common/__snapshots__/SectionHeader.stories.storyshot
- frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointList.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodList.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/pod/__snapshots__/Volumedetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassList.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.stories.storyshot
Users want to filter simply by clicking a switch to list all the warning type events, this patch adds that to the events table.
> frontend: Add a warning filter  switch to events table

- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/lib/util.ts
In #939 , I didn't notice I was merging an extra filter property into the SimpleTable. This is unnecessary and would create confusion for users.
This PR removes that and reimplements the filter by using the default function + the warning check.
How to test:
1. Verify the combination of search/filter for events and the warning switch work fine.
> Remove extra simple table filtering

- docs/development/frontend.md
- frontend/src/index.tsx
Still allow enabling the alert with
`REACT_APP_SKIP_A11Y=false make run-frontend`
When running `make run-frontend` the alert will not be shown.
> frontend: Disable a11y alert by default

- frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
- frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.tsx
- frontend/src/components/common/ReleaseNotes/UpdatePopup.stories.tsx
- frontend/src/components/common/ReleaseNotes/UpdatePopup.tsx
- frontend/src/components/common/ReleaseNotes/__snapshots__/ReleaseNotesModal.stories.storyshot
- frontend/src/components/common/ReleaseNotes/__snapshots__/UpdatePopup.stories.storyshot
We have a 5 second window for a update fetch, this patch adds feedback for all the actions that happen in that 5 sec window like fetching release and also if the release fetch failed and shows them in the update Snackbar
> frontend: Add feedback via update popup for release fetch

- docker-extension/Dockerfile
- docker-extension/docker-compose.yml
- frontend/src/components/authchooser/index.tsx
- frontend/src/helpers/index.ts
- frontend/src/i18n/locales/en/auth.json
- frontend/src/i18n/locales/es/auth.json
- frontend/src/i18n/locales/pt/auth.json
Steps to test
[[Hard Mode]]
- `docker build . -t ghcr.io/kinvolk/headlamp:v0.15.0` in project home directory
- `cd  docker-extension`
- `docker build . -t headlamp-dd`
-  `docker extension install headlamp-dd`
-  Go to docker desktop dashboard and test
[[Easy mode]] 
- `docker extension install yolossn/headlamp-dd-extension`
-  Go to docker desktop dashboard and test
Flows:
1. The user has a `~/.kube/config` file with a proper cluster config -> Headlamp opens to the dashboard UI directly
2. The user has a `~/.kube/config` file but the cluster is not accessible -> The user gets the following message
`Failed to connect. Please make sure the Kubernetes cluster is running and accessible. Error: {{ errorMessage }}`
3. The user doesn't have a `~/.kube/config` file, the user is shown a message …
> Docker desktop setup instructions and change exposed port

- frontend/src/components/Sidebar/prepareRoutes.ts
- frontend/src/components/portforward/index.tsx
- frontend/src/i18n/locales/en/glossary.json
- frontend/src/i18n/locales/en/resource.json
- frontend/src/i18n/locales/es/glossary.json
- frontend/src/i18n/locales/es/resource.json
- frontend/src/i18n/locales/pt/glossary.json
- frontend/src/i18n/locales/pt/resource.json
It was "port forwards" but @blixtra brought to my attention this was not correct.
> frontend: Rename port forwarding

- frontend/src/components/Sidebar/Sidebar.tsx
- plugins/examples/sidebar/src/index.tsx
We were not updating the sidebar when the plugin-added filters are updated after the sidebar is first rendered, so this made it impossible to register filters from within components' side effects.
How to test:
> Fix sidebar not reacting to filters

- frontend/src/components/App/TopBar.tsx
- frontend/src/components/App/settings/clusters.tsx
- frontend/src/components/account/Auth.tsx
- frontend/src/components/account/AuthToken.stories.tsx
- frontend/src/components/authchooser/AuthChooser.stories.tsx
- frontend/src/components/authchooser/index.tsx
- frontend/src/components/cluster/Charts.tsx
- frontend/src/components/common/NamespacesAutocomplete.tsx
- frontend/src/components/namespace/List.tsx
- frontend/src/helpers/index.ts
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
- frontend/src/lib/k8s/priorityClasses.ts
- frontend/src/lib/router.tsx
> Add accessible namespaces

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
For issue #983 
Creates an additional field for Init containers under the regular containers when in the pod view.
> frontend init-containers: Includes init containers to pod containers

- frontend/src/test/index.tsx
Jest is not made available to storybook, except in the test runner.
Fixes https://github.com/headlamp-k8s/headlamp/issues/1029
How to test?
```bash
cd frontend
npm run storybook
```
> frontend: Remove the usage of jest in the storybook

- Makefile
This patch removes the 'v' that was used in the
docker image tag to follow semantic versioning
> make: Use semantic version for docker ext tag

- .github/workflows/docker-extension-release.yml
- docker-extension/Dockerfile
- docker-extension/docker-compose.yml
The docker extension release action is also responsible for updating the base image used by the docker extension, due to a bug that was introduced when manual trigger was added to this github action the automatic updating part didn't work. This patch fixes it
> Fix docker ext release

- frontend/package.json
- frontend/src/components/common/Resource/EditorDialog.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/plugin/index.ts
- plugins/headlamp-plugin/config/webpack.config.js
This PR covers two scenarios:
- Load Monaco Editor from node_module instead of cdn for airgaped environment.
- For those of who want to create monaco editor in plugin, they can leverage monaco editor exported from frontend. It can reduce the size of plugin. In our case, we create editor for manage data stored in annotation.
> frontend: Load Monaco from node_module and export Monaco to plugin

- frontend/src/components/cluster/KubeConfigLoader.tsx
Instead of always going back to the root location, the
load-kube-config dialog should go back to whatever location that
originated it, so this patch adds that behavior.
> frontend: Go back using the "back" function from load-kube-config

- docs/installation/desktop/_index.md
Headlamp now supports reading from multiple kubeconfig files.
> docs: Fix KUBECONFIG section on multiple config files

- frontend/src/components/common/Terminal.tsx
- frontend/src/components/pod/Details.tsx
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/lib/k8s/pod.ts
> frontend: Add attach to pod option

- app/mac/scripts/notarize.js
This is required if there are multiple keys set up on the machine doing the notarization.
> app: Notarize with ascProvider set

- frontend/src/components/App/TopBar.tsx
- frontend/src/components/common/Resource/DeleteButton.tsx
- frontend/src/components/common/Resource/EditButton.tsx
- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/common/Resource/RestartButton.tsx
- frontend/src/components/common/Resource/ScaleButton.tsx
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/pod/Details.tsx
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/runtimeClass/__snapshots__/Details.stories.storyshot
- frontend/src/plugin/index.ts
- frontend/src/plugin/registry.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
- plugins/examples/details-view/src/index.tsx
- plugins/headlamp-plugin/lib/index.ts
Instead of allowing to just add (append) header actions, we want plugins to be able to process the list of header actions in details views. The idea is that plugins supply a function that is given the current list of header actions and should return a list of header actions to display, allowing them to add/remove/update such actions.
An example is provided in the details-view example plugin.
> Allow plugins to process the list of header actions

- .github/workflows/container-publish.yml
- Dockerfile
- Makefile
Refactor the Docker image to support cross-compiling and update the CI pipeline to publish arm64 images in addition to the amd64 images already being published.
There's also some general improvements here, e.g. the Go builds copy `go.{mod,sum}` and run `go mod download`, cache volumes, use of `COPY --link`, removal of unnecessary base images.
This removes the symlink for `/headlamp/server`, which has been around for almost a year for compatibility. (Keeping it will add a dependency on QEMU to run the `cd` / `ln` commands, as it's the only command run in the final image, which is for the _target_ arch, not the _build_ arch.)
CI also uses GitHub Actions cache now - free speed-up!
The builds are also done with `pull: true` to ensure that the latest Go / Node / Alpine patch versions get used. …
> ci: add multi-platform (arm64) Docker images

- frontend/src/components/App/RouteSwitcher.tsx
- frontend/src/components/Sidebar/NavigationTabs.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
- frontend/src/components/Sidebar/prepareRoutes.ts
- frontend/src/lib/router.tsx
- frontend/src/plugin/registry.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/reducers/ui.tsx
- plugins/examples/sidebar/src/index.tsx
- plugins/headlamp-plugin/lib/index.ts
This PR improves the sidebar, more particularly, it stops special casing the "home" sidebar and now supports having several sidebars, creating new ones, and controlling them from plugins.
It also fixes smaller issues like the special casing of the sidebar matching routes by name or cloning default routes by stringifying/unstringifying them...
This was part of the multi-cluster improvements but it's important enough that we can treat it separately.
Unfortunately, due to not easily being able to import types from plugins, I couldn't use the `DefaultSidebars.HOME` constant to refer to the home sidebar. Maybe @illume has a solution for this.
How to test:
> Improve sidebar

- plugins/headlamp-plugin/bin/headlamp-plugin.js
Before, only the extract command copied it. But this meant that during development using npm start, the package.json file was not copied.
> headlamp-plugin: Fix npm start to also copy package.json

- frontend/src/lib/k8s/index.ts
- frontend/src/redux/reducers/clusterAction.tsx
- frontend/src/redux/reducers/config.tsx
- frontend/src/redux/reducers/filter.tsx
- frontend/src/redux/reducers/ui.tsx
The auth chooser was getting an error when checking for a cluster's
auth because of how the cluster's state is set. It sets the state
directly and then calls dispatch, but since the object being modified
is the same that redux holds, redux detected this and it threw an
exception.
To prevent this case, the useClustersConf hook now returns a copy of
the state instead.
> frontend: Clone the clusters conf to prevent direct state changes

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/prepareRoutes.ts
- frontend/src/lib/router.tsx
It was not migrated to the new way sidebars are defined, so it was
no longer visible. This patch removes the legacy code and sets up
the sidebar properly.
> frontend: Fix plugins settings sidebar entry

- backend/cmd/headlamp.go
- backend/cmd/plugins.go
This is so we can have bundled plugins without affecting the user's
own plugin dir. For it is set by an env var.
> backend: Support a static plugins dir

- backend/pkg/helm/release.go
We don't need helm annotations now that we get the chart version.
> backend: Remove not required helm annotations

- app/windows/chocolatey/headlamp.nuspec
- app/windows/chocolatey/tools/chocolateyinstall.ps1
Choco bump. Version already tested locally and pushed to Chocolatey's registry.
> chocolatey: Bump Headlamp version to 0.17.0

- frontend/src/components/Sidebar/Sidebar.tsx
fixes #1120 
**Wide button**
**Icon-only button**
How to test:
> frontend: Use single-icon button for sidebar's add-cluster

- frontend/src/components/Sidebar/NavigationTabs.tsx
Fixes for issue #1115
Essentially, this an issue on the desktop app when the user is within a small screen view and on the settings page, if you click the navigation tab while in settings or plugins they do not work.
I was able to track the issue down while trouble shooting it in web environment and it seems to do a few things.
The first lead with this issue occurs within the console
Currently:
PLEASE NOTE: Currently debugging this issue from the web client, the router.tsx file has been edited to work with web client, under the plugins route field, disabled is temporarily set as `disabled: helpers.isElectron()` and will be reset to `disabled: !helpers.isElectron()`
- I have tried turning on and off useCluster field as well as trying to use noCluster (although its deprecated) within the …
> frontend NavigationTabs: Plugin Settings Nav Links Fix

- .github/workflows/build-container.yml
- .github/workflows/helm-chart-lint-test.yml
- Dockerfile
- Dockerfile.plugins
- Makefile
- charts/headlamp/values.yaml
- e2e-tests/kubernetes-headlamp-ci.yaml
- e2e-tests/tests/headlamp.spec.ts
So it's not run as root, it runs as a "headlamp" user.
It's a docker security best practice according to these guides:
- https://snyk.io/blog/10-docker-image-security-best-practices/
- https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
Also, make the container workflow run when Dockerfile is changed.
It should run as before.
> Dockerfile: Implement least privileged user

- Makefile
- backend/cmd/headlamp.go
- frontend/src/components/cluster/KubeConfigLoader.tsx
> Misc improvements for loading a cluster

- frontend/src/components/cluster/KubeConfigLoader.tsx
> Fix loading kubeconfig

- backend/cmd/headlamp.go
The path cleaning didn't work on windows.
Additionally, support unix paths for html-static-dir like 'frontend/build'.
Fixes #1094
- build on windows
- use cmd (not bash) and run `backend\headlamp-server.exe --dev=true --proxy-urls=* --html-static-dir=frontend/build`
- http://localhost:4466/static/ should work
- directory traversal should not work. Eg. `http://localhost:4466/../../../etc/passwd`
> backend: Fix --html-static-dir cmd line option on windows

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/pod/List.tsx
- frontend/src/lib/k8s/cluster.ts
fixes #1128 
Acceptance criteria
> Fix namespace pods

- app/electron/main.ts
- backend/cmd/headlamp.go
- frontend/src/helpers/index.ts
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/plugin/index.ts
- frontend/src/plugin/registry.tsx
This prevents some backend endpoints from being called unless there is a token passed in via the X-HEADLAMP_BACKEND-TOKEN header. The app generates the token and then sets HEADLAMP_BACKEND_TOKEN environment variable which the backend uses. This also makes available a getHeadlampAPIHeaders() function which can be used by the frontend and plugins to add headers to API endpoints that the backend serves. App creates token and sends it to the backend and frontend. This prevents unauthorized connections to the helm chart endpoints. The threat was that any connection from a Browser or localhost process could call helm and dynamic cluster creation endpoints.
Here's the steps of how the token gets generated, passed around and checked:
Here's how you use the headers for `fetch()` in a plugin:
```ts …
```
> frontend backend app: Prevent unauthorized access to helm endpoints

- frontend/src/components/common/Resource/Resource.tsx
> frontend: Do not show namespace filter in resources' namespace

- frontend/src/lib/k8s/index.ts
Before every time the location changed this was being recalled. This lead to some pretty big unneeded network calls and recalculations every time a URL was changed... even when the cluster had not changed.
It should help performance on large clusters because there are less network calls that aren't needed, and also less recalculations.
cc / @lijianzhi01 
related to https://github.com/headlamp-k8s/headlamp/issues/1161
> frontend lib/k8s: Fix useConnectApi to depend on cluster not location

- frontend/src/components/networkpolicy/Details.tsx
This patch checks for the members of the networkpolicy resources
before using them, to prevent failure.
> frontend: Prevent failure when rendering networkpolicy/Details

- frontend/src/components/App/Notifications/index.tsx
This will make the number of events to process much smaller and thus
be more optimal.
> frontend: Only get non-normal events for notifications

- frontend/src/components/common/Resource/ResourceTable.tsx
Throttles the data updates on tables to once per second. When new data comes in it is shown right away, but if more comes in within the next second it is not shown until 1 second has past. So there should be new data right away in most cases, and it should be limited to how fast it updates otherwise.
> frontend ResourceTable: Throttle data updates to 1Hz

- charts/headlamp/README.md
- charts/headlamp/templates/deployment.yaml
- charts/headlamp/templates/secret.yaml
When installing charts, oidc was being provided as config and since this contains sensitive information it should have been provided as secret.
Fixes: #1160
> charts: OIDC config via secrets

- backend/pkg/cache/cache.go
- backend/pkg/helm/handler.go
- backend/pkg/helm/release.go
This PR fixes the following:
- The get status function fails when an error occurs in the async task. This was due to unmarshalling error with the type error.
- In install release function the request validation error was missing a return statement that is fixed.
- Due to an issue in the cache clean up logic the cached values were dropped before the validity expiry.
> Helm endpoints bug fixes.

- docs/development/plugins/functionality.md
- frontend/src/plugin/registry.tsx
- plugins/examples/app-menus/README.md
- plugins/examples/cluster-chooser/README.md
- plugins/examples/details-view/README.md
- plugins/examples/dynamic-clusters/README.md
- plugins/examples/pod-counter/README.md
- plugins/examples/sidebar/README.md
They are not mixed case anchors on the website.
How to test:
- does not work (stays at top of page): https://headlamp.dev/docs/latest/development/api/modules/plugin_registry/#registerRouteFilter
- does work (jumps to registerRouteFilter): https://headlamp.dev/docs/latest/development/api/modules/plugin_registry/#registerroutefilter
> docs: Fix anchors in functionality.md and in plugin example READMEs

- frontend/src/components/node/Details.tsx
- frontend/src/redux/actions/actions.tsx
- frontend/src/redux/sagas/sagas.tsx
Steps to reproduce 
1. Go to node detail view and press either the drain node or the cordon node icon
2. Pressing the drain or cordon node icon shows a notistack saying cancel the drain or cordon
Acceptance Criteria
> Fix drain, cordon icon

- frontend/src/helpers/index.ts
- frontend/src/lib/k8s/apiProxy.ts
- frontend apiProxy: Add some docs and debug logging
Added some helpers to allow us to sprinkle plenty of verbose debug calls in there.
To add some verbose debugging to a module:
```ts
import { isDebugVerbose } from './helpers';
if (isDebugVerbose('k8s/apiProxy')) {
console.debug('k8s/apiProxy', {dataToLog});
}
```
You can also include a symbol name:
```ts
import { isDebugVerbose } from './helpers';
if (isDebugVerbose('k8s/apiProxy@refreshToken')) {
console.debug('k8s/apiProxy@refreshToken', {dataToLog});
}
```
In that example:
- 'k8s/apiProxy' is the module name.
- 'refreshToken' is the function symbol name.
To turn verbose debugging on via code in that module:
```ts
import { debugVerbose } from './helpers';
debugVerbose('k8s/apiProxy')
// or for everything in refreshToken: …
```
> frontend apiProxy: Add some docs and debug logging

- frontend/src/components/cluster/Overview.tsx
Issue:
go to cluster overview page, click on events warning switch, 
now click again to turn it off, 
switch to some other page and come back to cluster overview page, you will find the switch is always on if switched once.
This is fixed by parsing the value of event switch before making it as a default value
> frontend: Fix warning switch always on bug.

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/common/AlertNotification.stories.tsx
- frontend/src/components/common/AlertNotification.tsx
- frontend/src/lib/k8s/apiProxy.ts
- frontend: Add testClusterHealth function
- frontend: Use testClusterHealth in the AlertNotification
How to test:
> Use cluster health in alert notification

- kubernetes-headlamp-ingress-sample.yaml
* Adapt apiVersion to latest supported version for kubernetes
* Add missing properties
* Use new service declaration
closes #1237
> ingress-examle/headlamp: Fix ingress example file

- charts/headlamp/Chart.yaml
- charts/headlamp/README.md
- Fix 404 home page link, add new source link (This link https://github.com/headlamp-k8s/headlamp/tree/main/deploy/helm is a 404)
- Fix maintainers URL from kinvolk to MAINTAINERS.md
- Add screenshots, category, and license for artifacthub (See https://artifacthub.io/docs/topics/annotations/helm/)
- Add some keywords
See artifact page here: https://artifacthub.io/packages/helm/headlamp/headlamp
> charts: Fix 404 home page link, add new source link, fix maintainers URL, screenshots, keywords

- frontend/src/components/common/LogViewer.tsx
For issue #1061 
**Description:**
As part of the pod logs component improvement, a suggestion has been made to implement a "Clear Logs" button. This functionality will enable users to effortlessly clear the current log contents displayed in the text view, enhancing the troubleshooting experience by allowing focused analysis of specific service calls while maintaining continuous access to the log output.
**In progress:**
**Implementing Ongoing Log Printing:** I am currently working on implementing the necessary logic to ensure that the pod logs continue to be printed to the component even after the logs have been cleared. This will enable users to view the ongoing log output without interruption.
**Work Implemented:**
> frontend ClearPodLogs: Creates button to clear pod logs

- frontend/src/components/App/TopBar.tsx
> frontend: TopBar: Fix icon centering in mobile

- frontend/src/components/Sidebar/SidebarItem.tsx
When tabbing with the keyboard through the links, it was not
obvious with color which link was focused in light mode theme.
Fixes https://github.com/headlamp-k8s/headlamp/issues/1234
> frontend: SidebarItem: Fix focus background color

- frontend/src/components/App/TopBar.tsx
So that people can interact with the new popup. 
To test this, touch the notification icon from the mobile menu. Note how you can not scroll the list of notifications? With this fix people can scroll the list of notifications when it pops up.
> frontend: TopBar: Fix mobile menu to close when popup opens

- frontend/src/components/common/NamespacesAutocomplete.tsx
The AutoComplete component resets the typed (input) value when the
multiple selection is enabled, under certain conditions, so this patch
fixes that by controlling that input's value ourselves.
fixes #1228
> frontend NamespaceAutocomplete: Fix disappearing typed value

- frontend/src/components/App/Settings/Settings.tsx
- frontend/src/components/App/Settings/SettingsButton.tsx
- frontend/src/components/App/Settings/SettingsCluster.tsx
- frontend/src/components/App/Settings/__snapshots__/Settings.stories.storyshot
- frontend/src/components/App/TopBar.tsx
- frontend/src/components/App/__snapshots__/TopBar.stories.storyshot
Fixes for issue #1189 
Currently working on completing the solution based on the pillars of the issue.
Changes made:
- **Top Bar Settings Button Navigation:** The Top bar settings button now navigates to the Cluster Settings page of the current cluster. This simplifies the navigation process and brings a more intuitive user experience. Note that the settings button will not be visible when no cluster is set, preventing any confusion or error when there's no active cluster.
- **User Menu "General Settings" Navigation:** I have replaced the "Cluster Settings" button under the User Menu with a "General Settings" button. This button leads to the User Settings page, making it straightforward for users to modify their general settings.
- **Added "General Settings" Link to Cluster Settings:** To …
> frontend: Settings button fixes

- frontend/src/lib/themes.ts
This is in order for the currently selected entry to be more actively distinguishable.
Old/current:
New:
> frontend Sidebar: Add a different color to selected sub-entries

- charts/headlamp/templates/deployment.yaml
Previously when user changed baseURL for the application it was not reflecting with liveness and readiness probes. Due to which the application was crashing.
Fixes: #1266
> charts: Fix liveness and readiness probes

- frontend/src/components/common/LabelListItem.tsx
- frontend/src/lib/k8s/ingress.ts
This PR resolves an issue that was causing the Ingress tab to fail to load, resulting in a blank screen for users. The problem stemmed from a bug in the rendering logic for the Ingress resources.
> frontend: Fixes ingress render

- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/cluster/__snapshots__/Overview.stories.storyshot
- frontend/src/components/common/ObjectEventList.tsx
- frontend/src/components/common/ShowHideLabel/ShowHideLabel.stories.tsx
- frontend/src/components/common/ShowHideLabel/ShowHideLabel.tsx
- frontend/src/components/common/ShowHideLabel/__snapshots__/ShowHideLabel.stories.storyshot
- frontend/src/components/common/ShowHideLabel/index.tsx
- frontend/src/components/common/SimpleTable.stories.tsx
- frontend/src/components/common/SimpleTable.tsx
- frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
- frontend/src/components/common/index.test.ts
- frontend/src/components/common/index.ts
- frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/lease/__snapshots__/Details.stories.storyshot
- frontend/src/components/limitRange/__snapshots__/Details.stories.storyshot
- frontend/src/components/namespace/__snapshots__/NamespaceDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
These changes fix a few issues in the simple table:
Here's the table before the fix (ignore the blueboxes):
And here it is after the fix:
And they add an expand button to the events' message.
Storybook stories are added.
> Add collapse to events table + fix simple table

- app/windows/chocolatey/headlamp.nuspec
- app/windows/chocolatey/tools/chocolateyinstall.ps1
Already tested locally and submitted to chocolatey's registry.
> app: Bump Chocolatey Headlamp version to 0.19.0

- frontend/src/components/statefulset/List.tsx
As the latter may be 0 when there are readyReplicas, as a user reported.
fixes #1308
> frontend statefulset/List: Use replicas instead of currentReplicas

- frontend/src/components/App/Settings/SettingsCluster.tsx
for issue #1294 
This PR addresses an issue where clicking on the 'General Settings' link in app mode led users to a blank page. The underlying problem was identified in the routing mechanism that didn't correctly handle this specific navigation in app mode.
After implementing the fix the 'General Settings' link now reliably redirects users to the correct page without any issues.
It seems that the material ui Link component was the cause of the page directing to a blank view, seems to only have been an issue in app mode.
Please review and I welcome any feedback!
> frontend: Fixes settings link in app mode

- frontend/src/components/Sidebar/HeadlampButton.tsx
- frontend/src/components/common/SimpleTable.tsx
For issue #1233
This PR aims to improve the touch interface of our application, focusing specifically on button sizes and spacing, as per the touch interface guidelines. The changes target both general links/buttons and the sidebar navigation, enhancing usability on touch devices. Improving the touch interface should significantly enhance user experience on mobile devices by reducing misclicks and easing navigation.
1. Increase the size of buttons/links to a minimum of 44px to ensure a comfortable touch area on mobile devices.
2. Add ample space between buttons to avoid accidental touches. 
3. Apply the same design principles to the sidebar navigation, increasing touch areas and ensuring accurate navigation.
Working on a fix for the topbar new size taking up space for main content
Example …
> frontend: Fixes mobile spacing

- frontend/src/components/common/Label.tsx
In some pages the `mdi:calendar` icon is displayed with a wrong color in both dark and light themes.
**Before:**
**After:**
> Normalize the color of the calendar icon

- frontend/src/components/ingress/Details.stories.tsx
- frontend/src/components/ingress/Details.tsx
- frontend/src/components/ingress/List.stories.tsx
- frontend/src/components/ingress/List.tsx
- frontend/src/components/ingress/__snapshots__/Details.stories.storyshot
- frontend/src/components/ingress/__snapshots__/List.stories.storyshot
- frontend/src/components/ingress/storyHelper.ts
- frontend/src/lib/k8s/ingress.ts
A backend for an Ingress resource may represent a service with a port number, a port name, or it can be a resource reference.
This patch fixes displaying an Ingress for different types of backend and adds also stories to it.
fixes #1323
> frontend ingress: Fix showing ingresses with different kinds of backend

- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.stories.storyshot
- frontend/src/lib/util.ts
The Resource Quotas page previously displayed '0 cores' for the request field due to a hardcoded value. This update replaces the static string with dynamic values based on the actual quantity, ensuring accurate representation.
---
> frontend resourceQuota: Fix cores pluralization

- frontend/src/components/common/Label.tsx
When navigating to a timestamp using the date and calendar option, there has been an alignment issue noticed. This fix ensures that the date and calendar display are properly aligned to enhance user readability and aesthetics.
**Before**
**After**
> frontend: Fix alignment for calendar Icon

- app/scripts/build-backend.js
- frontend/package.json
Introduce a formatting problem in app/scripts/*.js
```bash
cd frontend
npm run format
```
Now the app/scripts JavaScript should be formatted too.
> app/scripts: Fix so app/scripts folder is formatted too

- app/README.md
- app/package.json
- app/scripts/start.js
- app: Fix for windows when using unsupported export
- app: Make `npm start` start the app
- app: Fix scripts so they are listed in alphabetical order
- app: Add a README.md with a Quickstart
- app: Add start script which handles ctrl+c quiting better (So that headlamp-server, frontend and app are quit when ctrl+c is done in the controlling terminal where `npm start` is run.)
Related:
- fixes #1372 
- fixes #1370
- fixes #1376
> app: Fix running on windows, improve quickstart docs, document scripts, better ctrl+c handling

- frontend/src/components/ingress/Details.tsx
- frontend/src/components/ingress/LinkStringFormat.stories.tsx
- frontend/src/components/ingress/__snapshots__/Details.stories.storyshot
- frontend/src/components/ingress/__snapshots__/LinkStringFormat.stories.storyshot
- frontend/src/lib/k8s/ingress.ts
Related to issue #1268 
This PR addresses the enhancement requested in issue #1268 . The purpose was to transform the host in the ingress rules into a clickable link, thereby eliminating the need for users to manually copy and paste the URL to open the endpoint.
- To validate this change, I created example pod, service, and host with the host set to bing. The changes work for formatted URL stings only, but will print '*' if needed and will not print any links if no host is written.
- When using tls and host is within fields, protocol is set to https, if not using tls or if it is not found, defaults to http
Using tls
Not using tls
> frontend: Create nav link for ingress

- frontend/src/components/App/Notifications/List.tsx
The mark-as-seen and the clear buttons were still enabled when there were no notifications. This patch fixes that and also optimizes how the check for the status is being computed.
How to test:
(make sure you copy the notifications from the browser's local storage so you can repeat the case where you have unseen and visible notifications)
> frontend Notifications/List: Correct status for context buttons

- Makefile
- backend/cmd/headlamp.go
- frontend/package.json
- frontend/src/helpers/index.ts
We use the make file to run Headlamp in dev mode, and since the backend token was not set up in that case, it was impossible to use this mode for testing any backend features, i.e. running npm run dev-only-app would not work for testing adding clusters, use Helm, etc.
> Use a phony backend token when run from Makefile

- frontend/src/components/common/Label.tsx
The HoverInfoLabel was changed to have its contents aligned to the
end (right, in LTR languages) as the date label used should be aligned
as such and uses this component internally. However, many other values
are represented with this label, so we cannot always align it.
This patch fixes that by making this component have an inline-flex
display, allowing for the labels+icons to be vertically aligned to the
center (reason for which it had a display:flex rule) while respecting
the text-align rule set on a wrapping element. i.e. the date labels get
aligned to the right in most tables as their cell has that text-align
rule, but other uses of the mentioned component don't get affected.
**Before the fix:**
**After the fix:**
> frontend common/Label: Do not end-align HoverInfoLabel

- Makefile
- backend/README.md
- docs/development/backend.md
- backend: Fix `make backend-lint` so it works with modern golang
- backend: Add a README.md with a quickstart and links to docs
- Makefile: Add backend-format for formatting backend go code
- docs/development/backend: Document lint, format, and test
- fixes #1371
> backend: Fix backend-lint, add backend-format, document backend make targets

- frontend/src/components/App/Home/index.stories.tsx
- frontend/src/components/App/Home/index.tsx
- frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigDetails.stories.storyshot
- frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigDetails.stories.storyshot
Plugins should be able to change the columns of the clusters' table
in the home view. So this change allows them to.
fixes #1397
> frontend: Allow plugins to modify home table's columns

- frontend/src/components/Sidebar/__snapshots__/Sidebar.stories.storyshot
- frontend/src/components/Sidebar/prepareRoutes.ts
- frontend/src/components/common/SectionHeader.tsx
- frontend/src/components/crd/CustomResourceDetails.tsx
- frontend/src/components/crd/CustomResourceList.stories.tsx
- frontend/src/components/crd/CustomResourceList.tsx
- frontend/src/components/crd/Details.tsx
- frontend/src/components/crd/List.tsx
- frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
- frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/runtimeClass/__snapshots__/Details.stories.storyshot
- frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigDetails.stories.storyshot
- frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigDetails.stories.storyshot
- frontend/src/lib/k8s/crd.ts
- frontend/src/lib/router.tsx
fixes #1393
We now have:
* Name CRDs in the sidebar is now Custom Resources
* The list view associated with the sidebar entry has now a link to Resources and Definitions:
* Clicking on a Resource in the view above, will show the list view for those resources (if the CR spec has additional columns, these are shown too)
* Clicking on an object in the Resource list view will show that object's details view
* This details view now has a Definition value, allowing to see the CRD association
* In the CRD details view (which existed before), now we have a new Resource value, allowing to access the Resource list view
> Improve Custom Resources UX

- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/crd.ts
- frontend/src/plugin/index.ts
When applying a resource, we tried to get a match for a known/default resource (CronJob, Pod, etc.) but this may result in trying to apply a resource using the wrong API when we have a CustomResource that has a name matching any exiting default resource's. This patch always tries to get the API details from the server for the API version of the data we need to apply, thus ensuring we always get the right API.
How to test:
`*`:
```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
name: my-new-cron-object
spec:
cronSpec: "* * * * */5"
image: my-awesome-cron-image
replicas: 5
```
> Fix standard name CRDs

- frontend/src/components/common/Resource/Resource.tsx
- frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/ingress/__snapshots__/Details.stories.storyshot
- frontend/src/components/lease/__snapshots__/Details.stories.storyshot
- frontend/src/components/limitRange/__snapshots__/Details.stories.storyshot
- frontend/src/components/namespace/__snapshots__/NamespaceDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/components/runtimeClass/__snapshots__/Details.stories.storyshot
- frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigDetails.stories.storyshot
- frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigDetails.stories.storyshot
Fixes issue #1317 
This addition ensures that there is a sufficient space below the last item, creating a more aesthetically pleasing view and avoiding the impression that content is abruptly cut off.
---
> frontend: Fix lack of space at page bottom

- frontend/src/lib/k8s/apiProxy.ts
We started using the "apis" prefix when applying resources but need also to distinguish when "api" is needed.
How to test:
> frontend: Fix regression when applying resources

- frontend/src/lib/k8s/index.ts
fixes #1398 
The double requests were triggered by how `useCluster` was being initialized to `null` when it didn't need to.
@callmevladik, maybe you can test it?
> Fix resource double requests

- frontend/src/lib/themes.ts
Fixes [#1390](https://github.com/headlamp-k8s/headlamp/issues/1390)
This PR addresses the motion issue which causes discomfort or system slow down for some users. It ensures that Headlamp respects the OS/browser level preference for motion while also providing a manual override setting. 
Additionally, the PR explores the implementation of reduced motion preference in a Material-UI application, as per the guidelines and discussions in Material-UI's repository.
This implementation references the discussions in Material-UI's repository on supporting `prefers-reduced-motion` ([#16367](https://github.com/mui-org/material-ui/issues/16367)) and follows one of the suggested implementations for a Material-UI application ([comment](https://github.com/mui-org/material-ui/issues/16367#issuecomment-517 …
> frontend: adds reduced motion compatibility

- frontend/src/components/storage/ClaimList.stories.tsx
- frontend/src/components/storage/ClaimList.tsx
- frontend/src/components/storage/__snapshots__/ClaimList.stories.storyshot
- frontend/src/lib/k8s/persistentVolumeClaim.ts
fixes #1431 
How to test:
(or check the storybook for it)
> fix pvc without storage class

- app/windows/winget/templates/Headlamp.Headlamp.installer.yaml
- app/windows/winget/templates/Headlamp.Headlamp.locale.en-US.yaml
- app/windows/winget/templates/Headlamp.Headlamp.yaml
- app/windows/winget/winget-create.js
- package-lock.json
- package.json
For issue #1265 
This PR addresses the request to support `winget`, the built-in package manager for Windows, especially since it's natively available in Windows 11. The goal is to streamline the installation experience for Windows users of the Headlamp desktop app.
1. **Winget Manifest**: Introduced a new `winget` manifest folder tailored for the Headlamp desktop app. This manifest will allow users to install Headlamp via the `winget install headlamp` command.
2. Followed the official `winget` documentation to ensure the manifest adheres to recommended guidelines and best practices.
3. Updated installation documentation (if applicable) to include instructions for the `winget` installation method.
> app: Creates winget manifest

- frontend/src/components/App/Home/RecentClusters.stories.tsx
- frontend/src/components/cluster/ClusterChooserPopup.stories.tsx
- frontend/src/helpers/index.ts
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
Improve some of the docs and types in lib/k8s. For https://github.com/headlamp-k8s/headlamp/issues/1295
- frontend: cluster: Add docs and some missing fields
- frontend: cluster: Add auth_type to Cluster interface
- frontend: helpers: Add docs for getRecentClusters, getVersion, getProductName
- frontend: helpers: Add docs for setRecentCluster
- frontend: apiProxy: Improve docs for drainNodeStatus
- frontend: apiProxy: Improve docs for drainNode
- frontend: apiProxy: Add docs for listPortForward
- frontend: apiProxy: Add docs for stopOrDeletePortForward
- frontend: apiProxy: Add docs for startPortForward
- frontend: apiProxy: Add docs for metrics
- frontend: apiProxy: Add docs for apply
- frontend: apiProxy: Add docs for combinePath
- frontend: apiProxy: Add docs for connectStream
- …
> frontend: k8s: Adding docs, improving types

- frontend/src/components/storage/ClaimList.stories.tsx
- frontend/src/components/storage/ClaimList.tsx
- frontend/src/components/storage/__snapshots__/ClaimList.stories.storyshot
- frontend/src/lib/k8s/persistentVolumeClaim.ts
If it's not a valid string, then we shouldn't try to get a link for it.
This is an attempt to fix #1444 .
> frontend: Check whether the volumeName is valid when listing PVCs

- frontend/.eslintignore
If you've been building the app, then the generated .js files are included in the `npm run lint`. With this file the generated js files are ignored, so the lint works.
- make the app js
- cd frontend && npm run lint
- there should be no false warnings/errors from the app generated js
> frontend: app: Fix lint to ignore generated app js

- plugins/examples/change-logo/package-lock.json
- plugins/examples/change-logo/package.json
- plugins/examples/change-logo/src/ReactiveLogo.stories.tsx
- plugins/examples/change-logo/src/__snapshots__/ReactiveLogo.stories.storyshot
- plugins/examples/change-logo/src/index.tsx
- plugins/examples/change-logo/src/storybook.test.tsx
- plugins/examples/tables/package-lock.json
- plugins/examples/tables/package.json
- plugins/examples/tables/src/ContextMenu.stories.tsx
- plugins/examples/tables/src/__snapshots__/ContextMenu.stories.storyshot
- plugins/examples/tables/src/index.tsx
- plugins/examples/tables/src/storybook.test.tsx
- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/config/storyshots/storyshots-test.ts
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
Whilst writing some plugin tests also fixed some headlamp-plugin issues running tests.
- headlamp-plugin: Fix for test runner to add polyfill TextEncoder
- headlamp-plugin: Add some more transform ignores for the test runner
- headlamp-plugin: storyshots workaround bugfix updated due to a dependency update
- headlamp-plugin: Add UNDER_TEST environment variable when testing
- plugins/examples/change-logo: Add ReactiveLogo.stories
- plugins/examples/tables: Add ContextMenu.stories
Run the tests, and see the stories in the storybooks.
The tests should pass, and you should see the stories.
```bash
cd plugins/examples/tables
npm i
npm run test
npm run storybook
cd plugins/examples/change-logo
npm i
npm run test
npm run storybook
```
> Fixes for headlamp-plugin tests and story tests for change-logo and tables examples

- backend/cmd/headlamp.go
- docker-extension/docker-compose.yml
- frontend/src/components/common/Resource/PortForward.tsx
- frontend/src/lib/k8s/apiProxy.ts
In docker desktop since the backend is running
inside a container portforwards running in the
container are not accessible from the host machine
to fix this a range of ports from 30000 to
32000 is exposed and a value in this range is used
when starting a portforward.
> docker-ext: Fix portforward issue

- frontend/src/components/workload/Charts.tsx
- frontend/src/components/workload/Overview.tsx
This PR fixes #1483 (check it out for testing instructions) and simplifies the logic for the workloads state as well.
It also adds a spinner to the tiled charts.
fixes #1489
> Show spinner when workloads are loading

- frontend/src/components/service/Details.tsx
Fixes issue #1500
The observed styling issue in the Endpoints section of the Service View has been resolved. The table now renders correctly across all viewing sizes, displaying the relevant information without any blank boxes or misalignment, enhancing the user's ability to view and interact with endpoint information.
- Navigated to the Service View, selected a service to view its details, and confirmed that the table under the Endpoints section now renders correctly without any blank boxes or misalignment.
- Tested the rendering on multiple viewing sizes to confirm the fix is effective.
> frontend: Fix endpoint address field CSS

- frontend/src/components/common/LogViewer.tsx
Fixes issue #1482 
In order to differentiate downloaded log files from one another, this update appends a timestamp suffix to the filename, reflecting the exact moment the file is downloaded. This enhancement ensures clearer organization and retrieval of log files, particularly when multiple downloads occur.
> frontend: Adds time to log download file name

- frontend/src/components/service/Details.tsx
- frontend/src/lib/k8s/endpoints.ts
Fixes issue #1515 
This PR addresses the rendering issue of the address field within the Endpoints section of the Service Detail View. The corrections ensure that the address field now displays the appropriate information without any truncation or misalignment, enhancing the user's interaction with endpoint address information.
- Navigated to the Service Detail View, scrolled down to the Endpoints section, and confirmed that the address field now renders correctly.
- Tested the rendering on multiple viewing sizes and different browsers to confirm the fix is effective.
A special thank you to @Src0p for their invaluable contributions to this PR. Their insights and suggestions significantly enhanced the quality of the changes, and their willingness to share expertise has greatly benefited …
> frontend: Fixes endpoint address renders

- frontend/src/lib/k8s/apiProxy.ts
Fixed a small typo in the code where 'handel' should be 'handle'.
> lib/k8s/apiProxy.ts: Correct typo 'handel' to 'handle'

- frontend/src/components/cronjob/Details.tsx
Otherwise they are just loose jobs and don't appear in the CronJob's
table.
fixes #1399
> frontend CronJob: Add owner ref when manually spawning jobs

- frontend/src/components/common/Terminal.tsx
- frontend/src/components/pod/Details.tsx
- frontend/src/i18n/locales/de/glossary.json
- frontend/src/i18n/locales/en/glossary.json
- frontend/src/i18n/locales/es/glossary.json
- frontend/src/i18n/locales/fr/glossary.json
- frontend/src/i18n/locales/pt/glossary.json
- frontend/src/lib/k8s/pod.ts
Fixes issue #1450
This PR enhances the Pod Details View by allowing logs and exec commands to be selected by container type. Users can now choose between standard containers, init containers, and ephemeral containers (if present) for more granular access to logs and exec functionality.
- Manual testing was conducted to ensure that logs and exec commands can be selected and are functioning for each container type within the Pod Details View.
> frontend: Add init and ephemeral containers logs

- frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
- frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
- frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
- frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
- frontend/src/lib/k8s/apiProxy.ts
- frontend/src/lib/k8s/cluster.ts
The right group and version were not being used when checking for a
resources' authorization which resulted in wrong authorization
assessments.
fixes #1490
> frontend: Use the right group and version in KubeObject.getAuthorization

- frontend/src/components/crd/__snapshots__/CustomResourceList.stories.storyshot
This PR adds the missing snapshot for Storybook of the Custom Resource List component. Having this snapshot in place will help in ensuring visual consistency and aiding in the identification of visual regressions in future changes.
> frontend: Add custom resource list snapshot

- backend/cmd/headlamp.go
- backend/pkg/portforward/handler.go
- backend/pkg/portforward/handler_test.go
- backend/pkg/portforward/internal_test.go
- backend/pkg/portforward/store.go
this patch refactors the Portforward
feature and moves it to a separate package.
this refactor uses the cache to store the
state of portforwards and adds tests.
> backend: Refactor and Add tests to Portforward

- .github/workflows/backend-test.yml
this patch selectively skips commenting the code
coverage change for PRs raised from forks to avoid 
the authorization error that arises when commenting.
> github: Fix PR comment issue for forks in backend test

- app/package-lock.json
- app/package.json
Electron v22 is EOL on Oct 10.
Quite a few releases have zoomed by... here are the release notes.
- https://www.electronjs.org/blog/electron-27-0
- https://www.electronjs.org/blog/electron-26-0
- https://www.electronjs.org/blog/electron-25-0
- https://www.electronjs.org/blog/electron-24-0
- https://www.electronjs.org/blog/electron-23-0
Some clicking about (smoke testing) with:
> app: Update Electron v27 from v22

- e2e-tests/tests/headlamp.spec.ts
- e2e-tests/tests/helpers.spec.ts
Streamline setup for e2e tests. We do not need to authenticate repetedly now. Added helpers for it
> Add e2e tests

- .github/workflows/app-artifacts-mac.yml
- app/mac/scripts/notarize.js
- app/mac/scripts/setup-certificate.sh
This commit allows the mentioned workflow to sign the builds if the user chooses to.
> github: Add a signing option to the app-artifacts-mac workflow

- Dockerfile
- Makefile
- docs/development/_index.md
Support for apt-get using Debian-like systems.
- Fixes https://github.com/headlamp-k8s/headlamp/issues/1072
- Adds a section in the documentation about how to specify different base images.
1) Try a base image with a Debian base image.
```bash
IMAGE_BASE=debian:latest make image
```
2) See that the default used is alpine.
```bash
make image
```
> Makefile: Dockerfile: Add support for custom IMAGE_BASE and Debian

- frontend/src/components/crd/CustomResourceDetails.tsx
- frontend/src/components/crd/CustomResourceList.tsx
- frontend/src/lib/k8s/crd.ts
This PR simplifies the use of CR classes by adding a new method for generating them out of CRD objects, and also fixes the permissions issues reported in #1552.
fixes #1552 
@Denis220795 , thanks again for reporting another important issue with a great insight that made this fix easier to do.
Can you try this branch and check if the issue if fixed for you?
> Improve CR permissions and class generation

- Dockerfile.plugins
When building docker image for plugins we were using npm latest version of @kinvolk/headlamp-plugin which was resulting in unsynced behaviour if any plugin changes were made. To solve this we are now building example plugins with the latest changes of headlamp-plugin.
Fixes: #1567
> ci: Fix plugins installation

- frontend/src/components/App/Notifications/notificationsSlice.test.ts
- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/cluster/__snapshots__/Overview.stories.storyshot
- frontend/src/components/common/Chart.stories/__snapshots__/PercentageCircle.stories.storyshot
- frontend/src/components/common/TileChart/__snapshots__/TileChart.stories.storyshot
- frontend/src/components/workload/Overview.tsx
- frontend/src/lib/k8s/cluster.ts
Headlamp has a convention where lists of items are set as null which means we are still fetching the objects, and a spinner should be shown instead of an empty or filled list.
However, if we seamlessly replace the cluster for which the list of items are being shown, then the list will hold the old items until new ones are prepared. So there's no perception for the user that there's a loading state.
This PR fixes this for the cluster and workloads overview. The first is fixed by resetting the items list in the useList hook, and using this hook in the cluster overview (instead of useApiList). The workloads overview is a bit more elaborate and replacing useApiList with useList is more complicated, so in this case we reset the object holding the workloads when the cluster changes (directly in …
> Show spinners when cluster changes

- frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.tsx
Fixes issue #1584 
This PR addresses the issue where the release notes were dimmed across the entire screen in Headlamp's app mode. The root cause was identified as a deprecated attribute "BackdropComponent", which has now been removed to resolve the dimming problem.
- Verified that the release notes are no longer dimmed on the entire screen in app mode.
- Conducted tests in different app modes to ensure the removal of the attribute does not affect other functionalities.
> Fix Dimming Issue in Release Notes on Headlamp App Mode

- backend/cmd/headlamp.go
- backend/cmd/headlamp_test.go
- backend/pkg/kubeconfig/kubeconfig_test.go
- backend/pkg/portforward/handler_test.go
- frontend/src/components/App/Settings/SettingsCluster.tsx
- frontend/src/lib/k8s/apiProxy.ts
User are sometimes interested in using the namespace that's set up in their kubeconfig, associated with the context/cluster they're using in Headlamp.
These changes accomplish that.
How to test:
> Use kubeconfig namespace

- docs/development/api/modules/plugin_registry.md
- docs/development/plugins/how-to.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/__snapshots__/ActionsNotifier.stories.storyshot
- frontend/src/plugin/index.ts
- plugins/headlamp-plugin/config/.storybook/preview.tsx
- plugins/headlamp-plugin/config/storyshots/storyshots-test.ts
- plugins/headlamp-plugin/config/webpack.config.js
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
- plugins/headlamp-plugin/template/src/headlamp-plugin.d.ts
- plugins/headlamp-plugin/template/src/index.tsx
I'm finishing off upgrading the plugins/ (app-catalog, and prometheus) and came across some issues.
- plugins: frontend: docs: Update mentions of `@material-ui` to `@mui`
- frontend: Update notistack@2.0.8 which uses mui 5
- frontend: headlamp-plugin: Add direct react-router dependency
- headlamp-plugin: Add image types into config file
- headlamp-plugin: Add ResizeObserver polyfill for tests
See
- app-catalog plugin upgrade PR: https://github.com/headlamp-k8s/plugins/pull/26
- prometheus plugin upgrade PR: https://github.com/headlamp-k8s/plugins/pull/27
> frontend: plugins: mui fixes

- Dockerfile
- Makefile
- container/build-manifest.json
- container/fetch-plugins.sh
We want to ship plugins with the official container image as well, but these will be only plugins that are safe in a non-desktop environment, so for now this means the prometheus plugin.
1. Build and run the image from this branch, make sure you can access a cluster, then go to a workload, like a deployment: verify that the prometheus charts are enabled in a workload's details view
> Ship official plugins in image

- app/windows/chocolatey/headlamp.nuspec
- app/windows/chocolatey/tools/chocolateyinstall.ps1
Just for an extra check. I have tested locally and verified it installs the published 0.22.0 version. The new version is already sent to the Chocolatey registry.
> chocolatey: Update Headlamp to 0.22.0

- index.yaml
By mistake, in version 0.21.0 (Helm version 0.17.0) we pushed the Helm config as having an appVersion of v0.21.0 but this config requires the tag version without the `v`. Since then, ArtifactHub has been giving us alerts that it cannot find the mentioned image.
Since we readily pushed a Helm 0.17.1 version with the right config, I think we should rather just remove the 0.17.0 from the registry to avoid anyone picking it up + fixing the warnings.
Once we merge this, we should remove the Helm 0.17.0 tag/release from the repo.
> Remove broken format version from the helm repository

- frontend/src/components/pod/Details.tsx
- frontend/src/lib/k8s/pod.ts
User can now download all logs, there is an option in the dropdown menu of pod's log page.
Fixes: #1481
> frontend: Add option to download all logs

- frontend/src/components/App/icons.ts
- frontend/src/components/common/Dialog.tsx
The logic around setting the icon for the fullscreen toggle in the
mentioned component was done by appending the icon name to the "mdi:"
prefix depending on the state. Therefore, this prevented the icon test
from scanning this file correctly, since it looks for a string that
started by "mdi:".
As a cause for this, the fullscreen-exit icon was not added to the
icon list for offline use, which this patch also adds.
fixes #1644
> frontend: Fix fullscreen icon bypassing tests and add missing icon

- frontend/src/components/common/LogViewer.tsx
- frontend/src/components/pod/Details.tsx
- frontend/src/lib/k8s/pod.ts
Adds a new enhancement where pods logs are not auto reconnected. This used to happen when pod's container was in retry state, which made logs to reconnect and it kept on flashing as if the page reloaded until the pod was in a Ready state.
This adds functionality if the pod is not Ready, it shows a button to reconnect the logs.
Fixes: #1480
Run the following commands in your terminal, assuming you have a cluster up and running.
```bash
kubectl run nginx --image nginx
kubectl exec -it nginx -- bash
kill 1
```
You will see the Reconnect button as show below.
> frontend: Disable auto reconnection of logs

- app/electron/main.ts
- app/electron/preload.ts
- frontend/src/components/App/runCommand.ts
- frontend/src/plugin/registry.tsx
- plugins/examples/app-menus/README.md
- plugins/examples/app-menus/src/index.tsx
So that some local shell commands can be run from inside a plugin.
This communicates the process interaction with the Electron app render process via ipc.
The interface exposed is a subset of the node spawn() which is what is used on the app side. It only implements the parts which are already used by the plugin we have in mind.
The interface supports streaming stdout and stderr, and getting exit codes.
Note, this supports running multiple commands at the same time. The complexities of this are hidden to the user of runCommand.
It limits the commands that can be run to only minikube and az so far. If there is a need for more this can be extended later. This is intended as a way to limit potential misuse.
The app-menu example plugin has been extended to add a minikube menu which displays …
> app: frontend: plugins: Add runCommand for shell commands in Electron app

- frontend/src/components/App/Layout.tsx
This endpoint is used only for parsing stateless clusters kubeconfig. So, it should only be called when dynamic clusters are enabled. When the flag was disabled, the endpoint was unavailable. This fix calling the endpoint unnecessarily when dynamic cluster is disabled.
Signed-off-by: Kautilya Tripathi <ktripathi@microsoft.com>
> frontend: fix calling /parseKubeConfig

- frontend/src/components/App/Notifications/index.tsx
- frontend/src/components/App/Notifications/notificationsSlice.ts
* Get 200 notifications stored in the local storage. Then go to a cluster with warnings and check the dev console logs to see if there are any indication/warnings about infinite loops.
* Verify that the latest cluster warning events are shown in the notifications
* Verify that marking notifications as read and deleting them does work
fixes #1664
> Fix notifications infinite loop

- frontend/src/components/common/Resource/ResourceTable.stories.tsx
- frontend/src/components/common/Resource/ResourceTable.tsx
- frontend/src/components/common/Resource/__snapshots__/ResourceListView.stories.storyshot
- frontend/src/components/common/Resource/__snapshots__/ResourceTable.stories.storyshot
- frontend/src/components/namespace/__snapshots__/NamespaceDetails.stories.storyshot
- frontend/src/components/node/__snapshots__/List.stories.storyshot
- frontend/src/components/pod/__snapshots__/PodList.stories.storyshot
- frontend/src/components/replicaset/__snapshots__/List.stories.storyshot
The ResourceTable by default sorts data by the age column. However,
since the columns can now be hidden, the way to compute the index of
the age column needed to be updated to take hidden columns into
account.
> frontend: Fix default sorting column for the ResourceTable

- docs/development/plugins/building.md
- docs/installation/in-cluster/_index.md
- docs: in-cluster: Add link to helm quickstart
- docs: building: Add a link to container plugins blog post
> Small documentation improvements, helm link, and blog link

- .github/workflows/build-container.yml
- Dockerfile
At some point the .plugin package copying stopped working. 
It's documented that a .plugins folder will be copied and used by the container.
There's a test included proving that the files are copied properly now.
Fixes #1687
> github: Dockerfile: Fix .plugins copying and usage with test

- docs/installation/in-cluster/_index.md
* Links now point to github
fixes #1708
> fix: local links in helm docs

- .github/workflows/build-container.yml
- Dockerfile.plugins
- plugins/examples/dynamic-clusters/package-lock.json
- plugins/examples/dynamic-clusters/package.json
- plugins/examples/headlamp-events/package-lock.json
- plugins/examples/headlamp-events/package.json
- plugins/headlamp-plugin/bin/headlamp-plugin.js
- plugins/headlamp-plugin/install-dependencies.sh
We were copying plugins but we were not installing dependecies which resulted some example plugins to not get copied.
headlamp-events plugin was also using local dev dependency which resulted in failure of installing it. This fixes it.
Fixes: #1695
> plugins: Fix copying to docker containers

- frontend/src/components/common/Resource/CreateButton.tsx
- frontend/src/lib/k8s/cluster.ts
This issue fixes https://github.com/headlamp-k8s/headlamp/issues/1660 by making the cluster name as part of each resource instance and using it for the operations (+ something similar for the resource creation).
fixes #1660
How to test:
> Fix item crud when changing clusters

- frontend/src/components/node/Details.tsx
- frontend/src/i18n/locales/de/glossary.json
- frontend/src/i18n/locales/en/glossary.json
- frontend/src/i18n/locales/es/glossary.json
- frontend/src/i18n/locales/fr/glossary.json
- frontend/src/i18n/locales/pt/glossary.json
Fixes issue #1316 
This PR introduces a confirmation dialog box in the Node UI for Drain actions, aimed at enhancing user experience by providing a clear, interactive confirmation step before these critical actions are executed. However, there's a known bug where the dialog box re-renders every couple of seconds if left open for an extended period. This issue has been traced back to the `apiProxy.ts` file, specifically lines 415 and 376.
- The confirmation dialog box for node actions re-renders every few seconds if it remains open. This behavior has been traced to the `apiProxy.ts` file, lines 415 and 376. May need to be solved in a different PR.
- Investigate and resolve the re-rendering issue in the `apiProxy.ts` file to ensure the dialog box remains stable and does not refresh …
> frontend: Add dialog for Drain

- frontend/src/components/App/Notifications/List.tsx
- frontend/src/components/App/Notifications/__snapshots__/List.stories.storyshot
Solves issue #1667
This PR focuses on improving the user experience of the Notifications List View. It involves utilizing the available horizontal space more effectively to display a larger portion of the notification message. Additionally, the cluster name in each notification will now be a clickable link, redirecting users directly to the associated cluster.
> frontend: Fix notifications format styles

- frontend/src/components/App/__snapshots__/TopBar.stories.storyshot
- frontend/src/components/cluster/ClusterChooser.tsx
After 2bc3979e7c41f264226bfb44e01e03f679b3a370 , the cluster chooser button's color became blue as apparently the sx prop isn't picking up custom theme entries. This patch fixes that by accessing the theme directly in the sx prop.
cc/ @farodin91 This may be important if you add more style replacements (the sx prop doesn't seem to find custom props by string directly, so they need to be referred by theme).
> frontend ClusterChooser: Fix color (make it black again)

- backend/cmd/headlamp.go
- backend/cmd/server.go
- backend/cmd/stateless.go
- backend/pkg/config/config.go
- backend/pkg/helm/handler.go
- backend/pkg/helm/release.go
- backend/pkg/helm/repository.go
- backend/pkg/kubeconfig/kubeconfig.go
- backend/pkg/kubeconfig/kubeconfig_test.go
- backend/pkg/kubeconfig/watcher.go
- backend/pkg/logger/logger.go
- backend/pkg/logger/logger_test.go
- backend/pkg/plugins/plugins.go
- backend/pkg/portforward/handler.go
- backend/pkg/portforward/store.go
Earlier we were not using zlog everywhere due to which some logs were not correctly parsed by log platforms. They were all parsed as errors. This fixes that and adds correct format of all logs in headlamp. They are now shown as json which can be parsed by any log platform.
This also adds a wrapper function for zlog which increases code readability and cleanliness.
Fixes: #1645
> backend: format backend logs to use zlog

- frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
this patch adds redirect to plugin settings list
view when the user clicks Save/Cancel. When save
is clicked the data is saved and redirected to
the plugin settings list view.
> frontend: Fix redirect on Save/Cancel in Plugin Settings Details View

- frontend/src/components/App/Home/__snapshots__/index.stories.storyshot
- frontend/src/components/App/Home/index.tsx
- frontend/src/i18n/locales/de/translation.json
- frontend/src/i18n/locales/en/translation.json
- frontend/src/i18n/locales/es/translation.json
- frontend/src/i18n/locales/fr/translation.json
- frontend/src/i18n/locales/pt/translation.json
- frontend/src/lib/k8s/cluster.ts
Allow useGet, useList, and apiGet/apiList functions to specify the cluster.
This is needed and it's possible now that we have a way to specify the cluster in apiProxy.
As part of testing whether this was working, I ended up adding the number of warnings for the clusters in the home view. Which is part of the new design when we implement the new multi-cluster view.
fixes #1747
> Cluster in hook api functions / Warnings in home view

- frontend/src/components/App/Home/index.tsx
- frontend/src/components/App/Notifications/index.tsx
- frontend/src/lib/k8s/event.ts
This PR aims to fix a long running issue: the notifications only report for clusters currently being checked + they don't work outside of a cluster (e. g. in the home view).
There are a few issues I am fixing still (introduced by this PR):
> Fix notifications out of cluster

- plugins/examples/change-logo/src/index.tsx
Since now we are using sx everywhere.
Fixes #1764
> plugins/examples/change-logo: Use sx prop in logo

- frontend/src/plugin/index.ts
The enable button was not being shown for plugins unless there was at
least one incompatible plugin being processed. This happened because
the code that set the isCompatible part of each plugin info was not
being directly set unless there were incompatible plugins.
> frontend plugins: Fix enable button disappearing

- e2e-tests/tests/headlampPage.ts
Sometimes the token would not be in the URL in time, and it would fail the tests. So we wait for the heading to be there.
> e2e-tests headlampPage: Fix flaky test to wait for page to load

- .github/workflows/build-container.yml
So that e2e tests can be run faster if only the e2e test changes.
Especially useful if there is a test that's flaky on CI, because timing is different there. Then you can try different test changes more quickly, because the container image does not need to be built each time.
- Here's an action run that caches the built headlamp container images: https://github.com/headlamp-k8s/headlamp/actions/runs/8262403292/job/22601643056?pr=1773
- Here's one that uses the restored container images and skips building the container image making the test run 8 minutes quicker: https://github.com/headlamp-k8s/headlamp/actions/runs/8262137512/job/22600860057?pr=1773
> github: build-container: Cache container build for faster testing

- plugins/headlamp-plugin/bin/headlamp-plugin.js
Due to a recent change, after webpack compiled or had an error
compiling a plugin's code, the process was being exited, meaning that
the functionality of watching for changes was broken.
fixes #1855 
1. Set up a version of headlamp-plugin with these changes (create a package using `npm pack`);
2. Go to an example plugin and install that package from the tarball (`npm i /path/to/your/kinvolk-headlamp-...tgz`);
3. Build the plugin for changes: `npm run start` -> Realize that the command does not quit after copying the files to the plugins folder, and instead it keeps watching for changes in the plugin files.
> headlamp-plugin: Do not exit process when watching for changes

- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/cluster/__snapshots__/Overview.stories.storyshot
By default we should show only warnings. This wrong default has been
around since we added the related switch.
> frontend cluster/Overview: Show only warnings by default

- frontend/src/components/App/TopBar.tsx
- frontend/src/components/App/__snapshots__/TopBar.stories.storyshot
There's a number of problems with Notifications. With some clusters the number of warnings makes it not useful. Because they keep showing new notifications over and over again.
The idea is to disable it for now, and revisit it again once we can prove that it is working well.
Related to this issue:
- https://github.com/headlamp-k8s/headlamp/issues/1807
- https://github.com/headlamp-k8s/headlamp/issues/1853
> frontend: Notifications: Disable Notifications

- backend/go.mod
- backend/go.sum
> backend: Upgrade github.com/docker/docker v24.0.7+incompatible to v24.0.9+incompatible

- e2e-tests/tests/headlamp.spec.ts
- e2e-tests/tests/headlampPage.ts
- e2e-tests/tests/securityPage.ts
So we can see it updates which page it is on.
> e2e-tests: headlamp.spec: Add test for pagination

- e2e-tests/package-lock.json
- e2e-tests/package.json
This PR updates the Playwright dependency to version 1.42 in our end-to-end (E2E) testing setup. The new release of Playwright introduces enhancements and bug fixes that improve the reliability and efficiency of our E2E tests.
> frontend playwright: Add update playright package

- backend/cmd/headlamp.go
- backend/pkg/plugins/plugins.go
- backend/pkg/plugins/plugins_test.go
this patch removes the base-url that was appended
to the /plugins response as the base path is
added automatically by the frontend
> backend: Fix plugin paths when base-url is set

- docker-extension/docker-compose.yml
- frontend/src/components/cluster/KubeConfigLoader.tsx
- frontend/src/lib/k8s/apiProxy.ts
The way we were adding clusters previously (before the stateless
clusters) meant we received the configuration when we added a
cluster. After stateless clusters, that same call to add a cluster
in the frontend doesn't return a response. This triggered an
exception which meant the UI assumed there was an issue with setting
up the cluster but that was false.
fixes #1831
> frontend: Fix success state when adding kubeconfig

- .github/workflows/backend-test.yml
When a fork like a dependabot makes a PR the coverage comment does not work.
Also we put in minimal permissions required for the action to work. Thus limiting the potential bad things that can be done in a PR.
---
See error in dependabot PR here: https://github.com/headlamp-k8s/headlamp/actions/runs/8273020677/job/22635968074#step:10:27
Information about github action permissions:
- https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> github: backend-test: Fix coverage comment and permissions

- .github/workflows/app-artifacts-mac.yml
- .github/workflows/app-artifacts-win.yml
Github issues every job a token, and a service principal in Azure can be configured to trust that token. This is called "federated credentials" or OpenID Connect. Switch to using the azure/login action and enable write access on the id-token for the jobs that need it.
> github: Switch azure login to OIDC connect

- Dockerfile
This was the error that was coming up:
```
ERROR: failed to solve: source can't be a git ref for COPY
```
It was causing the container image CI job to fail, and `make image` to fail.
Fixes #1903
> Dockerfile: Fix issue with copying git folder

- e2e-tests/.gitignore
- e2e-tests/package-lock.json
- e2e-tests/package.json
- e2e-tests/tests/podsPage.spec.ts
- e2e-tests/tests/podsPage.ts
fixes #1836
This PR introduces a new Playwright test that validates the functionality of live updates within the application. Specifically, it tests creating a pod and deleting it in the same browser tab, while confirming that these changes are reflected in real-time on new tab. This test ensures that live updates work seamlessly, providing users with accurate and up-to-date information without the need for manual refreshes.
> frontend: Add live update e2e test

- e2e-tests/tests/podsPage.spec.ts
- e2e-tests/tests/podsPage.ts
- frontend/package.json
The e2e-tests folder was not included in the "lint-staged" pre-commit hook for formatting or linting.
Make a change in the e2e-tests/tests/ folder which would trigger a lint issue (resort imports to something wrong) or a formatting issue (add some incorrect indentation). These should be fixed for you when you try committing the same as happens in frontend/ or app/.
> frontend: Fix lint-staged linting/formatting for e2e-tests

- frontend/package-lock.json
- frontend/package.json
- plugins/headlamp-plugin/package-lock.json
- plugins/headlamp-plugin/package.json
This gets rid of the yellow warning message that is shown when running `npm start` in the frontend.
Run `npm start` and there should be no warning text block about a babel package.
> frontend: Fix warning shown in npm start

- docs/development/plugins/building.md
The original intent of that link was to point to the "run the code" section of the development page, but index.md wasn't resolving and currently it shows 404. Also extra # is unnecessary. Verified the fix locally
> docs: Fix the link in building plugin page

- frontend/src/components/cluster/Overview.stories.tsx
- frontend/src/components/cluster/Overview.tsx
- frontend/src/components/cluster/__snapshots__/Overview.stories.storyshot
- frontend/src/components/common/ObjectEventList.tsx
- frontend/src/components/pod/PodDetails.stories.tsx
- frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
- frontend/src/lib/k8s/event.ts
- frontend/src/test/index.tsx
fixes #1787 
This PR takes into consideration the kube Event's eventTime and series before checking the lastTimestamp/firstTimestamp, as some kubernetes flavors apparently don't use the latter.
@lijianzhi01 , can you test if this fixes your issues?
> Fix event time displaying in certain k8s flavors

- .github/workflows/app-artifacts-linux.yml
- .github/workflows/app-artifacts-mac.yml
- .github/workflows/app-artifacts-win.yml
- .github/workflows/app.yml
- .github/workflows/backend-test.yml
- .github/workflows/backend.yml
- .github/workflows/build-container.yml
- .github/workflows/container-publish.yml
- .github/workflows/docker-extension-release.yml
- .github/workflows/draft-release.yml
- .github/workflows/frontend.yml
- .github/workflows/helm-chart-lint-test.yml
- .github/workflows/helm-chart-release.yml
- .github/workflows/pr-to-update-chart.yml
- .github/workflows/pr-to-update-homebrew.yml
- .github/workflows/pr-to-update-minikube.yml
- .github/workflows/trigger-flatpak-update.yml
See 
- https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
Note: `contents: read` at the top turns off all other permissions. It's best practice to do that and specify in each job any extra permissions they have. This is so that it's easier to tell which permission is for which job, and also so that the other permissions are turned off or not.
> github: Fix permissions so they are minimal

- e2e-tests/tests/namespacesPage.ts
For issue #1914 
fixed:
create a namespace with the minimal editor then delete it
> Frontend: fix e2e errors

- app/electron/main.ts
This fix prevents external URLs from being opened within the Headlamp app.
Fixes: #1917
> app: Fix external url opening in app

- .github/workflows/pr-to-update-winget.yml
That ref was for testing only and was left there by mistake.
> github: Remove ref when cloning Headlamp repo for winget automation

- charts/headlamp/README.md
- charts/headlamp/templates/ingress.yaml
- charts/headlamp/values.yaml
This PR updates the existing ingress chart template and adds the field "ingress.ingressClassName". 
According to the kubernetes documentation, setting the ingressClassName in the annotations is deprecated: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
This fixes issue #1895 
Added one line to the ingress chart template to template the field `Values.ingress.ingressClassName` if it exists
I tested the change locally by defining a simple my-values.yaml file:
```
ingress:
enabled: true
ingressClassName: nginx
hosts:
- host: chart-example.local
tls:
- secretName: chart-example-tls
hosts:
- chart-example.local
```
Using `helm template` I confirmed that a correct Ingress was templated:
```
helm template headlamp --namespace headlamp --create-namespace -f …
```
> charts: add ingressClassName to ingress template

- README.md
- docs/_index.md
- docs/faq.md
Relates to issue #1473 
This PR introduces a Frequently Asked Questions (FAQ) section to the Headlamp documentation, aimed at addressing common questions and providing users with a quick reference guide. The FAQ is easily accessible via new links added to the README and the webpage's footer.
> frontend docs: Add FAQ for headlamp docs

- charts/headlamp/README.md
- charts/headlamp/templates/deployment.yaml
- charts/headlamp/tests/expected_templates/extra-args.yaml
- charts/headlamp/tests/test_cases/extra-args.yaml
- charts/headlamp/values.yaml
User were unable to pass any additional arguments to the headlamp deployment, this adds enhancement for that.
Fixes: #1898
> charts: Option to pass additional arg to container

- backend/pkg/config/config.go
This fix prevents the development app (when running `npm run dev-only-app`) from watching the .plugins directory locally, which causes an endless loop of refreshes to the app. To do this, we ensure that .plugins is not set as the plugins dir by default.
Fixes: #1937
> backend: config: Change default plugins dir
