kubernetes-sigs/headlamp

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json

This PR fixes the items mentioned for the container display in details view as described in #1971.
How to test. Use the storybook to see how this PR shows the exit code + dates for the places showing containers.
Also fixes how the "terminated" display is shown.

add container exit code in details view

---

e2e-tests/README.md

This PR updates the existing documentation to include more detailed instructions on setting up and running local Playwright end-to-end tests. The enhancements aim to provide developers with clear guidelines on how to effectively utilize Playwright for testing their local developments, ensuring that they can quickly and efficiently verify changes before deployment.

frontend: edit docs for playwright

---

e2e-tests/README.md

Building on the recent updates to our documentation for local Playwright end-to-end tests, this PR further extends the documentation to include comprehensive instructions for setting up and running Playwright tests in a virtual machine (VM) environment. This addition aims to provide developers with detailed guidance on how to deploy and utilize Playwright for testing in more complex, VM-based setups, ensuring robustness and adaptability of testing practices across different environments.

docs: Adds docs for vm playwright env

---

frontend/package-lock.json
frontend/package.json

So people will get a hint when they install that they have older versions of node/npm than is required.
- Use node 18.
- Run `cd frontend && npm install`
- See warning message in screenshot about node version being wrong.

frontend: Add node/npm version requirements to package.json

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go

The header was not getting set correctly and returning an empty string
Fixes: #1968

backend: Fix empty X-Forwared-Host header

---

frontend/src/lib/k8s/apiProxy.ts

`errCb` parameter is the 3rd argument of `get` function returned by `singleApiFactory`, whereas it's only the 2nd argument of `list`. This causes `repeatStreamFunc` to misbehave for `list` calls because the error callback index is hard-coded to `2`.
In my case I couldn't list custom resources with deprecated API versions.

frontend: fix `repeatStreamFunc` for `list` requests

---

charts/headlamp/README.md
charts/headlamp/templates/deployment.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/tests/test_cases/extra-args.yaml
charts/headlamp/tests/test_cases/oidc-create-secret.yaml
charts/headlamp/tests/test_cases/oidc-directly-env.yaml
charts/headlamp/tests/test_cases/oidc-directly.yaml
charts/headlamp/tests/test_cases/oidc-external-secret.yaml
charts/headlamp/tests/test_cases/volumes-added.yaml
charts/headlamp/values.yaml

Now users have 3 different way they can set oidc configuration
- Directly set values of respective config.oidc.clientID and others which inject them into ENV variable, to be used by args.
- Use external i.e. already created secret with the same keys as args.
- Use config.oidc.secret.create functionality to create secret and have them dynamically loaded into the headlamp deployment.
Fixes: #1897
This is when user just want to use ENV variables directly. 
- Set values of `config.oidc.`  `clientID, clientSecret, issuerURL, scopes` in `values.yaml` and set `config.oidc.secret` as `false`
- Run `helm template charts/headlamp`
This is when user wants to use external secret created by them
- Create a new secret with above config.oidc values. For reference check `template/secret.yaml`. Then …

charts: Provide 3 options for oidc configuration

---

frontend/src/lib/k8s/cluster.ts

This isNamespaced will not work in the case of CRDs for example.
How to test:

Do not use isNamespaced for adding namespace to API calls

---

app/electron/main.ts
app/package.json

Currently in the app on windows when application triggers page reload it opens a browser.
The reason is difference in forward and back slashes in the url. 
in main.ts startUrl has forward slashes
but when page reloads, it requests a link with backward slashes. 
Since windows handles forward slashes just fine, I added a replacement that changes to forward slashes.
Fixes https://github.com/headlamp-k8s/headlamp/issues/1990

app: Fix electron opening browser on page reload

---

frontend/src/components/namespace/__snapshots__/NamespaceDetails.stories.storyshot
frontend/src/components/pod/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
frontend/src/components/pod/__snapshots__/PodList.stories.storyshot
frontend/src/components/pod/storyHelper.ts
frontend/src/lib/k8s/pod.ts

Just noticed that after the table changes we have pod IPs as being `undefined` (when there's no IP defined) in the pod list.
How to test:

pod/List: Fix IPs being displayed as "undefined" when not set

---

frontend/src/components/service/List.tsx

This fixes #2027 where the service list page crashes when there is at least one service without port.

frontend: fix crash on service list page

---

charts/headlamp/templates/deployment.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml

There was a wrong k8s config written for envFrom for external secret.
Fixes: #2022

charts: fix oidc external secret loading

---

charts/headlamp/README.md
charts/headlamp/values.schema.json
charts/headlamp/values.yaml

Charts did not have defined structure for Headlamp value configurations. Now we have defined schema for the same which will run while linting, installing, upgrading or templating the helm charts.
Fixes: #1926

charts: Add schema for values.yaml

---

frontend/src/components/common/Resource/MainInfoSection/MainInfoSection.stories.tsx
frontend/src/components/common/Resource/MainInfoSection/__snapshots__/MainInfoSection.Normal.stories.storyshot
frontend/src/components/common/Resource/MainInfoSection/__snapshots__/MainInfoSection.NullBacklink.stories.storyshot

Following #2034 , I am adding this story for testing the null backlink.

frontend: Add story for MainInfoSection

---

frontend/src/components/common/Chart.tsx
frontend/src/components/workload/Overview.tsx

Fixes issue #1792
This PR enhances the user interface by making the names on the workload circular charts clickable. This allows users to easily navigate to the corresponding workload list page, providing a more intuitive and efficient way to access detailed workload information directly from the charts.

Make Workload Circular Chart Names Clickable

---

backend/cmd/headlamp.go

This change prevents the spam of OIDC config errors in the logs when running the latest version of Headlamp without OIDC. Instead of logging an error when we check for the OIDC config, we simply return since we know we are not using OIDC auth.
Fixes: #1933

backend: Prevent OIDC errors when not in use

---

frontend/src/components/App/TopBar.tsx
frontend/src/components/App/__snapshots__/TopBar.NoToken.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.ProcessorAction.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.Token.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
frontend/src/components/Sidebar/HeadlampButton.tsx
frontend/src/components/Sidebar/NavigationTabs.tsx
frontend/src/components/Sidebar/Sidebar.tsx

This is based on #1720 as that PR is inactive.
I have set @tazo90 as a co-author.
fixes #1719
How to test:

Fix sidebar and topbar on mobile

---

.github/workflows/scorecard-analysis.yml
README.md

- **github: scorecard-analysis: Add config for OpenSSF scorecard**
- **README: Add OpenSSF scorecard badge**
The OpenSSF scorecard badge is a requirement for projects moving into CNCF incubator stage.
Additionally it gives us more code scanning results in the security tab on github. Giving us a nice list of things to fix up.

Add OpenSSF scorecard

---

plugins/headlamp-plugin/bin/headlamp-plugin.js

This change makes the update check for headlamp-plugin asynchronous to avoid slowing down and blocking the user on start.
Fixes: #1899

headlamp-plugin: Make update check asynchronous

---

frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot

Right now if you search within a table and some row cell has "undefined" as a value it crashes the page. 
This change will handle null and undefined values and replace them with a string, which table expects

frontend: Fix table search when some values are undefined

---

frontend/src/components/service/List.tsx
frontend/src/lib/k8s/service.ts

Simple PR just changing the type of spec.ports in KubeService.

frontend k8s/service: Make spec.ports optional to reflect the K8s API 

---

frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/components/common/Resource/Resource.tsx

If you to a config map view which shows data and your system text size setting is increased above 130% the monaco editor collapses, This PR allows it to resize itself on text size change

frontend: Allow editor to auto-resize in case of text size change

---

Makefile
app/electron/main.ts
app/electron/preload.ts
frontend/src/components/App/pluginManager.ts
frontend/src/plugin/registry.tsx
plugins/headlamp-plugin/README.md
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/headlamp-plugin-management.test.js
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json
plugins/headlamp-plugin/plugin-management-utils.js
plugins/headlamp-plugin/plugin-management-utils.test.js

A new `plugin-management.js` file has been introduced, responsible for handling plugin installation, listing, upgrades, and deletions. Additionally, the `runCommand` function has been enhanced to support electron-node command, enabling seamless execution of Node commands within the Electron environment.

Plugin Store prerequisites

---

frontend/vite.config.ts

Before the names were cut off. Also node_modules were included.
For https://github.com/headlamp-k8s/headlamp/issues/2125
(As a bonus it goes from 45s to 33s on my work-laptop-slower-than-my-phone.)
- See coverage report in CI (names are readable) See the CI run in this PR: https://github.com/headlamp-k8s/headlamp/actions/runs/9764162592/job/26951811504?pr=2127#step:5:3775
- Locally run `CI=true make frontend-test` (names are readable, and node_modules not there)
- Locally run `make frontend-test` (names are readable, and node_modules not there)

frontend: vite.config: Fix coverage report names, and excludes

---

charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml

This fixes the broken CI.
(A more long term fix would be to make it so it ignores version numbers somehow. But this is a quick fix to fix CI).
- locally `make helm-template-test`
- Also... the chart test CI Check passes ("Template test Helm charts / lint-test")

charts: Fix expected templates for new headlamp version

---

.github/workflows/backend-test.yml

Prior to this PR, tests running from branches (not PRs) would fail in the backend coverage scripts.
- **github: backend-test: Skip coverage steps unless PR**
- **github: backend-test: Add tracing to steps for easy debugging**
I created a testing-rc- branch which triggers the CI on branch pushes. You can see the testing-rc-... branch CI run passes now: https://github.com/headlamp-k8s/headlamp/actions/runs/9760869672 Whereas before this would fail.
---
NOTE: the charts CI failure is unrelated. There's a PR to fix it here: https://github.com/headlamp-k8s/headlamp/pull/2122

github: backend-test: Skip coverage except for PRs

---

frontend/package-lock.json
frontend/package.json
frontend/vite.config.ts
plugins/headlamp-plugin/dependencies-sync.js

For coverage task in #2125
Copied coverage collection includes/excludes from previous jest setup so it's more comparable and switched to istanbul coverage provider.

frontend: Improve test coverage collection

---

app/electron/main.ts
frontend/src/components/App/pluginManager.ts
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/plugin-management-utils.js

This patch adds few extra changes that are required for the plugin catalog plugin.
1. Add extra meta to installed plugins
2. Add user confirmation dialog to plugin Install
3. Add pluginName arg to pluginManager install function.

Plugin catalog extras

---

frontend/src/lib/k8s/apiProxy.ts

Linked to PR: https://github.com/headlamp-k8s/headlamp/pull/1727
This PR enhances the `singleApiFactory` function in `apiProxy.ts` to improve its flexibility. The `post` function within `singleApiFactory` has been updated to accept parameters of different types: JSON, `object`, or `KubeObjectInterface`. This change ensures that the function can handle various data formats more efficiently, making it more versatile and robust.

frontend: Adds JSON / object / KubeObjectInterface options

---

.github/workflows/frontend.yml
Makefile
frontend/src/i18n/index.test.ts

Fixes tests so they are not run twice #2125
Running it inside the tests makes the translation files be written
when the tests run, causing the tests to run twice.
Running it as a pre-commit hook is a bit slow (3.0s), because
it looks at all the files that have changed, and then writes all
the translation files again.
So instead we run it in CI so it catches the issues.

Makefile: github/workflows/frontend: Add i18n-check to CI

---

.github/workflows/build-container.yml
e2e-tests/kubernetes-headlamp-ci.yaml

This change replaces the use of minikube in the `Build Container and test / build discover and deploy` workflow with the use of kind. We estimate 60% decrease in run time on a cold run for the "Start Cluster" step of 1 minute (from ~1m50s to ~45s). Even with a cached image for the minikube run, we estimate a 25% decrease in run time (from ~1m to ~45s). This should speed up CI workflows for future changes.
Fixes: #1746

github: Replace minikube with kind in CI

---

frontend/src/plugin/index.ts

To maintain compatibility with plugins that are using webpack, some modules that have default exports need to have a special __esModule property so that plugins can grab the default export

frontend: Mark some modules in pluginLib as esModule

---

app/electron/main.ts
frontend/src/components/App/Layout.tsx
frontend/src/components/common/ErrorPage/ErrorPage.tsx

Fix error boundary Page link

---

app/.gitignore
app/electron/env-paths.ts
app/electron/plugin-management.ts
app/package.json
app/tsconfig.json

Now it gives ~/.config/Headlamp/plugins
Now it uses the same envPaths version so the plugin paths should be consistent.

app: Fix defaultPluginsDir on unix

---

app/electron/main.ts

There was a serialization error sending the data webContents.
This error was in the console.
- "Navigation" menu still works
- app-menus example plugin still works

app: Fix serialization error in app

---

frontend/src/plugin/index.ts

When plugins try to use `@mui/x-tree-view/TreeView` it fails because importing `@mui/material/styles` fails. 
Webpack version (0.24.1) also fails 
This fixes that
With this fix plugins can use Tree component like so 
```
import { TreeItem } from '@mui/x-tree-view/TreeItem';
import { TreeView } from '@mui/x-tree-view/TreeView';
```

frontend: Include styles in MuiMaterial in pluginLib

---

.github/workflows/build-container.yml

Wait a bit longer for headlamp service, because before often it would fail.
- some failing builds: https://github.com/headlamp-k8s/headlamp/actions/runs/10041408876/job/27749428400 https://github.com/headlamp-k8s/headlamp/actions/runs/10041295773/job/27749068280
- passes now: https://github.com/headlamp-k8s/headlamp/actions/runs/10041825495/job/27750786807 , https://github.com/headlamp-k8s/headlamp/actions/runs/10042072148/job/27751631559?pr=2186 , https://github.com/headlamp-k8s/headlamp/actions/runs/10042072148/job/27751631559

github: build-container: Fix container build

---

.github/workflows/build-container.yml

Before cached images meant that the e2e tests would fail.
Additionally, before changing go dependencies meant that the
image would not rebuild. Now if backend dependencies change
a new image is built and tested.
In this job you'll see that it uses a cached image, and the job fails. https://github.com/headlamp-k8s/headlamp/actions/runs/10042659886/job/27753598525
It seems to be because when things are cached we were skipping loading the images into kind. So we change it to always load the images into kind... no matter if the image is built or restored from cache.
---
There's a test of the caching behavior in the PR here: https://github.com/headlamp-k8s/headlamp/pull/2189
The job that successfully builds even though it is using caching is here: …

github: build-container: Fix cached image loading

---

frontend/src/redux/clusterActionSlice.ts

This change ensures that invalid resource operations (e.g. changing a resource kind) do not trigger a success notification. Previously, the app would indicate a successful attempt to apply changes even when it is unsuccessful. Now when trying to perform an invalid apply/edit operation, instead the editor will reappear with the error message and a failure notification.
Fixes: #2123

frontend: Prevent success pop-up on invalid operations

---

plugins/examples/pod-counter/src/index.tsx

Was causing a crash when actions is not there.
- Load pod-counter
- don't see a pod-counter related issue in the web dev console

plugins/examples/pod-counter: Fix notifications issue

---

frontend/src/lib/k8s/apiProxy.test.ts
frontend/src/lib/k8s/apiProxy.ts

This fix allows `testAuth` to take in a namespace parameter if given and fall back to using the default namespace if not given. Added changes to the `testAuth` tests in `apiProxy.test.ts` to account for this.
related: #754

frontend: apiProxy: Pass in namespace to testAuth

---

plugins/headlamp-plugin/README.md
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/template/package.json
plugins/headlamp-plugin/test-headlamp-plugin.js

This command creates a tarball in the format that headlamp-plugin expects to be in when we use the install command.

headlamp-plugin: Add package command

---

frontend/src/components/common/Resource/EditButton.tsx
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/crd.ts

A first draft to resolve #2032. I believe there might be a better way to do this.
I've removed the Status and ManagedFields fields from the code when making the editor dialog.
Fixes: #2032
Signed-off-by: guilhane <guilhane.bourgoin@orange.com>

Remove unnecessary fields from the editor

---

.github/workflows/helm-chart-release.yml
charts/headlamp/Chart.yaml

This add steps to releasing of Helm charts where it uses the gpg keys to sign and release the charts.
Fixes: #1989

charts: Add signing of Helm charts

---

app/windows/winget/templates/Headlamp.Headlamp.installer.yaml
app/windows/winget/templates/Headlamp.Headlamp.locale.en-US.yaml
app/windows/winget/templates/Headlamp.Headlamp.yaml

Fixes #2191 
This PR updates the Winget schema used in Headlamp from version 1.5.0 to 1.6.0. Additionally, the `DisplayVersion` field, which has been removed by Winget contributors, is removed to align with the latest schema requirements and maintain compatibility.

winget: Updates  manifest schema

---

app/scripts/after-pack.js

Otherwise, Mac will fail to notarize the app.

app: Replace symlinks in node_modules by their target in Mac builds

---

backend/cmd/headlamp.go

Refactor token handling function for clarity and maintainability
- Split complex logic in `isTokenAboutToExpire` into helper functions:
- `decodePayload`: Decodes the base64 payload from the token.
- `getExpiryTime`: Extracts and converts the expiry time from the payload.
- Simplified `isTokenAboutToExpire` main function for readability.
Solve this issue: https://github.com/headlamp-k8s/headlamp/issues/1848

ref: isTokenAboutToExpire for clarity and maintainability

---

backend/cmd/headlamp.go

Currently that error is ignored

backend: Print error if server fails to start

---

charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/tests/test.sh

This updates script to test template charts, this ensures when there is new release, the expected templates are updated with the correct version before comparison, avoiding test failures due to version mismatch.
Fixes: #2240

charts: Fix script to tests charts template

---

docs/development/plugins/building.md
docs/development/plugins/functionality.md

fixed links breaking after changes to API docs. See Issue [2227](https://github.com/headlamp-k8s/headlamp/issues/2227).

docs: redirect broken links

---

docs/development/plugins/building.md

This is a broken reference in the docs.
(Can anyone let me know if this doc is outdated before I invest a bunch of time and find out it doesn't work?)
I won't hold this PR up by marking it as a draft, because the link is definitely broken, but if the doc is outdated and that's why the reference is bad, then maybe we shouldn't merge it. (I'll get around to building headlamp today with flux plugin that's in development, if the documents are good, but ...)

docs: fix bad link in plugin dev docs

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

By Oleksandr Dubenko
It is not usable with react 18, they are not going to update it.
Instead we will use playwright testing with axe later. See https://github.com/headlamp-k8s/headlamp/issues/2239 about that.

frontend: Remove axe a11y check

---

frontend/src/components/ingress/Details.stories.tsx
frontend/src/components/ingress/__snapshots__/Details.WithWildcardTLS.stories.storyshot
frontend/src/components/ingress/storyHelper.ts
frontend/src/lib/k8s/ingress.ts

This change addresses a regression where Headlamp would crash when encountering an ingress that does not specify HTTP paths. This is particularly relevant for ingresses that only specify TLS settings for wildcard subdomains.
Fixes: #2261 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: wildcard
spec:
rules:
- host: '*.one.domain.tld'
- host: '*.two.domain.tld'
tls:
- hosts:
- '*.one.domain.tld'
- '*.two.domain.tld'
secretName: wildcard-cert
```

frontend: ingress: Handle missing HTTP paths

---

app/electron/main.ts

Not sure why these were not caught by linter/typechecker. I will try to make lint/type checking work for app/ again in a separate PR.
Testing done:
- app starts and arguments still work (`--headless, --disable-gpu --kubeconfig`)
- type errors and typos are absent in vscode

app: Fix typos and typing issues

---

frontend/src/lib/k8s/apiProxy.ts

the token expiry check in refreshToken was failing when the decodeToken returned null.this patch adds a check to see if the decodedToken exists before accessing the .exp property
Fixes: https://github.com/headlamp-k8s/headlamp/issues/2268

frontend: Fix refreshToken

---

backend/pkg/kubeconfig/kubeconfig.go

this patch makes sure the context name is DNS
compatible.

backend: Make sure context name is DNS compatible

---

frontend/src/components/cluster/KubeConfigLoader.tsx

The button was supposed to be black but the text was also being set as black. Since primary buttons are now blue from the theme, we shouldn't hardcode their color like that when it comes to normal buttons. This patch removes that custom styling from that "next" button, making it use the default primary color.

frontend KubeConfigLoader: Do not override Next button's color

---

app/electron/plugin-management.ts
plugins/headlamp-plugin/plugin-management/plugin-management.js

Instead use copy+removal so it works across partitions.
fixes #2259

app: Do not use rename to move plugin folders

---

frontend/src/plugin/index.ts

Since @mui/styles is deprecated and @mui/material/styles doesn't work with React 18 we can provide `styled` from @mui/system as a replacement for makeStyles function
This fixes prometheus plugin
make app-linux
Open app
See that prometheus plugin now works

frontend: Provide fallback for makeStyles in pluginLib

---

.github/workflows/backend-test.yml

currently due to insufficient permission of write permission for gh cli,
it was unable to comment on the PR. This fixes that.

ci: fix commenting of test coverage

---

frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.tsx
frontend/src/components/common/ReleaseNotes/__snapshots__/ReleaseNotesModal.Show.stories.storyshot

Removes usage of github-markdown-css styles which caused rendering issues with dark theme
Replaces low-level Modal with recommended Dialog component
Fixes #2298
Demo: First old popup, then new one
https://github.com/user-attachments/assets/bfa61c10-eee7-4ca2-a0c6-50b1b790f17d

frontend: Improve ReleaseNotesModal rendering

---

frontend/package-lock.json
frontend/package.json

Due to bug in the NPM (https://github.com/npm/cli/issues/4828) it generates inconsistent package-lock and app may fail on other platforms
Needed for #2231

frontend: Fix missing optional dependencies

---

frontend/src/lib/k8s/cluster.ts
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

There was a request to use getAllowedNamespaces in plugins
- **frontend: k8s/cluster: Export getAllowedNamespaces**
- **headlamp-plugin: Bump version to 0.10.0-alpha.2**
Fixes #2301
1) Use Headlamp from this branch
2) Install the alpha release of  `npm i @kinvolk/headlamp-plugin@0.10.0-alpha.2` in a plugin
3) Add this into a plugin src/index.tsx and after install the plugin with `npm start`
```ts
import { getAllowedNamespaces } from '@kinvolk/headlamp-plugin/lib/k8s/cluster';
alert(getAllowedNamespaces())
```
4) In Headlamp go to a cluster page, and go to cluster settings and add an 'allowed namespace'
5) Reload cluster page and see alert with the allowed name spaces you just added.

Export lib/k8s/cluster/getAllowedNamespaces

---

frontend/src/components/account/__snapshots__/AuthToken.ShowActions.stories.storyshot
frontend/src/components/account/__snapshots__/AuthToken.ShowError.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.AnError.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.AuthTypeoidc.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.BasicAuthChooser.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.HaveClusters.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.Testing.stories.storyshot
frontend/src/components/cluster/Chooser.tsx

Currently the header blends in with the background and in dark mode makes Info button not visible
Current, Dark mode:
Current, Light Mode:
After the change, Dark mode:
After the change, Light mode:

frontend: Fix Chooser popup header visibility

---

frontend/src/i18n/index.test.ts

This PR resolves the issue where the duplicate keys test for translations fails on Windows environments due to path inconsistencies. Previously, the test passed without issues on Linux machines but failed on Windows due to differences in file path handling. The error has been fixed by using `path.basename`, ensuring that the test works correctly on both Linux and Windows environments.
Fixes issue #2316 
- Updated the duplicate keys test to use `path.basename` for handling file paths.
- Ensured cross-platform compatibility for both Linux and Windows by standardizing the way paths are processed in the test.
- The test now successfully passes on both operating systems without raising a `TypeError`.

frontend: Fix duplicate translation keys pathing for windows

---

backend/cmd/stateless.go
backend/pkg/kubeconfig/kubeconfig.go
backend/pkg/kubeconfig/kubeconfig_test.go
backend/pkg/kubeconfig/test_data/kubeconfig_autherr
backend/pkg/kubeconfig/test_data/kubeconfig_partialcontextvalid
backend/pkg/portforward/handler_test.go

If there is a problem with the kubeconfig in any of the context or cluster, headlamp won't be rendered useless. It would throw human readable message to the backend and show the list of working clusters.
- Fixes: #1628
- The original issue was here: https://github.com/headlamp-k8s/headlamp/issues/1349
- In your kubeconfig add some context with partial validity. For reference please check [here](https://github.com/headlamp-k8s/headlamp/blob/e13376a49d4191032926373e11d30a1a6c5ff4f7/backend/pkg/kubeconfig/test_data/kubeconfig_partialcontextvalid)
- Run backend `cd backend && go run ./cmd -dev`
- Run frontend `cd frontend && npm start`
- You should see errors in backend and only valid clusters in frontend.
- You can try with different kubeconfig and check.

backend: send working list of contexts

---

plugins/headlamp-plugin/dependencies-sync.js
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This change addresses the plugins test failure in the CI.
Fixes: #2324
Tested on issue #1996 in [this commit](https://github.com/headlamp-k8s/headlamp/commit/ddd6c4a3cc49b67878bdfe05af285a37c9c6eb06).

headlamp-plugin: Install tar and update dependencies-sync

---

.github/workflows/container-publish.yml

This change was necessary to fix the container image publishing job. The newer versions were needed so that current github workers can create container images.

github container-publish: Add qemu action + update docker action version

---

backend/pkg/portforward/handler.go

this patch uses the token in startPortForward only if the token from the API request is not empty.
fixes #1834 
before:
https://github.com/user-attachments/assets/e40a708b-7ccc-4fd9-bc4c-c92b470a0dcb
after:
https://github.com/user-attachments/assets/398c7aba-958f-4ef0-90cf-d6df83624a45

backend: Use token only if present in PortForward

---

.github/workflows/backend-test.yml
.gitignore
Makefile

This is useful to check the test coverage of backend code changes.
- Makefile: Add backend-coverage and backend-coverage-html
- .github/workflows/backend-test: Add coverage report to PR comment
- .github/workflows/backend-test: Add coverage html report as artifact and provide link to it
- `make backend-coverage` to see report in terminal.
- `make backend-coverage-html` to see report in browser.
- See bot comment: click toggle arrow to see text report
- See bot comment: Follow html link to download artifact locally to view html report (it is more advanced showing which lines/branches are not covered)
- After `make backend-coverage` doing a `git status` does not show `backend/coverage.out` file because it is .gitignore'd.

backend: Add test coverage reports into the PR coverage bot comment

---

frontend/src/components/namespace/CreateNamespaceButton.tsx
frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot

This PR refactors the labels and attributes associated with the **Create Namespace** functionality to enhance accessibility and testing efficiency.
1. **Removed Unneeded `aria-label`s**:
- Eliminated redundant `aria-label` attributes from the **Create** and **Cancel** buttons within the Create Namespace modal/dialog.
- These labels were unnecessary as the button text already conveys the action to screen readers.
2. **Updated `aria-label` for Create Namespace Action Button**:
- Changed the `aria-label` of the Create Namespace action button to provide a more descriptive and specific label.
3. **Added `data-testid` Attributes**:
- Introduced `data-testid` attributes to all buttons in the Create Namespace component.
- Facilitates more precise and maintainable selectors in automated testing …

frontend: Refactor labels for create namespace button

---

backend/cmd/cluster.go
backend/cmd/headlamp.go
backend/cmd/stateless.go
backend/pkg/kubeconfig/kubeconfig.go
backend/pkg/kubeconfig/kubeconfig_test.go
backend/pkg/kubeconfig/test_data/kubeconfig_partialcontextvalid
backend/pkg/portforward/handler_test.go

This removes the dependacy of manually parsing of k8s resources. It was a problem as we had to be in sync with k8s API changes, which is not a good way. This change removes that and it splits kubeconfig into seperate contexts and validates them.
- In your kubeconfig add some context with partial validity. For reference please check [here](https://github.com/headlamp-k8s/headlamp/blob/e13376a49d4191032926373e11d30a1a6c5ff4f7/backend/pkg/kubeconfig/test_data/kubeconfig_partialcontextvalid)
- Run backend `cd backend && go run ./cmd -dev`
- Run frontend `cd frontend && npm start`
- You should see errors in backend and all clusters in frontend.
- You can try with different kubeconfig and check.
https://github.com/headlamp-k8s/headlamp/pull/2289#issuecomment-2343545934

backend: refactor listing all contexts and error

---

frontend/src/components/common/AlertNotification.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json

This change addresses issues with accessibility and clarity for the `AlertNotification` component. This now uses the React Alert component from Material UI and displays a more descriptive error message: "Lost connection to the cluster".
Fixes: #2314

frontend: AlertNotification: Improve alert component

---

frontend/package-lock.json
frontend/package.json
frontend/vite.config.ts
frontend/vitest.config.ts

- Move vitest to a dev dependency, add vitest.config.ts. Moving the vitest config to a separate file from the vite.config.ts so that prod only builds can work without vitest being installed.
- Upgrade vitest to 2.1.1
- Upgrade vitest-websocket-mock to 0.4.0
- Upgrade @vitest/coverage-istanbul to 2.1.1
- [vitest releases](https://github.com/vitest-dev/vitest/releases)
- [vitest-websocket-mock releases](https://github.com/akiomik/vitest-websocket-mock/releases)
- [coverage-istanbul commits](https://github.com/vitest-dev/vitest/commits/main/packages/coverage-istanbul)

frontend: Update vitest and related, move vitest to devDependencies so it's not needed for prod only builds

---

frontend/src/components/cronjob/Details.tsx
plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/change-logo/package-lock.json
plugins/examples/change-logo/package.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/cluster-chooser/package.json
plugins/examples/details-view/package-lock.json
plugins/examples/details-view/package.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/dynamic-clusters/package.json
plugins/examples/headlamp-events/package-lock.json
plugins/examples/headlamp-events/package.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/pod-counter/package.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/examples/tables/package-lock.json
plugins/examples/tables/package.json
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/config/plugins-tsconfig.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json
plugins/headlamp-plugin/template/package.json

This fixes the `headlamp-plugin upgrade` command so it runs on the plugins/examples. It also upgrades the examples.
- frontend: cronjob/Details: Fix for type issue
- headlamp-plugin: Add overrides to template for typescript issue
- headlamp-plugin: Add @headlamp-k8s/eslint-config to plugin devDependencies
- headlamp-plugin: Fix bug where upgrade of mui 4to5 is always run
- headlamp-plugin: Fix plugins-tsconfig.json to look at `@types` folders first
- headlamp-plugin: Bump version to 0.10.0-alpha.6
- plugins/examples: Upgrade to headlamp-plugin 0.10.0-alpha.6
This is the upgrade command used to upgrade the examples.
`npx @kinvolk/headlamp-plugin@0.10.0-alpha.6 upgrade plugins/examples --headlamp-plugin-version=0.10.0-alpha.6`

plugins/examples: headlamp-plugin: Bump headlamp-plugin to 0.10.0-alpha.6, upgrade examples to that

---

frontend/package-lock.json
frontend/package.json

This was added in with a bad git auto-merge, which broke CI.
It was supposed to be removed in this PR that was already merged:
- https://github.com/headlamp-k8s/headlamp/pull/2364

frontend: Remove unused @types/redux-mock-store

---

frontend/src/components/authchooser/__snapshots__/AuthChooser.AnError.stories.storyshot
frontend/src/components/authchooser/index.tsx

This change addresses a regression from unifying the general and cluster settings. Now, when trying to access a missing cluster, clicking on the "Cluster Settings" link should open the cluster settings in the home context.
Fixes: #2404

frontend: AuthChooser: Fix broken cluster settings URL

---

frontend/src/components/common/EmptyContent.tsx
frontend/src/components/common/ReleaseNotes/UpdatePopup.tsx

- **frontend: EmptyContent: Remove defaultProps usage**
- **frontend: UpdatePopup: Remove usage of defaultProps**
Stops some warnings appearing in dev console/test runner.

frontend: Remove usage of defaultProps which is deprecated

---

backend/cmd/headlamp.go

For security reasons we don't allow serving paths with .. in them, so we were setting an error but not returning.

backend: Return after attempt to serve a path using ..

---

.github/workflows/build-container.yml
Dockerfile

Npm install uses package.json, and npm ci uses package-lock.json.
Fixes a security issue where packages were not pinned.

Dockerfile: Use npm ci so lockfile is used

---

.github/workflows/backend-test.yml

To fix a security warning with scorecard.

github: backend-test: Pin dependency to hash

---

app/electron/main.ts
backend/cmd/server.go
backend/pkg/plugins/plugins.go
backend/pkg/plugins/plugins_test.go

This change creates a CLI subcommand in the backend + desktop to list all plugins, with a distinction between static/shipped plugins and user-added ones.
Fixes: #2161

Add option to list plugins

---

frontend/src/lib/k8s/cluster.ts

This is so that when multi clusters are used we know which
cluster the error is for.
This is not used in single cluster mode and does not affect
it because it's an optional param.

frontend: k8s/cluster: Add cluster arg to onError callbacks

---

frontend/src/lib/util.ts

Gets the active group of clusters.
Tiny PR... This is not used in headlamp at the moment, but is a prerequisite for further multi cluster work.

frontend: lib/util: Add getClusterGroup

---

frontend/src/components/cluster/ClusterGroupErrorMessage.stories.tsx
frontend/src/components/cluster/ClusterGroupErrorMessage.tsx
frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithClusterErrors.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithDetailedClusterErrors.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithMessageUsed.stories.storyshot
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json

This is for displaying clusters with errors.
Look for ClusterGroupErrorMessage in the storybook.
`npm run storybook`

frontend: Add ClusterGroupErrorMessage for displaying clusters with errors

---

frontend/src/lib/util.test.ts
frontend/src/lib/util.ts

Sometimes we need to convert the objects per cluster into a flat list
of objects.
This is for multi cluster, it's not used yet.

frontend: util: Add flattenClusterListItems for cluster objects

---

frontend/src/lib/util.test.ts
frontend/src/lib/util.ts

For errors, we may need to combine several cluster->errors
objects into a single object.
This is in preparation for multi cluster.

frontend: util: Add combineClusterListErrors

---

.github/workflows/build-container.yml

ubuntu-latest now resolves to 24 
playwright install fails on 24
so in this PR pinning the version to 22

ci: Use Ubuntu 22 for build-container workflow

---

frontend/src/lib/k8s/cluster.ts

So the cluster name is passed around to api calls.
This is not used, and is just preparing for multi cluster.

frontend: cluster: Add cluster argument to KubeObject class

---

frontend/src/components/App/RouteSwitcher.tsx

Do not check if cluster needs a token when in multi-cluster mode.
Because we do not know which cluster needs a token or not.

frontend: RouteSwitcher: Fix multicluster mode, no token check

---

frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
frontend/src/components/common/Resource/EditorDialog.stories.tsx
frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/components/common/Resource/__snapshots__/EditorDialog.EditorDialogWithResource.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/EditorDialog.ExtraActions.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/ViewButton.View.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/ViewButton.ViewOpen.stories.storyshot

So users can add their own actions.
This will be used later by Resource/CreateButton to add a cluster selector to the EditorDialog.
Check the storybook Extra Actions state has the extra action, and the other states do not have any visible changes.
`npm run storybook`

frontend: EditorDialog: Add optional actions property

---

frontend/src/components/common/Resource/CreateButton.tsx

So users can select which cluster to apply the resource to.
Only shows the cluster selector if there is more than one
cluster being viewed.
For single cluster mode there is no change.
~~Note: depends on this being merged:~~
- ~~https://github.com/headlamp-k8s/headlamp/pull/2428~~

frontend: Resource/CreateButton: Add cluster selector

---

frontend/src/lib/k8s/cluster.ts

Because we are accessing it from the ResourceTable and we have that data but didn't have a way to get it.
See the ResourceTable changes at https://github.com/headlamp-k8s/headlamp/commit/1e78de8ca6df0f9d6fde03743712f4aa323a5cf1 .

frontend: Add cluster getter to KubeObject class

---

frontend/src/components/configmap/List.tsx
frontend/src/components/crd/List.tsx
frontend/src/components/cronjob/List.tsx
frontend/src/components/daemonset/List.tsx
frontend/src/components/deployments/List.tsx
frontend/src/components/endpoints/List.tsx
frontend/src/components/horizontalPodAutoscaler/List.tsx
frontend/src/components/ingress/List.tsx
frontend/src/components/job/List.tsx
frontend/src/components/lease/List.tsx
frontend/src/components/limitRange/List.tsx
frontend/src/components/namespace/List.tsx
frontend/src/components/networkpolicy/List.tsx
frontend/src/components/node/List.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/podDisruptionBudget/List.tsx
frontend/src/components/priorityClass/List.tsx
frontend/src/components/runtimeClass/List.tsx
frontend/src/components/secret/List.tsx
frontend/src/components/service/List.tsx
frontend/src/components/serviceaccount/List.tsx
frontend/src/components/statefulset/List.tsx
frontend/src/components/verticalPodAutoscaler/List.tsx

These are not shown for single clusters.

frontend: Add cluster column to List views

---

frontend/src/stateless/index.ts

There was no checking in the case where clusters is null.
This is the traceback in the dev console. You need to have no "stateless clusters" (which is the default).

frontend: stateless: Fix error when clusters is null

---

frontend/src/lib/k8s/api/v2/hooks.ts
frontend/src/lib/k8s/cluster.ts

Adds these keyed by cluster name to the return of useList():
- `clusterResults`, valued by result of useList on a single one.
- `clusterErrors`, valued by the error if any, otherwise null.
Adds the cluster field for the results from each cluster. So that the tables can display the cluster if needed.
The new useList is backwards compatible and works with one cluster too.
People can now also do this to get the results for cluster groups:
```ts
{ clusterErrors, clusterResults } = useList()
const error = clusterErrors[cluster]
clusterResults[cluster].items[0].cluster // this cluster field is now in each row
```
Another example of usage:
```ts
const { 
items, // in multiple clusters mode items has .cluster field.
error, // in single cluster mode this is a single error or null. In multi cluster …
```

frontend: cluster: hooks: Make useList multi cluster aware

---

frontend/src/components/common/Resource/ResourceTable.tsx

Errors for multiple clusters are displayed if there are any.
There are no changes for single cluster mode.
Depends on 
- https://github.com/headlamp-k8s/headlamp/pull/2448

frontend: ResourceTable: Add display of clusterErrors

---

frontend/src/components/common/Resource/RestartButton.tsx

This ensures that the event performed by the restart button is recognized by Headlamp as a restart rather than a delete.

frontend: RestartButton: Use proper event type

---

frontend/src/components/common/ActionsNotifier.tsx
frontend/src/redux/clusterActionSlice.ts

This change introduces a state to track cluster actions and improve notification handling. This prevents duplicate notifications when performing scale/restart events to deployments in quick succession.
Fixes: #2382

frontend: Add state for notification handling

---

frontend/vitest.config.ts

This change adds an html coverage report to vitest.config.ts.
Fixes: #2466 
```shell
cd frontend
npm test -- --coverage
cd coverage
python3 -m html.server # runs a local static webserver
```
The coverage report should be in `frontend/coverage/`. To open the report, run `cd frontend/coverage && python3 -m html.server`.
You can also do:
```shell
make test # runs --coverage by default
cd frontend/coverage
python3 -m html.server
```

frontend: vitest.config: Add html coverage report

---

backend/cmd/headlamp.go
backend/cmd/multiplexer.go
backend/cmd/multiplexer_test.go
backend/cmd/server.go

This adds websocket multiplexer to the backend. Frontend now need to make a single websocket call to the backend. Once that connection is established with the backend it will send message to the backend with appropriate data. Backend will open multiple websockets and act as a proxy to the frontend. It will make request to k8s server and return data to frontend.
This also adds retry logic if the connection is broken between frontend and backend.
Fixes: #1802
- Run backend `cd backend && go run ./cmd -dev -enable-dynamic-clusters`
- Run frontend `cd frontend && npm start` (we need this for userID of the session).
- Open postman application and use the API [here](https://www.postman.com/knrt1017/workspace/headlamp/ws-raw-request/6717608832943442e3cc99a7)
- It has message payload which you …

backend: Add websocket multiplexer

---

backend/cmd/headlamp.go
backend/pkg/plugins/plugins.go
backend/pkg/plugins/plugins_test.go

The backend was sending a refresh signal to the frontend very early due to reading the plugins folders, and this resulted in a refresh right after the UI was loaded (desktop only).
It is only interesting for the app to refresh after a plugin change if it already has the list of plugins, so these changes prevent that refresh until the app requests the plugins list.
fixes #2182

backend: Prevent sending refresh signal before the app is ready

---

.github/workflows/pr-to-update-winget.yml

This fixes a security issue where dependencies are not pinned.

github: pr-to-update-winget: Use npm ci to pin deps

---

frontend/src/lib/k8s/api/v2/hooks.ts

When I removed the ! at the end, the type checker complained and helped me find this bug.
If one cluster doesn't have results for something this could result in one null entering the items list.

frontend: k8s: hooks: Fix useKubeObjectList items could contain null

---

frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/role/List.tsx

In single cluster mode the RoleList is the same.
The ColumnType is exported needed here to keep the typechecker happy.

frontend: RoleList: Make multi cluster aware

---

frontend/src/lib/k8s/api/v2/hooks.ts

So we don't have a different key when a function uses the namespace as `undefined` and another as `''`.

frontend: Improve handling of an edgecase in useKubeObject useKubeObjectList hooks

---

frontend/src/components/App/RouteSwitcher.tsx

This allows routes to suspend and lazy load. This is useful for routes that have a lot of dependencies.
We need to test also the #2484 .

frontend: Add Suspense boundary for the route Switcher

---

plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/test-headlamp-plugin.js

All files made in the dist/ folder are copied in.
So plugins can add extra files if they need in the build step.
For example:
```
"scripts": {
"build": "headlamp-plugin build && npx shx cp main.wasm dist/main.wasm",
```
Needed for:
- https://github.com/headlamp-k8s/plugins/issues/13

headlamp-plugin: Fix extract/package to copy all in dist/

---

charts/headlamp/templates/extra-manifests.yaml
charts/headlamp/tests/expected_templates/extra-manifests.yaml
charts/headlamp/tests/test_cases/extra-manifests.yaml
charts/headlamp/values.schema.json
charts/headlamp/values.yaml

This change allows the Helm chart's user to include additional Kubernetes manifests to be deployed along with the chart. The incentive for this change was to allow overriding the default use of cluster-admin cluster role and also deploy a different cluster role and binding. 
This is achievable by including the additional manifests as an array of multiline strings in field `extraManifests`. For example:
```
extraManifests:
- |
apiVersion: v1
kind: ConfigMap
metadata:
name: dummy-configmap
data:
key1: value1
key2: value2
- |
apiVersion: v1
kind: ConfigMap
metadata:
name: configmap-with-templated-data
data:
injectedKey: {{ .Release.Name }}
```

chart: support deploying additional kubernetes manifests

---

frontend/src/components/configmap/Details.tsx
frontend/src/components/cronjob/Details.tsx
frontend/src/components/daemonset/Details.tsx
frontend/src/components/endpoints/Details.tsx
frontend/src/components/horizontalPodAutoscaler/Details.tsx
frontend/src/components/ingress/ClassDetails.tsx
frontend/src/components/ingress/Details.tsx
frontend/src/components/lease/Details.tsx
frontend/src/components/limitRange/Details.tsx
frontend/src/components/namespace/Details.tsx
frontend/src/components/networkpolicy/Details.tsx
frontend/src/components/node/Details.tsx
frontend/src/components/pod/Details.tsx
frontend/src/components/podDisruptionBudget/Details.tsx
frontend/src/components/priorityClass/Details.tsx
frontend/src/components/resourceQuota/Details.tsx
frontend/src/components/role/BindingDetails.tsx
frontend/src/components/role/Details.tsx
frontend/src/components/runtimeClass/Details.tsx
frontend/src/components/secret/Details.tsx
frontend/src/components/service/Details.tsx
frontend/src/components/serviceaccount/Details.tsx
frontend/src/components/statefulset/Details.tsx
frontend/src/components/storage/ClaimDetails.tsx
frontend/src/components/storage/ClassDetails.tsx
frontend/src/components/storage/VolumeDetails.tsx
frontend/src/components/verticalPodAutoscaler/Details.tsx
frontend/src/components/webhookconfiguration/MutatingWebhookConfigDetails.tsx
frontend/src/components/webhookconfiguration/ValidatingWebhookConfigDetails.tsx
frontend/src/components/workload/Details.tsx

Allows for rendering Details components without the router params. This is useful for the map view but also when we add the drawer opening of details as it's planned.

frontend: Add optional parameters to all Details components

---

frontend/src/helpers/testHelpers.ts
frontend/src/lib/k8s/KubeObject.ts
frontend/src/lib/k8s/api/v2/hooks.ts
frontend/src/lib/k8s/api/v2/makeUrl.test.ts
frontend/src/lib/k8s/api/v2/makeUrl.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.test.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
frontend/src/lib/k8s/api/v2/webSocket.ts
frontend/src/lib/k8s/event.ts

Create a kubeObjectListQuery, for a singular request 
useKubeObjectList can handle multiple clusters and namespaces by using multiple queries
_useKubeObjectList and _useKubeObjectLists are no longer neccessary since useKubeObjectList can handle 1 and more lists
Manual testing done:

frontend: Use multiple queries in useKubeObjectList and add support for allowedNamespaces

---

frontend/src/components/cluster/Overview.tsx
frontend/src/components/node/List.tsx
frontend/src/components/resourceQuota/List.tsx
frontend/src/components/webhookconfiguration/ValidatingWebhookConfigList.tsx

In multi cluster mode it adds a few cluster fields to some list views that didn't have it yet.
(in single cluster mode no cluster field is visible)

frontend: Fix missing cluster fields in list views for multi cluster

---

frontend/src/components/replicaset/List.tsx
frontend/src/components/workload/Overview.tsx

This is only visible if multiple clusters are being used.

frontend: Overview: Add cluster field for multi cluster

---

frontend/src/components/authchooser/index.tsx

AuthChooser would sometimes initially flash incorrect state requiring token before clusters config is loaded

frontend AuthChooser: Fix incorrect UI flashing

---

app/app-build-manifest.json
container/build-manifest.json

These plugins were updated:
- [app-catalog 0.3.1](https://github.com/headlamp-k8s/plugins/releases/tag/app-catalog-0.3.1)
- [prometheus 0.2.2](https://github.com/headlamp-k8s/plugins/releases/tag/prometheus-0.2.2)
- [plugin-catalog 0.1.1](https://github.com/headlamp-k8s/plugins/releases/tag/plugin-catalog-0.1.1)

app: container: Bump static plugin versions

---

docs/contributing.md

This PR introduces a new contributor guide to the docs directory. The guide provides essential steps for first-time contributors, covering how to submit Pull Requests (PRs) and report Issues effectively.
The goal of this document is to streamline the onboarding process for new contributors and ensure consistency in submissions.
For now, the guide is added to the docs folder, but we are considering alternative locations, such as:
Moving it to the Discussions tab for easy community access.
Integrating it into the README to provide visibility to all contributors.

docs: Add new contributors guide

---

frontend/src/components/App/Home/index.tsx
frontend/src/lib/k8s/event.ts
frontend/src/lib/k8s/index.ts

This PR fixes the useWarningsList and useClustersVersion so they do not update whenever there's new data from the server but instead when the data differs from what we returned the last time. (Same goal as #2514)
how to test

Fix home constant update

---

frontend/src/components/App/Home/index.tsx

This change adds a label for the actions menu for each cluster on the home page, where there previous was no label.
Fixes: #2526

frontend: Home: Add label for actions menu

---

frontend/src/components/resourceMap/GraphView.tsx
frontend/src/components/resourceMap/graph/graphFiltering.test.ts
frontend/src/components/resourceMap/graph/graphFiltering.ts
frontend/src/components/resourceMap/graph/graphGrouping.tsx
frontend/src/components/resourceMap/graph/graphLookup.test.ts
frontend/src/components/resourceMap/graph/graphLookup.ts
frontend/src/components/resourceMap/sources/GraphSources.tsx

This fixes a stack overflow crash #2534 and improves grouping and filtering performance 
There's still a bunch of stuff that can be optimized so this is only first step
Testing done:
After fixes:
Map loading time: 5s
Filter by error: <1s
Group by node: <1s
Before:
Map loading time: ~3.5min
Filter by error: 50s
Group by node: 9s

frontend: Improve Map performance

---

charts/headlamp/templates/pvc.yaml

This fixes binding of storage class to pvc.
Fixes: #2579
Done on AKS cluster. Works now

charts: Fix storageClassName in pvc

---

frontend/src/components/common/LogViewer.tsx
frontend/src/components/common/Terminal.tsx

frontend: Enable allowProposedApi in XTerminal

---

plugins/headlamp-plugin/package.json

This change adds npm install to the update-dependencies script in headlamp-plugin to update the package-lock.json file to avoid having to do this manually.
Fixes: #2469

headlamp-plugin: Run npm install in update deps script

---

frontend/src/plugin/index.ts

This change allows the frontend to update plugin fields from the backend, avoiding the case where a plugin is updated but the version number does not reflect this.
Fixes: #2535

frontend: plugin: Sync plugin version with backend

---

frontend/src/components/job/List.tsx

This change adds a sort function for job duration times. Previously, sorting by duration would show the list of jobs out of order, but this should no longer be the case.
Fixes: #2564

frontend: Job: Add sort function for job durations

---

frontend/src/components/common/Resource/AuthVisible.tsx

This change validates the authVerb passed into the AuthVisible component before calling `getAuthorization()`, which prevents components from rendering with an invalid verb.
Fixes: #2147

frontend: AuthVisible: Validate verb before auth check

---

frontend/src/components/authchooser/AuthChooser.stories.tsx
frontend/src/components/authchooser/__snapshots__/AuthChooser.AnError.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.AuthTypeoidc.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.BasicAuthChooser.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.Testing.stories.storyshot
frontend/src/components/authchooser/index.tsx

This change makes the back button on the auth fail pop-up persist to allow the user to navigate back to home from an inaccessible single-cluster context.
Fixes: #2591

frontend: AuthChooser: Add home navigation on auth fail

---

frontend/src/components/cluster/ClusterChooserPopup.tsx

This change fixes a visibility issue with the 'Add Cluster' button in the cluster chooser pop up.
Fixes: #2601

frontend: ClusterChooserPopUp: Fix dark mode visibility

---

README.md

Before
After
supports light/dark theme

readme: Update header image and format

---

backend/cmd/headlamp.go

This should not be enabled in a release.
I'd like this disabled now, so it isn't enabled in the next release accidentally before it's ready.
related:
- https://github.com/headlamp-k8s/headlamp/pull/2563

backend: Disable websocket multiplexer

---

plugins/headlamp-plugin/vite-types.d.ts

This fixes CI fail when typechecking headlamp-plugin

plugins: Fix vitest placeholder type

---

frontend/src/lib/k8s/crd.ts

Fixes a regression introduced in #1967 where namespaced scope was left out when creating Custom Resource class.
Fixes #2613

frontend: Add missing isNamespaced property to Custom Resource class

---

frontend/src/components/node/List.tsx
frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
frontend/src/components/node/utils.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json

This change adjusts the width of the table columns to prevent UI issues and fills in empty values where applicable.
Fixes: #2100

frontend: Node: Fix table columns and empty values

---

frontend/src/components/common/Link.tsx
frontend/src/components/workload/Overview.tsx
frontend/src/lib/k8s/api/v2/hooks.ts

Every time Link accepts kubeObject we can populate query cache with that item so the navigation is instant and resource isn't loaded again.
This is done on "pointerenter" even to only populate the item user is about to click

frontend: Populate query cache when kubeObject is passed into a Link

---

frontend/src/components/resourceMap/useQueryParamsState.test.tsx
frontend/src/components/resourceMap/useQueryParamsState.tsx

How to test:
Go to map
Select a node
Refresh the page
Node should still be selected
Before this fix it wouldn't work

frontend: Rewrite useQueryParamsState logic and add unit tests 

---

frontend/src/components/resourceMap/GraphControls.tsx
frontend/src/components/resourceMap/GraphRenderer.tsx
frontend/src/components/resourceMap/GraphView.tsx
frontend/src/components/resourceMap/graphConstants.ts
frontend/src/components/resourceMap/useGraphViewport.ts

Remembers your last selected view mode
For example:
Click on fit to view on the map
Navigate around
It will now always fit to view (used to be fit to 100% by default)

frontend Map: Remember zoom mode. Move viewport logic to useGraphViewport hook

---

.github/workflows/frontend.yml

Since our CI has been broken for more than a month this PR disables the step that fails
I personally missed a couple of actual ci errors by assuming it's just 'test plugin' step that's failing 
Related #2549 #2560

CI: disable test plugins steps

---

frontend/src/components/App/PluginSettings/PluginSettings.tsx

fixes issue #2666 
This PR fixes a UI issue in the plugin settings page when running Headlamp in `app mode`. Previously, toggling the enable/disable switches for plugins did not visually reflect the updated state. The switches remained in their original positions until the save button was clicked and the page reloaded. This issue was limited to the UI, as the save functionality correctly updated the plugin state on reload.
1. **Real-Time Switch Updates**:
- Fixed the UI behavior to ensure that the enable/disable switches visually reflect the updated state immediately after being toggled.
- The switches now display the correct position without requiring a page reload.
2. **Enhanced State Handling**:
- Updated the component logic to synchronize the UI state with the underlying plugin state …

frontend: PluginSettings: Fix non responsive enable toggle

---

frontend/src/components/common/LogViewer.tsx

fixes issue #2640
This PR fixes an issue with the `LogViewer` component where log lines did not expand to the full width when in full-screen mode. This issue impacts user experience, especially for users relying on the full-screen view to read long log lines.
1. **Full-Width Expansion**:
- Updated the `LogViewer` component's logic allowing render handlers to run resizes to ensure log lines expand to utilize the full width in full-screen mode.
---
1. Open the `LogViewer` component in the pods details view.
2. Switch to full-screen mode.
3. Verify:
- Log lines expand to the full width of the screen in full-screen mode.
- Log lines remain readable and aligned correctly in both standard and full-screen modes.
4. Test on various screen sizes to ensure responsiveness and compatibility.

frontend: LogViewer: Fix log not expanding on full screen

---

frontend/src/components/Sidebar/prepareRoutes.ts

This change filters out routes with the optional `hide` property from propagating in the route list.
Fixes: #2663

frontend: Sidebar: Filter out hidden routes

---

frontend/src/components/common/Table/Table.tsx

Fixes #2669
This bug only occurs when the table has more than one page.
Steps to reproduce
1. Go to the page with a bunch of items (>1 page)
2. Select one item
3. Then click on select all checkbox

frontend: Fix memoization for Head cell when selecting all rows

---

frontend/src/components/ingress/Details.tsx
frontend/src/components/ingress/List.tsx
frontend/src/components/resourceMap/sources/definitions/networkSource.tsx
frontend/src/lib/k8s/ingress.ts

This fixes #2695 
While the crash only happens in the Map, I've fixed all the other places where it could potentially happen

frontend: Mark http field in IngressRule as optional and fix type errors

---

charts/headlamp/templates/deployment.yaml

There is currently no way of setting arbitrary environment variables when reading OIDC config from secrets, this PR allows it.

charts: fix: allow env vars to be set when reading others from secrets

---

backend/cmd/stateless.go

This ensures that:
We only store contexts that actually match the requested cluster name. We don't return a context key unless we've successfully stored a context.
Tested and it works now.
Fixes: #2622

backend: Fix cluster addition

---

plugins/headlamp-plugin/install-dependencies.sh
plugins/headlamp-plugin/test-plugins-examples.sh

This change addresses a security issue where dependencies are not pinned. 
Fixes: #2084

headlamp-plugin: Use npm ci to pin deps

---

frontend/src/components/common/NamespacesAutocomplete.tsx

This change alphabetically sorts namespaces in the UI, addressing the case where namespace lists from k3d/k3s clusters are not sorted by default.
Fixes: #2656

frontend: k8s: Sort namespaces in UI

---

.github/workflows/pr-to-update-choco.yml

Solves issue #2683 
This PR introduces an automation workflow and a supporting script to streamline the process of updating the Chocolatey package for Headlamp. The automation workflow automatically updates the headlamp.nuspec file and the checksum in app/windows/chocolatey/tools/chocolateyinstall.ps1, then creates a new PR with the changes for the updated version.
1. New Automation Workflow:
- Added a GitHub Actions workflow that:
- Runs the choco-auto.js script to update the headlamp.nuspec file with the new version number.
- Updates the checksum in chocolateyinstall.ps1 to match the new version.
- Automatically opens a new PR with the changes.
2. choco-auto.js Script:
- Added choco-auto.js to app/windows/chocolatey.
- This script handles:
- Updating the headlamp.nuspec file with the …

workflows: Add automation for choco upgrade

---

frontend/src/components/common/Table/Table.tsx

Fixes #2676
Currently table only updates grid layout based column visibility that comes from the props (which is used in Resource tables). 
But internal Table visibility state wasn't taken into account causing bugs like #2676
This PR handles internal state `table.getState().columnVisibility` to generate table layout.

frontend: Fix column visibility handled by internal Table state

---

docs/contributing.md

So we don't have to keep updating the docs about it, now that we have a public and reliable official calendar.

docs: Remove the individual mention of the monthly call event

---

frontend/src/components/App/Layout.tsx

It's a "css reset" that comes from mui library.
Makes scrollbars match the theme for example.
Before
After

frontend: Add CssBaseline component for improved default styles

---

frontend/src/components/common/ActionsNotifier.tsx

This change adds a unique refKey for error states, separate from success states, and creates a unique key for every snackbar. This addresses a regression where failure notifications would not appear in the UI.
Fixes: #2655 
```
apiVersion: v1
kind: ConfigMap
metadata:
name: configmap!
data: {}
```

frontend: ActionsNotifier: Adjust keys for snackbars

---

frontend/src/lib/k8s/api/v2/useKubeObjectList.test.tsx
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts

Found a bug with useKubeObjectLists when selecting fewer namespaces than before
Steps to reproduce 
1. Go to Pods
2. Select at least 2 namespaces
3. Observe correct amount of websocket connections (same as amount of namespaces)
4. Deselect some namespaces 
5. More websocket connections are recreated than needed

frontend: Fix useKubeObjectLists when deselecting namespaces

---

charts/headlamp/templates/pvc.yaml

Added validation to ensure required fields are provided. This will fail chart installation if size is not specified when PVC is enabled.
Keep the size value empty in values.yaml for persistentVolumeClaim.
```yaml
persistentVolumeClaim:
enabled: true
size: ""
```
- Run `helm template headlamp charts/headlamp` to see the error.

charts: Fix pvc storage requirement

---

backend/pkg/kubeconfig/file_test.go
backend/pkg/kubeconfig/watcher.go
backend/pkg/kubeconfig/watcher_test.go

When a context was being added and removed from KUBECONFIG file, it was still visible in UI. This removes the cluster from store and returns correct list of clusters.
Fixes #2541

backend: Fix reloading of clusters in kubeconfig

---

backend/cmd/multiplexer.go
backend/cmd/multiplexer_test.go
frontend/src/lib/k8s/api/v2/KubeList.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
frontend/src/lib/k8s/api/v2/webSocket.ts

This fixes a race condition in the WebSocket multiplexer where sending a COMPLETE message could panic if the connection was closed. Added proper connection state checking and error handling to safely handle closed connections.
- Add connection state check before writing messages
- Return early if connection is already closed
- Add error logging for failed writes
- Properly handle WriteJSON errors
Ref: https://github.com/headlamp-k8s/headlamp/pull/2563#issuecomment-2572713349

backend: prevent panic in WebSocket multiplexer

---

frontend/src/components/common/Label.tsx

Fixes #2726 
This PR adds TimeAgo component that updates every second to display time since the given date. 
Only the date itself updates and the table is not re-rendered so there's pretty much no impact on performance.

frontend: Add TimeAgo component that displays and auto refreshes time

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/SidebarItem.tsx
frontend/src/components/Sidebar/Sidebaritem.stories.tsx

With this change only items that were updated will rerender

frontend Sidebar: Improve performance by moving isSelected logic to the parent component

---

frontend/src/components/App/TopBar.tsx

This change hides the top bar menu on mobile when there are no actions to display.
Fixes: #2066

frontend: TopBar: Hide menu on mobile when empty

---

backend/cmd/multiplexer_test.go
backend/pkg/cache/cache.go

- **backend: cache: Fix race condition in cleanUp**
- **backend: multiplexer_test: Fix data race**
Fixes #2734
Run this:
`cd backend && go test -race -v -p 1 ./...`
There should be no races detected.

backend: Fix two races

---

frontend/src/lib/k8s/api/v2/webSocket.ts

This fixes watching individual kubernetes objects.
How to fix:
1. Go to any resource details (Pods > any pod, for example)
2. Make sure there are no errors in console and websocket connection is established
Fixes: #2736

frontend: Add missing base url in useWebSocket hook

---

frontend/src/components/cronjob/Details.tsx
frontend/src/lib/k8s/KubeObject.ts
frontend/src/lib/k8s/api/v1/factories.ts

Main point of this refactor is to use patch function when using suspend/resume button. This will only send a `{ spec: { suspend: true/false } }` update to the server instead of sending the whole object. Which will make it simpler and avoid any resourceVersion conflitcs. 
How to test:
- Open any CronJob
- Click on Suspend/Resume
- Click on Spawn Job
- Edit the CronJob
There shouldn't be any errors and should behave as expected
<details>
<summary>Sample CronJob yaml</summary>
```
apiVersion: batch/v1
kind: CronJob
metadata:
name: yearly-cronjob
namespace: default
spec:
schedule: "@yearly"
jobTemplate:
spec:
template:
spec:
containers:
- name: yearly-job
image: busybox:latest
command:
- /bin/sh
- -c
- "echo Happy New Year!; date"
restartPolicy: OnFailure
```
</details>

frontend: CronJob details refactor

---

frontend/src/lib/router.tsx

The route lookup for storedRoutes in createRouteURL was matching based on path key, now correctly matches using the route's name property.

frontend: Fix createRouteURL to match routes by name

---

frontend/src/lib/k8s/api/v2/webSocket.test.ts
frontend/src/lib/k8s/api/v2/webSocket.ts

We now mock console logs in tests and do not console errors for tests env.
This:
- Remove unnecessary console logs due to `v2` websocket usage
- Fix some message handling bugs in some error conditions
Part of:
- #2753
- #1802
<details>
<summary>Click to view Old logs</summary>
```bash
WebSocket error: Event {
type: 'error',
timeStamp: 1737091724622,
target: WebSocket {
listeners: { open: [Array], message: [Array], error: [Array], close: [Array] },
_onopen: [Function (anonymous)],
_onmessage: [Function: bound handleWebSocketMessage],
_onerror: [Function (anonymous)],
_onclose: [Function (anonymous)],
url: 'ws://localhost:4466/wsMultiplexer',
protocol: '',
binaryType: 'blob',
readyState: 3
},
srcElement: WebSocket {
listeners: { open: [Array], message: [Array], error: [Array], close: …
```

frontend: fix websocket logs errors in tests

---

docs/platforms.md

So people evaluating Headlamp have a bit more of an idea of it's functionality.
Having integrations documented is a requirement for CNCF incubating projects.

docs/platforms: Add CNCF integrations table

---

docs/platforms.md

The external tools running from Flatpak have been reported to be working, but there's a prior command that needs to be run by the user. So this PR adds a mention of that to the docs:
fixes #1885

docs: Add Flatpak to platforms with comment about external tools

---

README.md
docs/faq.md
docs/index.md

So people can find the community meeting more easily.
Also this is checked by the lxf insights scorecard.

docs: Add mention of monthly community meeting

---

app/electron/main.ts
backend/pkg/exec/exec.go
backend/pkg/exec/exec_test.go
backend/pkg/exec/syscallattr_other.go
backend/pkg/exec/syscallattr_windows.go
backend/pkg/exec/testdata/test-plugin.sh
backend/pkg/kubeconfig/kubeconfig.go

On Windows, even when the exec plugin's command is not interactive, running the command was still making the terminal window flash (default behavior on Windows). This can be annoying if a tool runs the exec plugin frequently. This patch prevents that problem by setting a sys proc attribute to hide windows, only when in the Windows platform and when the exec is non-interactive.
On Windows:
1. Have a kubeconfig's context whose user has the exec plugin configured (to run a command), or add a test one e.g.:
```yaml
- name: test-exec
user:
exec:
apiVersion: client.authentication.k8s.io/v1beta1
command: '\Users\YOUR_USER\CreateEmptyFile.cmd'
```
2. Have a `CreateEmptyFile.cmd` script in your home folder:
```shell
echo. > %HOMEPATH%\K8sHeadlampCheck.txt
```
3. Start Headlamp with this kubeconfig …

backend: Prevent flashing terminal on Windows

---

frontend/src/components/common/Resource/EditorDialog.tsx

This change addresses a regression where a local MonacoEnvironment override caused conflicts with Monaco-based components like DiffEditor. The Monaco override logic in EditorDialog is now removed to restore the default environment.
Fixes: #2693

frontend: EditorDialog: Remove unneeded Monaco override

---

frontend/.storybook/preview.tsx
frontend/src/components/gateway/ClassDetails.stories.tsx
frontend/src/storybook.test.tsx

Fixes #2450
When storybook renders a single story it only loads the relevant files which is nice and efficient, but we have some complicated circular dependencies that cause crashes.
Forcing the import of the root App component will also load the whole dependency tree for the App and fix the crash

storybook: Add workaround for the circular dependecy crash

---

frontend/src/lib/k8s/api/v2/useKubeObjectList.ts

By default if user has 'allowed namespaces' and no namespaces selected in the dropdown, it should load only the 'allowed namespaces'
This case wasn't handled properly and would just pass empty array for namespaces which would load all namespaces.

frontend: Fix namespace selection when allowed namespaces is set

---

frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
frontend/src/components/Sidebar/prepareRoutes.ts
frontend/src/i18n/locales/de/glossary.json
frontend/src/i18n/locales/en/glossary.json
frontend/src/i18n/locales/es/glossary.json
frontend/src/i18n/locales/fr/glossary.json
frontend/src/i18n/locales/pt/glossary.json
frontend/src/i18n/locales/zh-tw/glossary.json

Changes "Gateway" label in sidebar to "Gateway (beta)".

frontend: Add beta label to Gateway

---

charts/headlamp/README.md
charts/headlamp/templates/ingress.yaml
charts/headlamp/tests/expected_templates/default.yaml
charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/extra-manifests.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/values.yaml

- Add ingress.labels field to allow setting custom labels on ingress resources
- Update ingress template to merge custom labels with default labels
- Add documentation and examples in chart README.md
- Update test templates with latest chart version
Fixes #2779

charts: Add support for custom ingress labels

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This package isn't necessary to have installed as per the message in #1992.

frontend: plugins: Remove unused @types/nock pkg

---

frontend/package-lock.json
frontend/package.json

This PR updates the Vite package to 5.4.14 to address an issue found in `npm audit`

frontend: Update vite to 5.4.14

---

docs/contributing.md

Fixes #2833
`Makefile` is present at root level of the project that is having PHONY for frontend lint and test commands also.
```
f@f:~/w/oss/headlamp$ make frontend-lint
cd frontend && npm run lint -- --max-warnings 0 && npm run format-check
> headlamp@0.1.0 lint
> eslint --cache -c package.json --ext .js,.ts,.tsx src/ ../app/electron ../plugins/headlamp-plugin --ignore-pattern ../plugins/headlamp-plugin/template --ignore-pattern ../plugins/headlamp-plugin/lib/ --max-warnings 0
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0
YOUR TYPESCRIPT VERSION: 5.6.2
Please only submit bug reports when …
```

Docs: Fix contributing doc test and formatting instruction

---

backend/pkg/portforward/handler.go
frontend/src/lib/k8s/api/v1/portForward.ts

This change modifies both frontend and backend port forwarding code to properly handle dynamic clusters by passing the user ID through a header instead of modifying cluster names directly. The frontend adds the header for dynamic clusters, and the backend appends the user ID to cluster names when the header is present.
Fixes: #1834, #2510
- Run backend `go run ./cmd -dev -enable-dynamic-clusters`
- Run frontend `npm start`
- Run app `npm run dev-only-app`
- Have a cluster in kubeconfig.
- Load another cluster using add cluster button
- Create deploy for testing
```bash
echo 'apiVersion: apps/v1
kind: Deployment
metadata:
name: debug-deployment
spec:
replicas: 2
selector:
matchLabels:
app: debug
template:
metadata:
labels:
app: debug
spec:
containers:
- name: debug
image: nginxdemos/hello …
```

portforward: Fix recursive loading

---

app/electron/locales/de/app.json
app/electron/locales/en/app.json
app/electron/locales/es/app.json
app/electron/locales/fr/app.json
app/electron/locales/pt/app.json
app/electron/main.ts
app/electron/plugin-management.ts

When installing a plugin, we are showing the plugin's ArtifactHub URL to the user for confirmation and this is not very interesting since all plugins are listed from ArtifactHub, in fact, what the user should confirm is the origin of the plugin package, because it's from that package that we will deploy the plugin.

Show plugin package URL for user confirmation

---

docs/development/index.md

The purpose behind this PR was that I noticed at this place:
https://github.com/headlamp-k8s/headlamp/blob/bdd56af4d8e96c9b094f05d7b72e8b01126a16d9/docs/development/index.md?plain=1#L69
before building the app, `make backend frontend` has been called and then `make app-linux` or whatever command user prefers gets called. 
However, at [this](https://github.com/headlamp-k8s/headlamp/blob/bdd56af4d8e96c9b094f05d7b72e8b01126a16d9/Makefile#L49) place, when we call `app-linux` for e.g., it calls `app-build` which inturn calls `frontend/build` which inturn calls `make frontend`. So the need for calling `make frontend` was definitely not necessary before building the app as all the OS specific commands already do the frontend build behind the scenes before building the app.
And regarding the …

docs: remove redundant backend, frontend build commands before building app

---

app/electron/main.ts
app/electron/preload.ts
frontend/src/components/App/AppContainer.tsx
frontend/src/helpers/index.ts

This change removes the backendToken from the URL and instead passes it via IPC. This ensures that restarting the app does not create new instances with unique URLs.
Fixes: #2846 
```ts
(window as any).parseKubeConfig = parseKubeConfig
```
```ts
window.fetch = new Proxy(window.fetch, {
apply: (target, thisArg, args) => {
console.groupCollapsed("+++ Intercepted Network Request");
console.log("URL:", args[0]);
console.log("Options:", args[1]);
console.trace("+++ Request Stack Trace:");
console.groupEnd();
return target.apply(thisArg, args);
}
});
```
```ts
window.parseKubeConfig({ kubeconfig: "test-kubeconfig-data" });
```

frontend: app: Pass backendToken via IPC

---

frontend/package-lock.json
frontend/package.json

This change updates vitest to the desired 2.1.9 version.

frontend: Update vitest to 2.1.9

---

backend/cmd/headlamp.go

Fixes #1848
The `refreshAndCacheNewToken` function in `backend/cmd/headlamp.go` is currently too long and complex, requiring a `//nolint:funlen` directive to bypass linter warnings. This makes the code harder to maintain and understand.
Refactored the function by:
- Breaking it down into smaller, more focused functions
- Improving readability and maintainability
- Removing the need for the `funlen` linter bypass

backend: refactor: refreshAndCacheNewToken in headlamp.go

---

.github/workflows/app-artifacts-mac.yml

When the Mac app fails to be code signed, the job still continues as it doesn't halt the process.

github: Make Mac build job fail if signing failed

---

frontend/src/components/cluster/ClusterChooser.stories.tsx
frontend/src/components/cluster/__snapshots__/ClusterChooser.LongClusterName.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterChooser.NoCluster.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterChooser.Normal.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterChooser.SpecialCharacters.stories.storyshot

References #931
Added `clusterChooser` components stories.
Here's storybook video of current state:
[Screencast from 2025-02-01 03-55-16.webm](https://github.com/user-attachments/assets/2cb22695-0d97-4878-83e3-f110ed5408c8)

frontend: Add clusterChooser componnent stories

---

frontend/src/lib/swagger-parser.k8s.test.ts

frontend: Add tests for `@apidevtools/swagger-parser`

---

frontend/src/components/cronjob/List.stories.tsx
frontend/src/components/cronjob/__snapshots__/List.Items.stories.storyshot
frontend/src/components/cronjob/storyHelper.ts
frontend/src/components/networkpolicy/__snapshots__/NextworkPolicy.Default.stories.storyshot

Fixes #2374 
[Screencast from 2025-01-30 19-12-59.webm](https://github.com/user-attachments/assets/2394d249-96e5-48e5-a89f-b833316652b5)
@illume can you please review this PR. Thanks.

frontend: Add `CronJobListView` story to test `cronstrue` dependency

---

frontend/src/components/cluster/Charts/ResourceCharts.stories.tsx
frontend/src/components/cluster/Charts/ResourceCharts.tsx
frontend/src/components/cluster/Charts/StatusCharts.stories.tsx
frontend/src/components/cluster/Charts/StatusCharts.tsx
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.CpuChartNoMetrics.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.CpuChartPod.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.CpuChartWithMetrics.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.MemoryChartNoMetrics.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.MemoryChartPod.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/ResourceCharts.MemoryChartWithMetrics.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.NodesStatusEmpty.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.NodesStatusLoading.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.NodesStatusWithMixedStates.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.PodsStatusEmpty.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.PodsStatusLoading.stories.storyshot
frontend/src/components/cluster/Charts/__snapshots__/StatusCharts.PodsStatusWithMixedStates.stories.storyshot
frontend/src/components/cluster/Charts/index.ts
frontend/src/components/cluster/__snapshots__/Overview.Events.stories.storyshot
frontend/src/components/common/Chart.stories/__snapshots__/PercentageCircle.Percent100.stories.storyshot
frontend/src/components/common/Chart.stories/__snapshots__/PercentageCircle.Percent50.stories.storyshot
frontend/src/storybook.test.tsx

References #931 
Brief overview:
- `Charts.tsx` originally had 4 chart components, from which `CpuCircularChart` and `MemoryCirclularChart` components had similar props, while `PodStatusCircularChart` and `NodeStatusCircularChart` had similar props.
- So, refactored chart.tsx into `ResourceCharts` and `StatusCharts`
- Created `.Stories.tsx` for both.
- Created index file and updated imports (if any).
@illume PR is currently ready for review, needed your opinion weather we should have done this separation of files or not? 
IMO it was too messy to deal this in single story file so refatrored a bit. Thanks !
Here's storybook video of current state:
[Screencast from 2025-01-31 23-57-28.webm](https://github.com/user-attachments/assets/b1e2f548-17e0-4ea9-87fc-bff2c9a47998)

Frontend: Add stories for chart componenets

---

.github/workflows/pr-to-update-minikube.yml

Because we will have an action in minikube's repo to update it.

github: Stop automatically creating minikube PR

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

These changes: 
- Updates jsonpath-plus to the desired 10.2.0 version
- Updates undici to the desired 6.21.1 version
- Overrides nth-check to the desired 2.0.1 version

frontend: headlamp-plugin: Update dependencies

---

frontend/src/components/App/Layout.tsx
frontend/src/components/App/TopBar.tsx
frontend/src/components/App/__snapshots__/TopBar.NoToken.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.ProcessorAction.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.Token.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
frontend/src/lib/themes.ts

These changes display the scroll bars for the main content and sidebar under the top bar. The width of the sidebar and the height of the top bar are also adjusted to prevent inconsistencies.
Fixes: #2679

frontend: Improve scroll bars

---

frontend/src/components/Sidebar/NavigationTabs.tsx

Fixes regressions introduced in #2717
First is a page crash when sidebar is collapsed - early return in a react component before a hook was called caused a crash
Second is duplicated entries in NavigationTabs - mutation of the sidebar entries inside NavigationTabs was causing issues
How to test:
Open/close sidebar
Navigate around

frontend: NavigationTabs: Move early return after all hooks to prevent a crash

---

app/electron/main.ts

- Pops up a dialog asking the user if they consent to running the command.
- Saves the choice and uses that choice in the future.
Related to
-  #1824
- #1744
The General Settings part of issue #1744 is out of scope for this PR. That will be done in a future PR.
---
From a security standpoint, this adds an extra layer of protection for the user.
Now:
- an attacker would need to change a plugin, AND the user settings to be able to run commands. 
Before this PR:
- they would just need to add something into a plugin.
---
Note: the running of commands is still disabled in main for now. Because we are not using that functionality yet. This PR does NOT enable the running of commands.

app: Add checkCommandConsent dialog for checking az/minikube/etc

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

To match frontend dependencies, and so
`npm run check-dependencies` passes again.

headlamp-plugin: Add fuse.js dependency

---

charts/headlamp/README.md

This reflects the actual parameter name on `values.yaml`.
I was installing this chart today and was basing myself off of the ArtifactHub docs to enable the ingress, but I noticed the `ingress.ingressClassName` parameter was actually documented as `ingress.className`.
It's up to you folks whether to update this on the documentation or to change the actual parameter name on `values.yaml`. I'm available if you need any more input.

docs: Change ingress.className on README to ingress.ingressClassName

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/common/Table/Table.tsx
frontend/src/components/namespace/NamespaceDetails.stories.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/pod/PodList.stories.tsx
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
frontend/src/lib/k8s/KubeObject.ts
frontend/src/lib/k8s/PodMetrics.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts

Fixes #1 
How to test:
Go to Pods
Check new columns CPU and Memory

frontend: Add Pod list metrics

---

frontend/src/components/common/Resource/DocsViewer.tsx
frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/components/common/Resource/__snapshots__/EditorDialog.EditorDialogWithResource.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/EditorDialog.ExtraActions.stories.storyshot
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json

This change gracefully handles comments from the editor dialog in the documentation tab, preventing the app from crashing.
Fixes: #2854

frontend: EditorDialog: Handle null YAML in docs tab

---

.github/workflows/app-artifacts-linux.yml
.github/workflows/app-artifacts-mac.yml
.github/workflows/app-artifacts-win.yml
.github/workflows/app.yml
.github/workflows/backend-test.yml
Dockerfile
Makefile
backend/.golangci.yml
backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/multiplexer_test.go
backend/cmd/stateless.go
backend/cmd/stateless_test.go
backend/go.mod
backend/pkg/config/config.go
backend/pkg/config/config_test.go
backend/pkg/helm/release.go
backend/pkg/kubeconfig/file.go
backend/pkg/plugins/plugins.go
backend/pkg/plugins/plugins_test.go
backend/pkg/portforward/handler.go
docs/development/index.md

- **backend/.golangci.yml: Remove deprecated linters**
- **backend: Upgrade golangci-lint@v1.64 and fix formatting**
- **github: Dockerfile: Update golang to 1.24**
- `make backend-lint` passing locally.
- smoke testing of headlamp app locally
- all tests pass in CI
We need a newer golang for some security fixes and also for this PR:
- https://github.com/headlamp-k8s/headlamp/issues/2892

backend: Update golang@1.24 and golangci-lint@v1.64

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/headlamp_testdata/kubeconfig_partialcontextvalid
backend/pkg/kubeconfig/kubeconfig.go
backend/pkg/kubeconfig/kubeconfig_test.go

We were loading clusters and checking if they had errors, but we'd still include them in the final list.
This PR also changes the tests since it seeems like some parts of the code were expecting the list of contexts to be always returned regardless of whether they had invalid contexts or not (this is how the tests were written), while other parts were assuming only [valid contexts](https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci9hNTgzYjliNTNhOWU3MTY0NTM2MDMwNGQzNjYyNzhhNjEwMTg0Y2ZlL2YvYmFja2VuZC9wa2cva3ViZWNvbmZpZy9rdWJlY29uZmlnLmdvP3VybD1odHRwcyUzQSUyRiUyRmdpdGh1Yi5jb20lMkZoZWFkbGFtcC1rOHMlMkZoZWFkbGFtcCZsaW5lcz0zMzk%3D?origin=gitlens) were [returned](https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci9hNTgzYjliNTNhOWU3MTY0NTM2MDMwNGQzNjYyNzhhNjEwMT …

backend: Do not include clusters with errors when loading them

---

frontend/src/components/App/Notifications/Notifications.stories.tsx
frontend/src/components/gateway/GRPCRouteDetails.stories.tsx
frontend/src/components/gateway/GRPCRouteList.stories.tsx
frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
frontend/src/components/gateway/HTTPRouteList.stories.tsx
frontend/src/plugin/pluginLib.test.ts
frontend/src/storybook.test.tsx

I've noticed that we have some warnings and misconfigured mocked handlers. 
This PR fixes awaiting of `toMatchFileSnapshot` and fixes missing or incorrect msw handlers

frontend: Fix test warnings and misconfiguration

---

app/electron/main.ts

This change refactors the zoom functionality in the Electron app to remember the zoom level in the Electron app after restarts.
Fixes: #2681

app: Remember zoom level after restarts

---

.github/workflows/build-container.yml

Currently our CI is crashing because of an old deprecated version of the `actions/cache`. 
[Example](https://github.com/headlamp-k8s/headlamp/actions/runs/13399139353/job/37425471463)
> Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
This PR updates it to the latest version pinned by a SHA hash.
According to the 'migration guide](https://github.com/actions/cache/discussions/1510) there are no breaking changes

CI: Fix CI crash - Update actions/cache action to v4.2.1

---

backend/cmd/headlamp.go

Fixes #2849
By default in helm charts 'dynamic clusters' feature is not enabled. In the code then /wsMultiplexer handler was skipped
How to reproduce:
Locally:
- Run `./backend/headlamp-server -html-static-dir ./frontend/build `
- Open any page see that /wsMultiplexer is failing
in cluster Helm:
- Run `helm install my-headlamp headlamp/headlamp --namespace kube-system`
- Expose the service through Ingress
- /wsMultiplexer is failing

backend: Move wsMultiplexer handler so it's not skipped without dynamic cluster feature

---

frontend/src/lib/k8s/event.ts

Seems like some objects can get related to the event without having a namespace but when they do need them for the link to work.
1. Copy the contents of:
https://raw.githubusercontent.com/Azure-Samples/aks-store-demo/main/aks-store-all-in-one.yaml
2. Paste the contents in the Create dialog in Headlamp and press apply
3. Go to the overview -> crash! (before this patch)

frontend: Fix broken link for involved objects in the overview

---

frontend/src/components/globalSearch/GlobalSearchContent.tsx

Fixes #2902 
Fixed by only displaying the `cluster settings` page once.

frontend: global searchbar: Fix multiple clusterSettings items

---

backend/go.mod

Otherwise this means people need to manually update their go versions.
This also means we need a go 1.24.x not 1.24.0. This is easier to maintain rather than having to update at each golang patch release. This is so we don't specify go 1.24.0
Details: https://go.dev/doc/toolchain#config
- tried this with Linux Ubuntu 22.04 and an older go 1.23 patch release installed and a newer one written in the go mod

backend: Add toolchain for those without latest go

---

frontend/src/components/App/TopBar.tsx
frontend/src/components/Sidebar/SidebarItem.tsx
frontend/src/lib/k8s/index.ts

How to reproduce:
- Go to Security, click in each sub-item of the sidebar under it
- Switch to another cluster using the top bar button
- Go to Secrets and click the sub-items again -> the URL will be the one from the previous cluster
This was caused by the stale `cluster` value that wasn't being updated. Using `useCluster` hook fixes it
Also updated useCluster hook so it doesn't trigger a rerender on every navigation

frontend: Fix incorrect links in sidebar after switching clusters

---

frontend/src/components/common/Resource/DetailsDrawer.tsx

Fixes a bug in details drawer in app mode
How to test/reproduce:
- Go to ConfigMaps (or any other resource)
- Click on one resource
- Close the details drawer
- Click on the same resource again
The spinner will show, check the `window.location.href` it will have url path set instead of the hash router

frontend: Fix DetailsDrawer to not mutate url when in app mode

---

frontend/src/components/Sidebar/useSidebarItems.test.tsx
frontend/src/components/Sidebar/useSidebarItems.ts

Fixes the regression to be able to handle custom entries that extend default items
for example 
```js
{
name: "custom-entry",
label: "Custom entry",
parent: "network"
}
```
Should add it to the network item in "IN_CLUSTER" sidebar
Added a test case for this

frontend: Update useSidebarItems hooks to support extending default sidebar items

---

.github/workflows/push-release-assets.yml

Couldn't test it yet because workflows need to be in main to show in the actions area first, apparently.

github: Add a new workflow to attach the release assets to a release

---

charts/headlamp/README.md
charts/headlamp/templates/deployment.yaml
charts/headlamp/values.yaml

charts: make in-cluster arg configurable

---

app/electron/main.ts
backend/cmd/headlamp.go

When I tried running both the version of headlamp in the Arch AUR (not official) and the AppImage in this repo I would get an error about a function not existing. This complete makes headlamp useless for my usecase in WSL2 (in one of the computers I tested).
This PR address these issues and performs the following changes:
In https://github.com/headlamp-k8s/headlamp/blob/v0.28.1/app/electron/main.ts#L1413 , we are not awaiting the Promise returned on the previous line, so it caused the exception I first mentioned in the issue. It happened because `serverProcess` was `null` when reaching the `attachServerEventHandlers` function. Solved by chaining a `then` at the end of it
When using on Arch, after fixing the first exception, I got a permission denied with the AUR package. With the …

app: fix headless mode not running

---

frontend/src/components/resourceMap/graphViewSlice.tsx
frontend/src/redux/drawerModeSlice.ts
frontend/src/redux/overviewChartsSlice.ts
plugins/headlamp-plugin/vite-types.d.ts

There were some private types that had to be exported for proper declaration generation and also vitest module stub types were added

headlamp-plugin: Fix building

---

frontend/src/components/node/List.tsx
frontend/src/components/node/utils.tsx
frontend/src/lib/k8s/node.ts

This change adds the 'value' field to the taint spec, allowing us to display the taint value in the node status on the list page.
Fixes: #2975

frontend: node: Display taint value in status

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This was published to the get the new APIs which minikube plugin depends on.

headlamp-plugin: Bump to version 0.11.1

---

Makefile

Otherwise enable dynamic clusters gets "true " and golang
does not think that is valid.

Makefile: Fix run-backend on windows

---

docs/development/plugins/publishing.md

It is not needed, and installing things globally can be harmful. The package command is inside the package.json scripts section, so use that instead.

docs: publishing: Remove install of headlamp-plugin globally

---

Makefile

-> Adds a new command `backend-lint-fix` 
-> This command is the updated version of the existing command `backend-lint` 
-> The difference is it has `--fix` flag which fixes the line-space errors, indentation, and missing full-stop errors itself.

Makefile: adds `backend-lint-fix` command

---

frontend/src/components/common/Resource/EditorDialog.tsx

This change gives additional information to the user about resource creation failures, using the reason provided in the value object. The message in the UI will fall back to the original message when a reason is not provided in the object.
Fixes: #3047

frontend: EditorDialog: Show error reason on failure

---

kubernetes-headlamp.yaml

just add readinessProbe for deployment workload

kubernetes-headlamp.yaml: Add readinessProbe to deployment

---

docs/development/plugins/functionality/index.md

Fixes links on this page https://headlamp.dev/docs/latest/development/plugins/functionality/
how to test:
in frontend run `npm run build-typedoc`
in headlamp-website repo run `npm run start`, make sure you've linked the docs

docs: Update links to APIs in the plugin functionality page

---

eslint-config/package.json

Due to restructuring the current present link is resulting in a 404.
No changes apart from correcting link pointing to correct README file

eslint: documentaton: fix dead link to headlamp eslint-config

---

backend/pkg/helm/repository_test.go

Fixes the failing `repository_test.go` file, causing due to repo. migration.
Related to https://github.com/kubernetes-sigs/headlamp/actions/runs/14382933450/job/40331061953?pr=2976
PR: https://github.com/kubernetes-sigs/headlamp/pull/2976

backend: fix helm repo test

---

backend/cmd/multiplexer.go
backend/cmd/multiplexer_test.go
frontend/src/lib/k8s/api/v2/webSocket.test.ts
frontend/src/lib/k8s/api/v2/webSocket.ts

Updates the websocket implementation to refresh authentication tokens during reconnection. This fixes the mismatch between token lifetime and websocket lifetime by ensuring the backend always has the latest token from the frontend, even after reconnection.
It is difficult to simulate a network disruption even when closing connection so the tests that I wrote help with that.
`TestGetOrCreateConnection_TokenRefresh`: When a new token is provided in a message, the connection's token is updated correctly.
`TestReconnect_WithToken`: During reconnection, the most recent token is used.
These tests provide good confidence that this change will correctly handle token refreshes during websocket reconnections.
- Run tests `cd backend && go test -v ./cmd -run …

multiplexer: Fix token refresh for ws reconnection

---

.github/workflows/backend-test.yml

When there is an error in the main branch backend tests we skip doing the coverage check.
Because currently there is a problem where other PRs fail the backend CI test job, because main is failing for it. (even if the PR fixes the issue).
- I commented out the previous step so that, and ran this code when there was an issue in main with the backend test
- I also ran the workflow injecting a fault into the base coverage step.

github/backend-test: Fix coverage so it skips when main fails

---

.github/workflows/push-release-assets.yml
app/scripts/push-release-assets/push-release-assets.js

- app push-release-assets.js: Fix uploading actual file. Waits for app assets to be uploaded and actually uploads
the file data.
- github push-release-assets: Remove blockmap files before uploading

github/workflows/push-release-assets: Fix pushing assets

---

frontend/package-lock.json
plugins/examples/app-menus/package-lock.json
plugins/examples/change-logo/package-lock.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/customizing-map/package-lock.json
plugins/examples/details-view/package-lock.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/headlamp-events/package-lock.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/resource-charts/package-lock.json
plugins/examples/sidebar/package-lock.json
plugins/examples/tables/package-lock.json
plugins/headlamp-plugin/package-lock.json

These changes bump vite in frontend and the plugins examples to v6.2.5.

frontend: plugins: Bump vite to 6.2.5

---

frontend/src/components/App/Settings/Settings.tsx
frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
frontend/src/components/Sidebar/useSidebarItems.ts
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/it/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json
frontend/src/redux/configSlice.ts

This change adds an option in the settings to sort the sidebar items alphabetically.
Fixes: #3061

frontend: Add option to alphabetize sidebar items

---

frontend/package-lock.json
plugins/examples/app-menus/package-lock.json
plugins/examples/change-logo/package-lock.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/customizing-map/package-lock.json
plugins/examples/details-view/package-lock.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/headlamp-events/package-lock.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/resource-charts/package-lock.json
plugins/examples/sidebar/package-lock.json
plugins/examples/tables/package-lock.json
plugins/headlamp-plugin/package-lock.json

These changes bump vite in frontend and the plugins examples to v6.2.6.

frontend: plugins: Bump vite to 6.2.6

---

frontend/src/components/Sidebar/Sidebar.tsx

This change updates the color of the Add Cluster button based on the currently used theme.

frontend: Sidebar: Use theme color for Add Cluster Button

---

backend/cmd/headlamp.go
backend/cmd/stateless.go
backend/pkg/kubeconfig/contextStore.go

just like the title, fix some typo errors in method comment and struct field

backend: fix some typo errors

---

frontend/src/components/resourceMap/GraphView.tsx

This change adds a queryParamsState for the namespace filter, allowing the query parameters to persist on refresh when they previously did not.
Fixes: #3110

frontend: Map: Persist query params on refresh

---

frontend/src/components/pod/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot

This change adds a new icon displaying the status of each container in the pods list. Hovering over the icon gives important info about the container at a glance: name, status, reason, exit code, and start/finish times.
Fixes: #2689, follow-up from #3008 
------
------

frontend: pod: Add quick status for containers

---

frontend/src/components/cronjob/Details.tsx

Truncates the generated cronjob name to a maximum of 63 characters to comply with kubernetes naming rules
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/3133

frontend: truncate long cronjob names

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/server.go
backend/pkg/config/config.go
backend/pkg/kubeconfig/kubeconfig.go
backend/pkg/kubeconfig/kubeconfig_test.go
backend/pkg/kubeconfig/watcher.go
backend/pkg/kubeconfig/watcher_test.go

for the default use-case, headlamp will load kubeconfig with `kubeconfig` options, and all context in the `kubeconfig` files will be automatically loaded, but sometimes there are some needs to hide some context across the kubeconfig file. So I want to add the feature to skip the contexts according to `skipped-kube-contexts`, it will be used like 
```
headlamp -kubeconfig=${kubeconfig1}:${kubeconfig2}
-html-static-dir=${path/to/static/bundles}
-plugins-dir=${path/to/plugins}
-dev
-enable-dynamic-clusters
-skipped-kube-contexts=ctx1,ctx2,ctx3
```

backend: add support for skip context

---

frontend/src/components/App/Settings/Settings.tsx
frontend/src/components/App/Settings/ThemePreview.tsx
frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
frontend/src/components/globalSearch/GlobalSearchContent.tsx

Add a little minimal preview of the theme

frontend: Add simplified Theme preview to Settings and Search

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/multiplexer.go

Fixes https://github.com/kubernetes-sigs/headlamp/issues/2970
Certain k8s vendors don't support tokens via Sec-Websocket-Protocol value, so we need to use the Authorization header instead.
Certain k8s vendors will perform additional cors check when browser-like User-Agent is present, which we currently pass but now will just remove.
How to test:
Create rancher cluster
Open headlamp and check for websocket connections (live updates to lists, logs and attach features)

Improve WebSocket compatibility

---

frontend/src/components/pod/List.tsx

Fixes https://github.com/kubernetes-sigs/headlamp/issues/3108
Table cell wasn't re-rendering because the "reason" label stayed the same but status (which impacts color and the icon) changed but wasn't taken into account in the getValue function
How to test (steps from reported issue):
Go to pod list
Delete a pod
Wait for recreation
Check status color

frontend: Include pod status in column text value to avoid stale status label state

---

plugins/examples/dynamic-clusters/src/index.tsx

This change applies the color of the button text for the dynamic-clusters plugin from the currently used theme.
```
cd plugins/examples/dynamic-clusters && npm install
npm run build
npm run start
```

plugins/examples/dynamic-clusters: Use theme color for buttons

---

e2e-tests/package-lock.json
e2e-tests/package.json
e2e-tests/tests/headlampPage.ts
e2e-tests/tests/namespaces.spec.ts
frontend/src/components/App/TopBar.tsx
frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
frontend/src/components/common/CreateResourceButton.tsx

This PR improves accessibility testing coverage and reliability of Playwright E2E tests in the project.
Note: this also fixes some e2e test failures for my other branches, once this is merged in I will drop the duplicates in the other branches.
- https://github.com/kubernetes-sigs/headlamp/pull/3124
- https://github.com/kubernetes-sigs/headlamp/pull/3123
- Adds `@axe-core/playwright` integration to the Namespaces Playwright test to perform automated **A11Y checks**.
- Introduces accessibility assertions to verify that no critical violations occur before and after creating a namespace.
- Fixes an issue detected by these tests: the **"Create" button lacked an accessible label**. This was resolved by adding an `aria-label` to ensure compliance with screen reader standards.
- Updates the …

Fix e2e auth logic + add namespace a11y playwright tests

---

app/electron/main.ts
backend/cmd/headlamp.go
backend/cmd/server.go
backend/pkg/config/config.go
docs/development/index.md

This change creates a CLI flag in the backend + desktop for watching changes to the plugins or their directory.
Fixes: #2894, follow-up from #2939

app: backend: Add flag for watching plugins changes

---

e2e-tests/package-lock.json
e2e-tests/package.json
e2e-tests/tests/headlampPage.ts
e2e-tests/tests/namespaces.spec.ts
frontend/src/components/App/TopBar.tsx
frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
frontend/src/components/common/CreateResourceButton.tsx

Reverts kubernetes-sigs/headlamp#3144
Seems like e2e tests started failing after this PR was merged 
Examples
https://github.com/kubernetes-sigs/headlamp/actions/runs/14639858867/job/41079478461?pr=3168
https://github.com/kubernetes-sigs/headlamp/actions/runs/14638805739/job/41076090849?pr=3167
https://github.com/kubernetes-sigs/headlamp/actions/runs/14639718092/job/41079030065?pr=3166
https://github.com/kubernetes-sigs/headlamp/actions/runs/14635662403/job/41066121159

Revert "Fix e2e auth logic + add namespace a11y playwright tests"

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go

This resolves an issue introduced in #3142 when decoding the bearer token from the websocket Sec-Websocket-Protoccol it assumes the token is padded.
When testing with tokens generated for Azure AKS and GKE, I noticed headlamp started to fail all websocket connections and upon further investigation, the tokens that did not have padding (==) were not decoded properly and the authorization header was malformed when sent to K8s.
This attempts to decode the token additionally with RawStdEncoding to catch these edge cases.
How to test:
- Included test case for tokens without base64 padding
- Test using Azure AKS or GKE using token obtained via OIDC integration or `kubelogin` (depends on the token whether or not padding is necessary, results were intermittent prior to this patch).

backend: Resolve issues with websocket token encoding

---

plugins/examples/custom-theme/package-lock.json

This change bumps vite in the custom-theme example plugin to v6.2.6.

plugins/examples/custom-theme: Bump vite to 6.2.6

---

frontend/src/components/pod/List.tsx

Fixes #3171 
* Add condition and different color when container state was terminated by an error
how to test:
apply the following 2 pod manifests to create a faulty and a working pod
start app and see both are showed properly
* the one with an error is red
* the one which was completed is green
```yaml
apiVersion: v1
kind: Pod
metadata:
name: error-pod
spec:
restartPolicy: Never
containers:
- name: error-container
image: busybox
command: ["sh", "-c", "exit 1"]
```
```yaml
apiVersion: v1
kind: Pod
metadata:
name: good-pod
spec:
restartPolicy: Never
containers:
- name: working-container
image: busybox
command: ["sh", "-c", "exit 0"]
```

frontend: Fix container status color

---

.github/workflows/push-release-assets.yml

This change limits the permissions of the GITHUB_TOKEN as desired.

github/workflows/push-release-assets: Limit token permissions

---

frontend/src/components/common/Table/Table.tsx
frontend/src/i18n/ThemeProviderNexti18n.tsx

This is so Material React Table, and Material UI use their internal locales when we switch to our locales.
So various UI elements in Table/Mui are rendered with the correct locales.
Before:
After:

frontend: i18n: Table: Add missing locale mappings

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/configmap/Details.tsx
frontend/src/components/configmap/__snapshots__/Details.WithBase.stories.storyshot
frontend/src/components/secret/Details.tsx
frontend/src/components/secret/__snapshots__/Details.WithBase.stories.storyshot

These changes allow the user to directly make changes to fields for configmaps and secrets without having to open the entire resource YAML in the editor dialog.
Fixes: #2412, follow-up from #2994
- #2412

frontend: Allow direct editing of resource fields

---

e2e-tests/tests/headlamp.spec.ts
e2e-tests/tests/headlampPage.ts
e2e-tests/tests/namespaces.spec.ts
e2e-tests/tests/namespacesPage.ts
e2e-tests/tests/pluginSetting.spec.ts
e2e-tests/tests/podsPage.ts

This should let us find a11y issues in the parts of the app that are tested by our playwright tests.
Thanks @vyncent-t
This is what it looks like when it fails. (Note the a11y violations are there pretty printed with the failing test).

e2e-tests: Add a11y check with Axe in many tests

---

frontend/src/components/workload/Overview.tsx

This change adjusts how we determine when to stop loading the workloads list, stopping the case where it loads infinitely.
Fixes: #3112

frontend: workload: Stop loading list infinitely

---

.github/workflows/helm-chart-template-test.yml
Makefile
charts/headlamp/README.md
charts/headlamp/tests/expected_templates/default.yaml
charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/extra-manifests.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/tests/readme.md
charts/headlamp/tests/test.sh
charts/headlamp/tests/update-version.sh

- Separates template testing from version updating.
- Fixes default test case comparison in test.sh
- Creates update-version.sh for version updates only
- Updates Makefile with helm-update-template-version target
- Adds documentation in README.md and tests/readme.md
- Improves GitHub workflow to catch all relevant changes
This change creates a cleaner workflow for testing and updating Helm chart templates, making it easier for contributors to validate their changes and update templates when needed.

charts: Improve Helm chart template testing

---

plugins/examples/ui-panels/src/index.tsx

This fixes failing e2e a11y tests for the new ui-panels plugin

plugins: examples: ui-panels: add role attribute to UI panel components for accessibility

---

app/electron/i18next-parser.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/App/Home/ClusterContextMenu.tsx
frontend/src/components/App/Home/ClusterTable.tsx
frontend/src/components/App/Home/config.ts
frontend/src/components/App/Home/customClusterNames.ts
frontend/src/components/App/Settings/ThemePreview.tsx
frontend/src/helpers/debugVerbose.ts
frontend/src/i18n/i18next-parser.config.js
frontend/src/i18n/tools/copy-translations.js
frontend/src/i18n/tools/extract-empty-translations.js
frontend/src/make-env.test.js
frontend/src/redux/uiSlice.ts
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/config/setupTests.js
plugins/headlamp-plugin/dependencies-sync.js
plugins/headlamp-plugin/plugin-management/plugin-management.e2e.js
plugins/headlamp-plugin/plugin-management/plugin-management.js
plugins/headlamp-plugin/plugin-management/plugin-management.test.js
plugins/headlamp-plugin/test-headlamp-plugin-published.js
plugins/headlamp-plugin/test-headlamp-plugin.js

A couple of files were missing the header and to catch header issues earlier I've added an eslint rule for it

frontend: Add lint rule for the license headers and add missing headers

---

frontend/src/components/App/themeSlice.ts

This change replaces useTypedSelector in the themeSlice file with react-redux's useSelector address a circular import between the themeSlice and reducers files.
Fixes: #3198

frontend: themeSlice: Use useSelector to fix import cycle

---

frontend/src/components/App/Home/ClusterTable.tsx
frontend/src/components/App/Home/RecentClusters.tsx
frontend/src/components/Sidebar/SidebarItem.tsx
frontend/src/components/common/Link.tsx
frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/crd/CustomResourceDetails.tsx
frontend/src/components/crd/CustomResourceInstancesList.tsx
frontend/src/components/crd/CustomResourceList.tsx
frontend/src/components/crd/Details.tsx
frontend/src/components/crd/List.tsx
frontend/src/components/gateway/GatewayDetails.tsx
frontend/src/components/gateway/GatewayList.tsx
frontend/src/components/ingress/Details.tsx
frontend/src/components/ingress/List.tsx
frontend/src/components/pod/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/role/BindingList.tsx
frontend/src/components/storage/ClaimDetails.tsx
frontend/src/components/storage/ClaimList.tsx
frontend/src/components/storage/VolumeDetails.tsx
frontend/src/components/storage/VolumeList.tsx
frontend/src/components/webhookconfiguration/Details.tsx
frontend/src/lib/cluster.ts
frontend/src/lib/k8s/KubeObject.ts
frontend/src/lib/k8s/api/v2/KubeList.test.ts
frontend/src/lib/k8s/api/v2/KubeList.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
frontend/src/lib/k8s/event.ts
frontend/src/lib/router.tsx

Fix all links that point to a resource but don't use kubeObject property and just use routeName + name
- Namespace column links
- 'Definition' link in Custom Resource details*
- 'Instance name' column in Custom Resource Instances list
- 'CRD' column in Custom Resource Instances list
- 'CRD' link at the top of the list in Custom Resource List
- 'Resource' column in Custom Resource Definition details*
- 'Resource' and 'Definition' columns in Custom Resource Definition list
- Gateway Class link in Gateway details*
- Gateway Class column in Gateway list
- Ingress Class link in Ingress details*
- Ingress Class link in Ingress list
- Node link in Pod details*
- Node, Nominated Node columns in Pod List
- Role, Namespace columns in Binding list
- Storage Class link in Claim details*
- Storage …

frontend: Various multicluster fixes

---

plugins/headlamp-plugin/README.md
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/dependencies-sync.js
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json
plugins/headlamp-plugin/plugin-management/multi-plugin-management.js
plugins/headlamp-plugin/plugin-management/multi-plugin-management.test.js
plugins/headlamp-plugin/plugin-management/plugin-management.js

Refs #2787, first PR towards original propossed solution.
**Scope and Tasks of this PR:**
The plugin-level config option was removed for now, as it might cause unnecessary confusion, though saved the TODO-based implementation that I removed in git stash, can be redone if required.
---
**individual Plugin with URL:**
`bin/headlamp-plugin.js install https://artifacthub.io/packages/headlamp/test-123/appcatalog_headlamp_plugin --folderName tmp`
**Bulk installations:**
- Create a file plugin-config.yml:
``` yml
plugins:
- name: test-app-catalog
source: https://artifacthub.io/packages/headlamp/test-123/appcatalog_headlamp_plugin
version: 0.0.3
- name: ai-plugin
source: https://artifacthub.io/packages/headlamp/test-123/ai_plugin
version: 0.0.2
- name: prometheus
source: …
```

Headlamp Plugins CLI: Bulk installations support

---

CONTRIBUTING.md

This pull request updates the Kubernetes Contributor Guide link in the `CONTRIBUTING.md` file to use **HTTPS** instead of **HTTP**.
- **Before:**  
`http://git.k8s.io/community/contributors/guide`
- **After:**  
`https://git.k8s.io/community/contributors/guide`
- Ensures secure and encrypted connection by default.
- Follows best practices for open source and documentation hygiene.
- Prevents potential issues with HTTP-to-HTTPS redirection.
- `CONTRIBUTING.md`

fix: Use HTTPS for Kubernetes Contributor Guide Link in CONTRIBUTING.md

---

plugins/headlamp-plugin/package-lock.json

This change bumps the undici dependency in the headlamp-plugin to the desired version.

headlamp-plugin: Bump undici to 6.21.3

---

frontend/.storybook/main.ts

So, I was facing an error while running first time the storybook using command directly 
Error Reproducing
- On a fresh repo clone, go to ./fontend/ and run Storybook
```
cd ./frontedn
npm install
npm run storybook
```
- You will see an error
- check file change in PR
Thank you :slightly_smiling_face: 
let me know if any changes required

fix: import fix on ./frontend/storybook/main.ts

---

frontend/src/components/common/Tabs.tsx

Documented the props, return types, and functionality in Tabs.tsx using TSDoc to improve developer understanding and maintainability.
---
This PR adds TSDoc comments to the `Tabs.tsx` component to improve code readability and maintainability. The documentation includes descriptions for props, return types, and internal logic.
Adding proper documentation helps:
* Other developers understand the purpose and usage of the component
* Improve editor/IDE autocomplete and type inference
* Reduce onboarding time for new contributors
* Encourage consistent documentation practices
* All exported types and functions in `Tabs.tsx`
* Inline comments where clarification is helpful
* No functional or behavioral changes were made.
* This is a documentation-only change.
---
I have added documentation for …

frontend: tabs: Add TSDoc comments for component and helpers

---

charts/headlamp/templates/deployment.yaml
charts/headlamp/templates/plugin-configmap.yaml
charts/headlamp/values.yaml
docs/installation/in-cluster/index.md
plugins/headlamp-plugin/README.md
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/plugin-management/multi-plugin-management.js

Implemented headlamp-plugin sidecar container for plugin management.
- charts: Added `--watch-plugins-changes` option to charts for the main headlamp container
- headlamp-plugin: Added watch option for config file changes in bulk install
- headlamp-plugin: Added cleanup for removal of plugins (in case the user removes a plugin from the config file)
- charts: Mount plugin.yml using a configMap-based volume
- charts: do a global `@kinvolk/headlamp-plugin` install and watch the config file
For docs, see https://github.com/kubernetes-sigs/headlamp/pull/2983/files#diff-6ba75da13a137e0dc291f25e5514187d41c825abf7cc74cee9e238cffbf7d539
I've tested by using my published npm package from my account https://www.npmjs.com/package/@faakhir/headlamp-plugin
and building the headlamp server image …

charts: Add headlamp-plugin sidecar for automated plugin management

---

frontend/src/components/App/Settings/Settings.tsx
frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot

This PR replaces the theme <Select> dropdown with a grid-based selector.
The grid uses appThemes to render all themes visually, allowing users to click and apply them.
I noticed the base themes are defined in themeSlice.ts, but I couldn’t clearly identify how to distinguish them from plugin-registered themes. If there’s a recommended way to separate base and plugin themes visually, I’d love some guidance to follow up with a second PR or improvement.
#3155

frontend: Settings: Replace theme dropdown menu with grid-based selector

---

frontend/src/components/App/themeSlice.ts

Adds 2 more themes. 
Monochrome Light
Lights Out
- Checked with "Accessibility Insights for Web" 
- Manually tested text contrast to verify accessible contrast level
- No a11y issues found

frontend: Add 2 more default themes

---

frontend/src/components/App/Notifications/List/List.stories.tsx
frontend/src/redux/drawerModeSlice.ts

Resolved a TypeError in the Notifications Docs and List stories by adding missing context providers. The drawer relied on Redux state which was not available without decorators in the story setup.
---
This PR fixes a rendering issue in the Notifications Docs and List stories in Storybook. The error was caused by missing Redux context, which resulted in a `TypeError` when accessing `isDetailDrawerEnabled`.
* Added necessary decorators to wrap the stories with required providers.
* Ensured proper rendering of the Notification Drawer in Storybook.
1. Run Storybook locally.
2. Navigate to:
* http://localhost:6006/?path=/story/notifications--list
* http://localhost:6006/?path=/docs/notifications--docs
3. Confirm the docs and list render without errors.
---
|Before(Docs) |After (Docs) | …

frontend: notifications: Fix storybook crash due to missing context

---

frontend/src/components/common/Terminal.tsx
frontend/src/components/node/NodeShellTerminal.tsx

In the Terminal component, while on Mac computers with a German layout, the pipe command was not being correctly inputted.
This commit adds a workaround till we find a better fix. I have filed https://github.com/xtermjs/xterm.js/issues/5341 to see if there's a fix possible in xterm.
fixes #3165 
1. While on a Mac with the German keyboard layout, open the shell in a pod and try to type the pipe character `|` (Alt+7) -> verify the pipe character is indeed inputted
2. Test the same key combo with other layouts to see that there are no regressions

frontend Terminal: Add workaround for inputting pipe character

---

frontend/src/components/Sidebar/NavigationTabs.tsx

There's something structuredClone doesn't handle...
> vendor-mui-Djh-99hi.js:40  DataCloneError: Failed to execute 'structuredClone' on 'Window': Symbol(react.element) could not be cloned.
>   at NavigationTabs (index-CgoiQPYG.js:1119:10657)

frontend: NavigationTabs: Fix to use cloneDeep instead of structuredClone

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/it/translation.json
frontend/src/i18n/locales/ja/translation.json
frontend/src/i18n/locales/ko/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json
frontend/src/i18n/locales/zh/translation.json

Changed the description of the left chevron and right chevron button in the sidebar. 
fixes: #3276 
Renamed Collapse sidebar to Shrink sidebar as the i18n support for Collapse Sidebar was there with a block 'S' but not the same for Expand Sidebar. Attached a screenshot of the translation.json for more context:
This is why some tests expecting Collapse Sidebar are failing as well.

frontend: Sidebar: Fix conditional expansion description text

---

backend/cmd/headlamp.go
backend/pkg/kubeconfig/kubeconfig.go
backend/pkg/kubeconfig/kubeconfig_test.go
backend/pkg/kubeconfig/test_data/kubeconfig_metadata
backend/pkg/kubeconfig/test_data/kubeconfig_metadata_duplicate

This PR introduces `clusterID` to be later used for non dynamic cluster actions (rename / delete) only. At current, cluster actions like rename and delete are done by locating the cluster by its `name` field. ClusterID is needed in order to separate non dynamic clusters from being impacted by overlapping action side effects of all other clusters. 
- Expands metadata field for clusters, metadata field now includes:
- Source  `cluster.metadata.origin.kubeconfig` : File path of the kubeconfig
- OriginalName `cluster.metadata.originalName` : Original name the cluster was created with
- ClusterID  `cluster.metadata.clusterID` : Unique ID for finding cluster, source + originalName
---
part 1/3 from - https://github.com/kubernetes-sigs/headlamp/pull/3121

Backend: Improve cluster metadata and add clusterID

---

frontend/src/components/App/Home/ClusterTable.tsx

Displays the actual kubeconfig path for cluster in the `origin` field when on the home view. 
- UI fix for App home view, `Origin` now displays correct Kubeconfig path
- Run headlamp in App mode
- Create a non dynamic cluster and let it load at home view
- At the home view: notice the specific Kubeconfig path under `Origin` on the table
--- 
part 2/3 from - https://github.com/kubernetes-sigs/headlamp/pull/3121

frontend: Home: Display true kubeconfig origin

---

frontend/src/components/common/InnerTable.stories.tsx
frontend/src/components/common/__snapshots__/InnerTable.Default.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.EmptyTable.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.InsideAnotherComponent.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithFewRows.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithoutTableHeader.stories.storyshot

This PR adds Storybook stories for the `InnerTable` component, which is a wrapper around the `SimpleTable` component. The stories demonstrate various use cases and configurations of the component.
- Added `InnerTable.stories.tsx` with 5 different stories:
- Default (Basic Inner Table): Shows a standard table with multiple rows
- WithFewRows: Demonstrates a table with a single row
- EmptyTable: Shows how the table handles empty data with a custom message
- WithoutTableHeader: Demonstrates the table without column headers
- InsideAnotherComponent: Shows how the table can be nested within other components

frontend: InnerTable: Add storybook stories

---

frontend/src/components/common/InnerTable.stories.tsx
frontend/src/components/common/ObjectEventList.stories.tsx
frontend/src/components/common/__snapshots__/InnerTable.Default.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.EmptyTable.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.InsideAnotherComponent.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithFewRows.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithoutTableHeader.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.ErrorFetching.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.NoEventsForObject.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.WithEvents.stories.storyshot

Add Storybook stories for ObjectEventList component
-Adds ObjectEventList.stories.tsx with three cases:
-WithEvents: Pod with multiple events
-NoEventsForObject: Deployment with no events
-ErrorFetching: Simulates fetch failure

frontend: ObjectEventList: Add stories

---

frontend/src/components/Sidebar/NavigationTabs.stories.tsx
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.ClusterParentSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.ItemWithoutOwnURLSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.NoSubList.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.SettingsParentSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.SidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.WorkloadsChildSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.WorkloadsParentSelected.stories.storyshot
frontend/src/components/common/InnerTable.stories.tsx
frontend/src/components/common/ObjectEventList.stories.tsx
frontend/src/components/common/__snapshots__/InnerTable.Default.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.EmptyTable.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.InsideAnotherComponent.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithFewRows.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithoutTableHeader.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.ErrorFetching.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.NoEventsForObject.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.WithEvents.stories.storyshot

Adds comprehensive Storybook stories for the NavigationTabs component, demonstrating various navigation states and sidebar interactions.
- Cluster View (Parent Selected)
- Workloads View (Parent Selected)
- Workloads View (Child 'Pods' Selected)
- Workloads View (Child 'Item Without URL' Selected)
- Settings View (Parent Selected)
- No Sub-List View
- Sidebar Open State

frontend: NavigationTabs: Add Storybook stories

---

frontend/src/components/Sidebar/ListItemLink.stories.tsx
frontend/src/components/Sidebar/NavigationTabs.stories.tsx
frontend/src/components/Sidebar/__snapshots__/ListItemLink.Default.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.IconOnly.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.IconOnlySelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.NoIcon.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.Selected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.SubItem.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.SubItemSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.UsingFullWidthPropFalse.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.UsingFullWidthPropTrue.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.WithDivider.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/ListItemLink.WithSubtitle.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.ClusterParentSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.ItemWithoutOwnURLSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.NoSubList.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.SettingsParentSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.SidebarOpen.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.WorkloadsChildSelected.stories.storyshot
frontend/src/components/Sidebar/__snapshots__/NavigationTabs.WorkloadsParentSelected.stories.storyshot
frontend/src/components/common/InnerTable.stories.tsx
frontend/src/components/common/ObjectEventList.stories.tsx
frontend/src/components/common/__snapshots__/InnerTable.Default.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.EmptyTable.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.InsideAnotherComponent.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithFewRows.stories.storyshot
frontend/src/components/common/__snapshots__/InnerTable.WithoutTableHeader.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.ErrorFetching.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.NoEventsForObject.stories.storyshot
frontend/src/components/common/__snapshots__/ObjectEventList.WithEvents.stories.storyshot

Changes: Added new Storybook for ListItemLink with the stories:
- Basic navigation with and without icons
- Selected and unselected states
- Sub-item variations
- Full width control
- Divider support
- Subtitle support
- Icon-only mode

frontend: ListItemLink: Add StoryBook stories

---

frontend/src/components/pod/Details.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/hi/translation.json
frontend/src/i18n/locales/it/translation.json
frontend/src/i18n/locales/ja/translation.json
frontend/src/i18n/locales/ko/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json
frontend/src/i18n/locales/zh/translation.json

This PR reduces the size of the toggle button and updates the *Show Previous* label to *Previous* to create room for potential additional toggle buttons in the future.
Discussed here: [Issue Comment](https://github.com/kubernetes-sigs/headlamp/pull/3331#issuecomment-2907860785)

frontend: PodLogViewer: Scale down and Rename toggle buttons

---

frontend/.storybook/preview.tsx

Removed in https://github.com/kubernetes-sigs/headlamp/pull/3362
Go onto some stories and refresh the page to see an import error, something to do with lib k8s.
> Cannot access 'KubeObject' before initialization.

frontend: storybook: Add back full import to fix vite/storybook bug

---

frontend/src/components/pod/PodLogs.stories.tsx
frontend/src/lib/k8s/pod.ts

This change reorders the unescaped string literals to ensure that any \ characters introduced by earlier replacements are not unintentionally unescaped again.

frontend: Pod: Reorder unescaped string literals

---

docs/installation/in-cluster/eks/index.md

Add guidance for users configuring Headlamp with non-Cognito OIDC providers or behind ingress controllers. Covers redirect URI construction, required headers, and EKS trust setup.
This change aims to prevent common misconfigurations and improve the onboarding experience for users deploying Headlamp.
Here's a screen shot of the extra info block I added to the fifth point:

docs: eks: Clarify OIDC setup for non-Cognito and ingress users

---

backend/cmd/multiplexer.go

Malformed authorization header was causing issues with the websocket connections when multiplexer is enabled
Steps to reproduce:
1. Login into cluster using Token
2. Open any resource list page
3. Verify that there are no "bad handshake" messages in the /wsMultiplexer websocket connection

backend: Add missing space before token in the Authorization header in multiplexed websocket connection

---

docs/index.md

Head over to
https://headlamp.dev/docs/latest/
The Code of Conduct link redirects to a wrong url
I have updated and fixed the link 
fixes #3266

frontend: Update Code of Conduct link in docs

---

app/mac/scripts/codeSign.js

https://github.com/kubernetes-sigs/headlamp/blob/5a334017cc02bb6aec597a2aef2ae66f0b7c6590/app/mac/scripts/codeSign.js#L2-L2
https://github.com/kubernetes-sigs/headlamp/blob/5a334017cc02bb6aec597a2aef2ae66f0b7c6590/app/mac/scripts/codeSign.js#L17-L18
Fix the issue will replace the use of `execSync` with `execFileSync`, which allows us to pass the command and its arguments separately. This approach avoids shell interpretation of the arguments, mitigating the risk of command injection. Specifically:
1. The `codesign` command will be passed as the first argument to `execFileSync`.
2. The dynamic components (`teamID`, `entitlementsPath`, and `config.app`) will be passed as separate arguments in an array.
3. This change ensures that special characters in the inputs are treated as literal values …

fix(codeSign) shell command built from environment values

---

.github/workflows/app.yml

windows-2019 is being deprecated, see more here https://github.com/actions/runner-images/issues/12045

ci: Update windows version to windows-2025

---

frontend/src/components/authchooser/__snapshots__/AuthChooser.AuthTypeoidc.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.BasicAuthChooser.stories.storyshot
frontend/src/components/authchooser/__snapshots__/AuthChooser.HaveClusters.stories.storyshot
frontend/src/components/authchooser/index.tsx

Fixes color for "log in" and "use cluster" buttons
Reported bug:
Now:

frontend: AuthChooser: Update buttons for better visibility

---

docs/installation/in-cluster/index.md
kubernetes-headlamp-ingress-sample.yaml

Updated the in-cluster installation docs to use the correct GitHub repo URL (`kubernetes-sigs/headlamp` instead of `kinvolk/headlamp`). Also updated the ingress manifest to use the `ingressClassName` field instead of the deprecated `kubernetes.io/ingress.class` annotation, for better compatibility with newer Kubernetes versions.

docs: update ingress example

---

backend/go.mod

There's CVE in net/http module 1.24.0 https://artifacthub.io/packages/helm/headlamp/headlamp?modal=security-report&image=ghcr.io%2Fheadlamp-k8s%2Fheadlamp%3Av0.31.0&target=headlamp%2Fheadlamp-server
So this PR updates the toolchain to the latest stable one

backend: Update go toolchain to 1.24.4

---

frontend/src/components/resourceMap/graph/graphGrouping.test.ts
frontend/src/components/resourceMap/graph/graphGrouping.tsx
frontend/src/components/resourceMap/graph/graphLayout.tsx
frontend/src/components/resourceMap/graph/graphModel.test.ts
frontend/src/components/resourceMap/graph/graphModel.tsx
frontend/src/components/resourceMap/nodes/KubeObjectNode.tsx

Fixes #3369 
1) Before Weights:
After Weights:
2) Before Weights:
[Screencast from 29-05-25 08:25:38 PM IST.webm](https://github.com/user-attachments/assets/7dfff547-dab8-40f2-9fc7-7ffb68c5ffa6)
After Weights:
[Screencast from 29-05-25 08:27:19 PM IST.webm](https://github.com/user-attachments/assets/c98fc3e3-449a-42da-960d-c2e69314c19a)
cc @sniok @yolossn

frontend: Map: Add weights to GraphNodes

---

frontend/src/components/common/ConfirmDialog.tsx
frontend/src/components/common/Resource/DeleteButton.tsx
frontend/src/components/common/__snapshots__/ConfirmDialog.ConfirmDialog.stories.storyshot
frontend/src/components/common/__snapshots__/ConfirmDialog.ConfirmDialogCancelHidden.stories.storyshot

- Better labels Delete/Cancel instead of Yes/No
- Contained buttons with clear primary and secondary versions
- Checkbox instead of a switch for better visibility
Before:
After:

frontend: Improve Delete dialog

---

Makefile
cloudbuild.yaml

Added this cloudbuild.yaml based on https://github.com/kubernetes-sigs/kwok/blob/main/cloudbuild.yaml .
@xmudrii , I am not sure if we are still missing adding k8s-staging-headlamp to https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/infra.yaml . I have added you as a reviewer because no one in the Headlamp is likely to be able to do a better check. I appreciate any guidance here.
Once we have this in, we need a ProwJob as in https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md .

Add cloud build / push to gcr.io

---

frontend/src/components/resourceMap/GraphView.tsx
frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
frontend/src/components/resourceMap/graph/graphModel.tsx
frontend/src/components/resourceMap/sources/GraphSources.tsx
frontend/src/components/resourceMap/sources/GraphSourcesView.tsx
frontend/src/components/resourceMap/sources/definitions/relations.tsx
frontend/src/components/resourceMap/sources/definitions/sources.tsx
frontend/src/lib/k8s/crd.ts

This PR adds Custom Resources to the Map in the frontend.
**Filter dropdown**
Custom Resources are grouped by API group in the dropdown and can be individually selected:
**Edges**
Edges between Custom Resources are shown for the Owner Reference in reverse order:
**Details View**
The same details view as in the Custom Resources Section is also shown in the Map:
**Approach for adding Custom Resources**
For now we have not squashed all the commits to show multiple ideas of how to add the CR details view. It was not clear for us which approach would be the best for this project, the latest one being the best integrated one from our point of view. Some changes were necessary since we dynamically load the CRD list, compared to the static approach of the base objects. If you think another …

frontend: map: Add Custom Resources support

---

frontend/src/components/ingress/Details.tsx
frontend/src/components/resourceMap/sources/definitions/relations.tsx
frontend/src/lib/k8s/ingress.ts

This PR marks `rules` field in the Ingress object as optional, and updates usages accordingly
Fixes #3522
1. Create Ingress without rules
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: my-ingress
spec:
defaultBackend:
service:
name: my-service
port:
number: 80
```
2. Go to Map and make sure it doesn't crash

frontend: Ingress: Mark rules field as optional

---

Makefile

This change updates the frontend lint fix make command from `make frontend-fixlint` to `make frontend-lint-fix`, in line with the backend lint commands.

Makefile: Update frontend-lint-fix command

---

Makefile

This PR adds `make lint` and `make lint-fix` targets for convenience.
See #3534
- Added target to Makefile
1. Check out the branch and run `make lint` and `make lint-fix`
2. Verify that it runs both sub-targets successfully

Add "make lint" and "lint-fix" targets

---

frontend/src/components/ingress/Details.tsx

This change displays the proper port number for the default backend, which was previously not shown. When no port is given, it falls back to the port name.

frontend: ingress: Display missing port for default backend

---

frontend/src/components/pod/Details.tsx

This PR fixes the verbs, used to determine if the "exec" and "attach" button is visible in the PodDetails.

Frontend: PodDetails: Fix wrong verbs

---

.github/workflows/pr-to-update-chart.yml
.github/workflows/pr-to-update-choco.yml
.github/workflows/pr-to-update-homebrew.yml
.github/workflows/pr-to-update-minikube.yml
.github/workflows/pr-to-update-winget.yml

This PR updates the branches used in CI workflows so they have the hl-ci- prefix, which doesn't get protected by the kubernetes branch policies, thus allowing us to delete/update them easily.
No test needed since this will be related to the release. Just double check if the logic makes sense and there are no typos or things like that.

github: Add hl-ci- as a branch name prefix

---

frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
frontend/src/lib/k8s/crd.ts

This PR fixes an issue with the auto-generated `kind` field in the Custom Resource (CR) creation template.
Fixes #3591
* Previously, the `kind` value in the generated CR template was being set using the `singular` field from the CRD.
* This behavior has been corrected to use the actual `kind` defined in the CRD.
1. Create a CustomResourceDefinition (CRD) where the `kind` and `singular` fields are different.
2. Open the CR creation form for that CRD.
3. Verify that the `kind` value in the YAML template uses the `kind` field from the CRD, not the `singular` one.
**Before:**
```yaml
apiVersion: school.com/v1
kind: student  # Incorrect: used the 'singular' field
metadata:
name: ''
```
**After:**
```yaml
apiVersion: school.com/v1
kind: Student  # Correct: uses the actual 'kind' field
metadata: …
```

fix the kind at cr creation template

---

frontend/src/components/common/Chart.tsx

These changes do the following:
- Adjust the colors of the bar chart so the bar is more visible in dark mode
- Render tooltips in a portal to prevent them from being clipped by the table row

frontend: Chart: Fix UI bugs

---

frontend/src/components/common/Table/Table.tsx
frontend/src/components/common/Table/__snapshots__/Table.WithGlobalFilter.stories.storyshot
frontend/src/components/workload/Overview.tsx

This PR introduces a feature to preserve the search filter state when navigating backward or forward within the application. Users will no longer need to reapply the filter repeatedly during navigation.
https://github.com/user-attachments/assets/33faa95a-783f-48bf-b808-fdf73e8fc40a
https://github.com/user-attachments/assets/e31f0186-fddf-450b-8324-7591c2634e2d
With this feature, the `URL` now includes the applied filter, making it look like:
> `{application_url}/c/my-new-profile/pods?filter={filter}`
This ensures the filter state is preserved during navigation.
[Remember filter when going back #3175](https://github.com/kubernetes-sigs/headlamp/issues/3175)

frontend: Table: Add Global filter

---

.gitignore
Makefile
backend/.air.toml

This PR adds hot-reload support for the Headlamp backend using the [Air](https://github.com/cosmtrek/air) tool, which improves the developer experience by automatically rebuilding and restarting the server when Go files are changed.
Fixes #3621
- Added `.air.toml` configuration file for Air in the `backend/` directory
- Added `run-dev` target to `Makefile` for running the backend with hot reload
1. Navigate to the project root
2. Run `make run-dev`
3. Modify any `.go` file in the `backend/` folder
4. Observe that the backend automatically rebuilds and restarts with updated code
- This is a development-only change and does not affect production behavior.
- it will create a bin folder to store the binary created by air file and it will automatically be deleted after termination

add air file for automatic reload

---

frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
frontend/src/components/node/utils.tsx

This PR fixes the overflow issue for taints at the node table .
Fixes #3634   
- updates the taint chip css 
1. Navigate to nodes under the cluster tab 
2.  and notice the taint field at the table 

frontend:fix the overflow taints node table

---

charts/headlamp/values.yaml

extraManifests example was not working properly, it failed with this error
Error: values don't meet the specifications of the schema(s) in the following chart(s): headlamp:
- extraManifests.0: Invalid type. Expected: string, given: object

fix: update extraManifests example

---

frontend/src/components/App/Settings/NodeShellSettings.stories.tsx
frontend/src/components/App/Settings/__snapshots__/NodeShellSettings.Default.stories.storyshot

This PR adds/fixes [feature/bug] by [brief description of what the change does]. 
This PR tries to add storybook and snapshots of NodeShellSettings. I've used busybox and kube-system as default values for container image and namespace respectively. Tested using make frontend-test in WSL and also updated the snapshots as required.
Fixes #ISSUE_NUMBER  There is no specific issue for which I've raised the PR, it tries to add a storybook.
- Added [file]

frontend: NodeShellSettings: Add Storybook and its snapshots

---

frontend/src/components/common/Table/Table.tsx

This fixes weird behavior when typing anything in the column filter value.
Due to internal handling of the input (multiple sources of truth, sync and debouncing) we cannot efficiently render header cell and have rerender the whole component on each update to the filter value.
fixes #3552
1. Go to any table
2. Open column filter
3. Slowly type anything
4. Filter value should appear as you type without any dropped characters

frontend: Table: Include filter value for memoization

---

frontend/src/components/resourceMap/sources/definitions/sources.tsx

This PR fixes an icon inconsistency for the "Network" section by updating the icon used in the resource map filter to match the one used in the sidebar.
Fixes #3485
- Updated the icon for the "Network" group in GraphSources.tsx
- Replaced mdi:lan with mdi:folder-network-online for visual consistency
1) Start Headlamp locally
2) Navigate to the Resource Map
3) Confirm that the Network icon in the sidebar and map filter now match visually

frontend: resourceMap: Unify network icon with sidebar

---

frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryAst.stories.storyshot
frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryMinute.stories.storyshot
frontend/src/components/job/List.tsx
frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
frontend/src/components/namespace/__snapshots__/NamespaceDetails.Active.stories.storyshot
frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
frontend/src/lib/k8s/job.ts
frontend/src/lib/k8s/pod.ts

This PR adds a create resource button for pod and job
Fixes #3659 
- Added buttons for pod and job creation

frontend:add create resource button  for  pod and job creation

---

frontend/src/components/common/Resource/EditorDialog.tsx

This PR fixes the behavior of the apply action by ensuring the editor closes automatically when all resources are successfully applied.
Fixes #3676 
- Updated `applyFunc` to invoke `onClose()` only if all apply operations succeed.
- Improved error handling and feedback for apply failures.
1. Navigate to the editor where you apply Kubernetes resources.
2. Apply multiple valid resources — the editor should close on success.
3. Apply a mix of valid and invalid resources — the editor should remain open and show an error.

fix the editor  close after successfull apply

---

frontend/src/components/cluster/ClusterGroupErrorMessage.tsx
frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithClusterErrors.stories.storyshot
frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithMutipleErrorsPerCluster.stories.storyshot

This PR aims to fix the issues found via FastPass for the cluster error message text not readable across all themes.
Mainly fixes the texts not being able to read easily on dark modes of headlamp, not an issue on light based modes.
---

Accessibility [FastPass]: Fix contrast for cluster error message text on all themes

---

frontend/src/components/common/Label.tsx

Similar to https://github.com/kubernetes-sigs/headlamp/pull/3687
This PR fixes the FastPass check failures for the label comp when we use dark mode. I have set the texts to be a few shades lighter so that it contrasts better in dark mode, the lights out mode does not have this same issue.

Accessibility [FastPass]: Fix contrast for labels for dark mode

---

frontend/src/components/App/Notifications/List/List.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/hi/translation.json
frontend/src/i18n/locales/it/translation.json
frontend/src/i18n/locales/ja/translation.json
frontend/src/i18n/locales/ko/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/ta/translation.json
frontend/src/i18n/locales/zh-tw/translation.json
frontend/src/i18n/locales/zh/translation.json

This PR fixes the FastPass check for the notifications menu button when on the notifications page. 
Added a translated string for screen readers for the menu icon button, it should now read out "Notifcations menu"
I also included a change that moves the on click so that tab navigation works as intended. (Before you could not tab then press enter to open the menu, now you can.)

Accessibility [FastPass]: Fix ARIA label and tab navigation for notifications menu

---

frontend/src/components/App/Settings/NumRowsInput.tsx
frontend/src/components/App/Settings/Settings.tsx
frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
frontend/src/components/common/NameValueTable/NameValueTable.tsx
frontend/src/components/common/TimezoneSelect/TimezoneSelect.tsx

This PR fixes accessibility related issues for the settings page, mainly just the issues found by FastPass on the `General` tab. 
These changes are part of a larger accessibility compliance goal from ADO (not sure if linking is allowed).
Issues are found using FastPass automated checks, feel free to download the tool and doublecheck if interested.
These aria labels are now added to the settings view
- Add aria labelled by for `Sort sidebar items alphabetically` menu switch
- Add aria labelled by for `Use evict for pod deletion` menu switch
- Add aria label for `Number of rows for tables` source component
- Add aria label for `Timezone to display for dates` source component
- Add aria label for drawer mode switch
- Updates `Language` to use typography (was plain text before)
I have ran …

Accessibility [FastPass]: Fix settings general missing aria input labels 

---

frontend/src/components/common/Link.tsx

Fixes #3704 
1. Go to custom resource instances
2. Click on name links
3. Details should render properly

frontend: Link: Pass custom resource definitions to Activities

---

frontend/src/components/activity/Activity.tsx

This PR fixes a bug where the Overview mode remains active with a blurred background UI even after all activities are manually closed one by one. The update ensures that when the last activity is closed, the overview mode exits automatically, restoring the normal UI state.
Fixes #3690 
- Updated the ActivitiesRenderer component to include a useEffect hook:
- This ensures the overview mode deactivates automatically when the taskbar is empty.
1. Open multiple activities in Headlamp.
2. Enter Overview mode.
3. Close each activity manually using the X button on the tabs (not "Close All").
4. After the last activity is closed, the UI should no longer be blurred and overview mode should exit.
https://github.com/user-attachments/assets/89e31249-3009-4859-9bea-5df99d460748

frontend: Activity: Fix exit overview mode when last activity is manually closed

---

frontend/src/components/App/Settings/NodeShellSettings.tsx
frontend/src/components/App/Settings/SettingsCluster.tsx
frontend/src/components/App/Settings/__snapshots__/NodeShellSettings.Default.stories.storyshot

This PR fixes accessibility related issues for the settings page, mainly just the issues found by FastPass on the "Cluster' tab. 
These changes are part of a larger accessibility compliance goal from ADO.
Issues are found using FastPass automated checks, feel free to download the tool and doublecheck if interested.
These aria labels are now added to the settings view
- Add aria labelled by for 'Allowed Namespace' name label and input
- Add aria labelled for 'Enable Node Shell'
related to issue https://github.com/kubernetes-sigs/headlamp/pull/3542

Accessibility [FastPass]: Fix FastPass ARIA checks for cluster page in settings

---

frontend/src/components/common/Tooltip/TooltipIcon.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
frontend/src/i18n/locales/de/glossary.json
frontend/src/i18n/locales/en/glossary.json
frontend/src/i18n/locales/es/glossary.json
frontend/src/i18n/locales/fr/glossary.json
frontend/src/i18n/locales/hi/glossary.json
frontend/src/i18n/locales/it/glossary.json
frontend/src/i18n/locales/ja/glossary.json
frontend/src/i18n/locales/ko/glossary.json
frontend/src/i18n/locales/pt/glossary.json
frontend/src/i18n/locales/ta/glossary.json
frontend/src/i18n/locales/zh-tw/glossary.json
frontend/src/i18n/locales/zh/glossary.json

This change adds a tooltip to display requests and limits values for pods, if provided. This will improve resource tracking for individual pods in real time.

frontend: Pod: Add tooltip for requests and limits

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/stateless.go
backend/cmd/stateless_test.go
backend/pkg/helm/charts.go
backend/pkg/helm/repository.go
backend/pkg/helm/repository_test.go
backend/pkg/kubeconfig/watcher.go
backend/pkg/logger/logger_test.go
backend/pkg/plugins/plugins_test.go
backend/pkg/portforward/internal_test.go

Remove unnecessary assignment in range for loop, the return values of range for are already local values, dont have to do it again in the range for loop body

backend: Remove unnecessary assignment in range for loop

---

backend/cmd/headlamp.go

Remove the dead code, and move router  use middle logic into createHeadlampHandler function
Fixes #3708

backend: HeadlampServer: Move router initialization codes to createHeadlampHandler

---

backend/pkg/config/config_test.go

This change refactors the parse tests by grouping them by test case, allowing us to reenable the linter.
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/3287, follow-up from https://github.com/kubernetes-sigs/headlamp/pull/3610

backend: config: Refactor parse tests

---

frontend/src/lib/k8s/index.ts

This change adds the missing TSDocs for the functions in `src/lib/k8s/index.ts`.

frontend: lib/k8s: Add TSDocs for functions

---

tools/releaser/src/commands/check.ts
tools/releaser/src/index.ts
tools/releaser/src/utils/github.ts

After each release, we have to rely on manually checking if all the release extended assets (Flatpak, minikube, homebrew, etc.) are updated, as sometimes CI fails. Sometimes we forget to check on one of these and that asset is not published until someone reports.
It would save a lot of time and effort to have a tool that does all these checks.  That's what this PR does.
1. Go to tools/releaser and run: npm install && npm run build && npm link
2. Run: `releaser check 0.33.0` to check for the release 0.33.0
3. Observe how it checks for extended release assets and shows the ones that are published and the ones that are not.
In the near future we should:

Improve releaser check

---

docs/installation/desktop/mac-installation.md

Adds `--no-quarantine` to the brew install command so that new users aren't confounded by corrupt binary errors (due to bad signature).
#3655

chore(docs): brew `--no-quarantine` kludge to resolve bad sig/corrupt binary error

---

app/electron/main.ts

This starts loading the backend right away, rather than waiting for the window to load.
With the mac losing signed binaries it meant they are additionally taking longer to load on first run.
Fixes #3596
-  #3596
- compile app on Mac, and install it
- run app
- See that 1) **clusters are there** (without having to refresh app)
- See that 2) **plugins are loaded** (without refreshing app)
- There should not be that much (or any) delay waiting (plugins and clusters should be there quickly... on main there is a delay currently)
- Intel and Silicon Macs with `npm start` and with compiled app (could reproduce before)
- Windows and Ubuntu compiled apps (could not reproduce before)

app: mac: Fix broken first load of clusters and plugins

---

frontend/src/components/common/ActionsNotifier.tsx
frontend/src/components/common/__snapshots__/ActionsNotifier.Some.stories.storyshot

This PR fixes the issue where the text for the ActionsNotifier (like cancel) were not readable on darker themes. I have set the text to be white as all themes share the same black background.
Related to issue https://github.com/kubernetes-sigs/headlamp/issues/3746
- Added contrast text to be white on all ActionsNotifiers
1. Navigate to dashboard of any resource
2. Click on the create button and create a resource
3. Notice the Actions Notifier on the bottom left text is readable

frontend: ActionsNotifier: Fix contrast issue for all themes

---

.gitignore

MacOS Finder leaves these little .DS_Store presents wherever it's used.

gitignore: Add ignore for mac .DS_Store files

---

frontend/src/components/common/Table/Table.tsx

This change improves the handleRowClick function in the Table component and stops the Table from blocking the switch functionality and allowing for range selection when it is not applicable.
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/3773

frontend: Table: Refactor handleRowClick for switches

---

charts/headlamp/templates/service.yaml
charts/headlamp/values.yaml

This PR adds option to define custom service annotations
Fixes #3750
- Added/Updated [component/file/logic]
- Fixed [bug/issue/typo]
- Refactored [code/module] for clarity/performance
1. add any annotation to `service.annotations` in `values.yaml` for example `testAnnotation: testValue`
2. run `helm template NAME PATH_TO_CHART -f values.yaml`
3. check annotations on service

helm: add custom annotations to service

---

frontend/src/components/cluster/Overview.stories.tsx
frontend/src/components/cluster/__snapshots__/Overview.EmptyState.stories.storyshot
frontend/src/components/cluster/__snapshots__/Overview.ErrorState.stories.storyshot
frontend/src/components/cluster/__snapshots__/Overview.LoadingState.stories.storyshot

Adds 3 Storybook stories for the Overview component:
- EmptyState (shows the UI when there's no data available)
- LoadingState (shows a spinner while data is being fetched)
- ErrorState (simulates when data fails to load)
Screenshots for new stories :
**EmptyState**
**LoadingState**
**ErrorState**
Note: I noticed that the Empty, Loading, and Error states all look quite similar in Storybook — they seem to show the same fallback message or UI. I'm assuming this is expected because the Overview component handles these cases in a similar way with mock data, but please let me know if I might have missed something!

frontend: cluster: Add Overview stories

---

frontend/src/components/App/Home/ClusterTable.tsx
frontend/src/plugin/__snapshots__/pluginLib.snapshot
frontend/src/plugin/registry.tsx
frontend/src/redux/clusterProviderSlice.ts

This allows overriding cluster status on the Home table.
install the minikube pre release plugin and see some stop/start buttons on the home page

frontend: ClusterTable: Add registerClusterStatus

---

backend/pkg/telemetry/metrics.go
backend/pkg/telemetry/metrics_test.go

Summary
This PR fixes WebSocket connection errors by implementing http.Hijacker interface support in the telemetry responseWriter.
Related Issue
Fixes WebSocket protocol upgrade failures that were causing "can't switch protocols using non-Hijacker ResponseWriter type *telemetry.responseWriter" errors.
Changes
- Added http.Hijacker interface support to telemetry responseWriter - Implemented Hijack() method to support WebSocket protocol upgrades
- Added necessary imports - Added bufio, fmt, and net packages for hijacking functionality
- Delegated hijacking to underlying ResponseWriter - Properly forwards hijack requests to the wrapped ResponseWriter when supported
Steps to Test
1. Start the backend server with make backend && cd backend && ./headlamp-server -dev
2. Navigate to any …

backend: fix responseWriter to support protocol switching

---

frontend/src/components/common/LogViewer.tsx

This change fixes an issue in Windows where the search bar in the log viewer overlaps with the scroll on the side.
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/3018, follow-up from [#3721 ](https://github.com/kubernetes-sigs/headlamp/pull/3721) by @greedy-wudpeckr

frontend: LogViewer: Prevent search overlapping scroll

---

frontend/package-lock.json

This change updates the cipher-base dependency in the frontend to the desired 1.0.6 version.

frontend: Bump cipher-base to 1.0.6

---

plugins/examples/app-menus/package-lock.json
plugins/examples/change-logo/package-lock.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/custom-theme/package-lock.json
plugins/examples/customizing-map/package-lock.json
plugins/examples/details-view/package-lock.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/headlamp-events/package-lock.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/projects/package-lock.json
plugins/examples/resource-charts/package-lock.json
plugins/examples/sidebar/package-lock.json
plugins/examples/tables/package-lock.json
plugins/examples/ui-panels/package-lock.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This change updates the vite-plugin-static-copy dependency in the headlamp-plugin and plugins examples to the desired 2.3.2 version.

plugins: Bump vite-plugin-static-copy to 2.3.2

---

frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/pod.ts

This change handles native sidecar containers, as enabled by default in Kubernetes v1.29. These sidecars are listed under `initContainers` with a special field `restartPolicy: Always` and remain running throughout the pod's lifetime.
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/2483

frontend: k8s: Handle new k8s feature native sidecars

---

docs/development/plugins/i18n.md
docs/development/plugins/index.md
frontend/src/plugin/__snapshots__/pluginLib.snapshot
frontend/src/plugin/index.ts
frontend/src/plugin/pluginI18n.ts
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/config/i18next-parser.config.js
plugins/headlamp-plugin/config/vite-plugin-name-injection.mjs
plugins/headlamp-plugin/config/vite.config.mjs
plugins/headlamp-plugin/src/index.ts
plugins/headlamp-plugin/template/package.json
plugins/headlamp-plugin/template/src/index.tsx

This PR adds the ability for plugins to use i18n.
fixes https://github.com/headlamp-k8s/plugins/issues/372
1. Go to the [pod-counter-with-i18n](https://github.com/kubernetes-sigs/headlamp/compare/main...headlamp-k8s:hl-shared:pod-counter-with-i18n) branch from the **hl-shared fork**
2. Go to headlamp-plugin; Run `npm i; npm run build; npm run pack`. This will create a _kinvolk-headlamp-plugin-0.13.0-alpha.3.tgz_ file
3. Go to the pod-counter example plugin; run `npm i; npm i -S ../../headlamp-plugin/kinvolk-headlamp-plugin-0.13.0-alp
ha.3.tgz ; npm run start`; Notice that it mentions the locales:
```bash
build started...
🎯 Plugin name detected: '@kinvolk/headlamp-pod-counter'
🎯 Plugin name detected: '@kinvolk/headlamp-pod-counter'
Checking if @kinvolk/headlamp-plugin is up to date...
🔄 …
```

Add support for i18n in plugins

---

backend/cmd/headlamp.go
backend/cmd/headlamp_test.go
backend/cmd/server.go
backend/pkg/config/config.go
backend/pkg/headlampconfig/headlampConfig.go
backend/pkg/k8cache/authErrResp.go
backend/pkg/k8cache/authErrResp_test.go
backend/pkg/k8cache/authorization.go
backend/pkg/k8cache/authorization_test.go
backend/pkg/k8cache/cacheInvalidation.go
backend/pkg/k8cache/cacheInvalidation_test.go
backend/pkg/k8cache/cacheStore.go
backend/pkg/k8cache/cacheStore_test.go
backend/pkg/k8cache/key.go
backend/pkg/k8cache/responseCapture.go
backend/pkg/k8cache/responseCapture_test.go

This PR is the refactored and cleaner PR of #3499, which includes Caching functionalities like Storing, Serving and Authorization of the user to access a resources.
-  Currently in this setup, cache is by-default ``false``, so to test it you would need to put make it true by overriding the ``CacheEnabled = true``, this would enable the cache.
There are many scenerios here which you can test it out:-
1.  If you want to test whether it is showing the data that the user was authorized to access it or not ? you can do it by creating your service accounts and bind roles and add resource which you want to test it out.
2. For the scenerio where the ``user's permissions`` just revoked by admin so for that you can remove your added <resource>  and now reload the resource page you should see the …

backend: caching: refactored PR for cache implementation 

---

frontend/package-lock.json
frontend/package.json
frontend/rsbuild.config.ts
frontend/src/components/App/AppContainer.tsx
frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/components/monaco/MonacoEditorLoaderInitializer.tsx
frontend/vite.config.ts
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This PR fixes the Monaco Editor not working in an air-gapped environment (no internet). By default the monaco-react package loads resources using the `jsdeliver.net` CDN, which I think is no good (we use Headlamp heavily in air-gapped environments at my workplace).
You can see the JSDeliver default config here: https://github.com/suren-atoyan/monaco-loader/blob/fc86117fb2f221070a509aa4539dd4644a607381/src/config/index.js#L3
I saw a previous issue related to air gapped environments (https://github.com/kubernetes-sigs/headlamp/issues/1103), so I assume this will be regarded as a bug here as well?
- I've configured the Monaco Editor loader so it loads the editor files from the assets folder, instead of importing the ESM module - this was the only way I could find to get the localisation …

Make monaco-editor work in an offline/air-gapped environment and fix localisation

---

frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx

This change moves useDispatch outside of the delete handler in `PluginSettingsDetails` to fix a regression where plugins could not be deleted.
Fixes: https://github.com/kubernetes-sigs/headlamp/issues/3793

frontend: PluginSettingsDetails: Move useDispatch outside delete handler

---

Dockerfile

This PR Bump the Node.js image version to 22 in Dockerfile,  Because the node version in frontend code is supposed ti >= 20.11.1
```json
"engines": {
"npm": ">=10.0.0",
"node": ">=20.11.1"
},
```

frontend: Dockerfile: Bump Node.js image version to 22

---

frontend/src/lib/k8s/KubeMetadata.ts
frontend/src/lib/k8s/api/v1/apply.ts
frontend/src/lib/k8s/api/v1/clusterApi.ts
frontend/src/lib/k8s/api/v1/clusterRequests.ts
frontend/src/lib/k8s/api/v1/factories.ts
frontend/src/lib/k8s/api/v1/formatUrl.ts
frontend/src/lib/k8s/api/v1/metricsApi.ts
frontend/src/lib/k8s/api/v1/scaleApi.ts
frontend/src/lib/k8s/api/v1/streamingApi.ts
frontend/src/lib/k8s/api/v2/apiDiscovery.tsx
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts

Using import type in the lib/k8s folder. Only v1 and v2 folders done for now.
Why use import type?
-  No runtime code, removed from compiled JavaScript, so zero bundle impact
-  Clear intent, signals you’re importing types only, not values
-  Avoids circular dependencies, safer when working across interdependent modules
-  Faster builds, helps TypeScript and bundlers optimize
-  Cleaner output, keeps runtime imports minimal and focused

frontend: lib/k8s: Fixing some circular imports

---

docs/development/plugins/index.md

This PR fixes an issue on the website currently where accessing the 'architecture' link from the plugins docs page would lead it to a broken link.
Fixes https://github.com/kubernetes-sigs/headlamp/issues/3864
- Fixed broken link for architecture under the plugins docs
1. Nav to `/docs/latest/development/plugins/`
2. Click on the `Plugin Architecture` link
3. Note that this should take you to the architecture docs and not a "page not found" error

Docs: Fix broken link to architecture from Plugins page

---

app/package-lock.json
app/package.json

These changes perform the following updates to the app dependencies:
- Remove the `electron/notarize` dependency, which is no longer needed after https://github.com/kubernetes-sigs/headlamp/pull/1741
- Adds the missing `glob` dependency which is required in `app/scripts/setup-plugins.js`

app: Update dependencies

---

charts/headlamp/README.md
charts/headlamp/templates/deployment.yaml
charts/headlamp/values.yaml

This PR adds the possibility to specify `podLabels`.
Fixes #3475
- Added ability to specify `podLabels`
1. Deploy with `podLabels` specified.
2. Verify that the labels on the Pod.
No screenshots.
Nothing special to say.

charts: add ability to specify podLabels

---

frontend/src/components/App/Notifications/List/List.tsx

This PR fixes the issue where the text for notification menu items were not readable on darker themes
Related to issue https://github.com/kubernetes-sigs/headlamp/issues/3746
- Added contrast text via theme.palette to all notification menu items
- Keeps buttons disabled when needed, just not readable
1. Navigate to notifications
2. Click on the menu button
3. Note that they are now contrast friendly

frontend: Notifications: Fix contrast for menu items on all themes

---

frontend/src/components/common/Label.stories/DateLabel.stories.tsx
frontend/src/components/common/Label.stories/__snapshots__/DateLabel.Default.stories.storyshot
frontend/src/components/common/Label.stories/__snapshots__/DateLabel.MiniLabel.stories.storyshot

This change adds Storybook stories for the DateLabel component.
Related issue: https://github.com/kubernetes-sigs/headlamp/issues/931

frontend: Add stories for DateLabel

---

.github/workflows/helm-chart-template-test.yml
charts/headlamp/README.md
charts/headlamp/templates/pdb.yaml
charts/headlamp/tests/expected_templates/pod-disruption.yaml
charts/headlamp/tests/test_cases/pod-disruption.yaml
charts/headlamp/values.schema.json
charts/headlamp/values.yaml

This PR adds an optional PodDisruptionBudget for the helm deplopyment
Fixes #ISSUE_NUMBER  
- Added optional PodDisruptionBudget for helm
1. render template as is
2. Set `.Values.podDisruptionBudget.enabled` to true
3. render again
- This should leave the default install without a PDB
- With `enabled` it should setup a PDB that lets headlamp be offline during a disruption

[helm] add optional PodDisruptionBudget

---

plugins/headlamp-plugin/bin/headlamp-plugin.js

The previous headlamp-plugin printed where files were copied.
It was added after a contrib fest spent telling people where files
were copied to. The next one didn't have this problem, but the
feature was lost after the vite port... and then people started
asking again.

headlamp-plugin: Fix npm start to log where files are copied

---

.github/workflows/docker-extension-release.yml

It could be the last version is not there in the current files
so we always just replace the latest version in those files.
Also we need to update the version sha256 hash.
I tested the commands locally, and they WFM.

github: docker-extension-release: Fix to just use latest tag

---

frontend/src/components/DetailsViewSection/detailsViewSectionSlice.ts

Because the input sections can contain ReactNode, the output
should also contain ReactNode.

detailsViewSectionSlice: HeaderActionFuncType: Fix return type to contain ReactNode

---

frontend/src/components/Sidebar/ListItemLink.tsx
frontend/src/components/Sidebar/SidebarItem.tsx
frontend/src/components/Sidebar/__snapshots__/ListItemLink.NoIcon.stories.storyshot

fixes: #2128 
This does fixes the issue but not sure if we should do it this way
In this pr we it is checking if url starts with `http` and if it does then that means our url is external and should open up in new tab.
example - 
`url: "https://www.youtube.com"` will open up in different window
but `url: "/someComponent"` will route within the headlamp
also as said in issue, we could add a separate `external_url` field to explicitly handle external URLs, but this may lead to ambiguity if both `url` and `external_url` are set by mistake

Feature: now sidebar can have external urls

---

frontend/src/components/project/ProjectDetails.tsx
frontend/src/redux/projectsSlice.ts
plugins/examples/projects/README.md
plugins/examples/projects/src/index.tsx

Modified #3844 PR 
This is a slightly updated PR, it makes all tabs behave the same way (default and custom) so the rendering logic is simpler
----
This PR allows overriding an existing tab in the Projects. If the ID of the tab we are registering matches an existing ID, then it will replace that tab.
Once this is merged, we should have another PR exporting the default IDs and documenting this change, but for now this should be already useful for some (even if a silent change).
1. Install the updated `project` example plugin
2. Verify it's overriding the Access tab
3. Uncomment the example of deleting a tab (which is commented out in the plugin code) -> verify it removes that tab

frontend: Allow overriding default tabs in the project view

---

frontend/src/components/common/Chart.tsx

This PR fixes a tooltip mispositioning bug in the Nodes table by calculating the tooltip position relative to the hovered CPU/Memory bar element.
Fixes #3937
Updated `frontend/src/components/common/Chart.tsx` to:
- Ensure correct tooltip rendering within the table
1. Ensure metrics-server is installed.
2. Open Headlamp → Nodes tab.
3. Hover over CPU/Memory usage bars on rows 1 and 2 → tooltips should align with the hovered row.
4. Hover over CPU/Memory usage bars on rows ≥ 3 → tooltips should align with the hovered row.
***Before***
***After***

frontend: fix: correct CPU/Memory tooltip positioning in Nodes table

---

frontend/src/components/common/Resource/EditButton.tsx

This PR fixes a bug where the Actions dropdown menu remains open after the "Edit" action is selected from a resource table. 
By modifying the shared EditButton component, this fix is applied to all tables that use it.
Fixes #3956 
Updated `frontend/src/components/common/Resource/EditButton.tsx` to ensure the menu-closing callback is triggered immediately upon clicking the Edit button.
1. Navigate to any resource list view with an "Actions" menu.
2. Click the kebab menu (three dots) in the "Actions" column for any row to open the dropdown.
3. Click on Edit.
4. Observe that the Actions dropdown menu closes as the YAML editor opens.

frontend: EditButton: close actions menu on edit click

---

frontend/src/components/project/ProjectDeleteButton.tsx
frontend/src/components/project/ProjectDetails.tsx
frontend/src/plugin/__snapshots__/pluginLib.snapshot
frontend/src/plugin/registry.tsx
frontend/src/redux/projectsSlice.ts
plugins/examples/projects/src/index.tsx

Adds `registerProjectDeleteButton` function available to plugins
```tsx
// delete button that is only enabled for certain projects
registerProjectDeleteButton({
isEnabled: async ({ project }) => project.clusters.length > 1,
component: ({ project }) => (
<button
onClick={() => {
console.log('Custom delete action');
}}
>
Delete {project.id}
</button>
),
});
```

frontend: Projects: Add ability to register custom delete button for projects

---

backend/cmd/headlamp.go

This PR fixes empty idpIssuerURL by setting fallback for kubeconfig field.
Fixes #3961
- Added fallback for idpIssuerURL
1. Set your idpIssuerURL outside of global flag
2. After logging in, wait for token to expire

fix: add fallback for idpIssuerURL

---

app/scripts/setup-plugins.js

This fixes a bug that is only happening on windows
setup-plugin.js fails to copy plugins because glob dependency was bumped from @7 to @11 
in version 8 they had a breaking change which treats all backslashes \ as an escape char which breaks path resolution on windows
- Replace \ with / in glob pattern
- Add more logging
0. (windows only)
1. rm -rf .plugins
2. cd app && node ./scripts/setup-plugins.js
3. Make sure .plugins folder has plugins with main.js and package.json in each

app: Fix glob pattern on windows for setup-plugins.js

---

frontend/src/App.tsx
frontend/src/components/Sidebar/NavigationTabs.tsx
frontend/src/lib/router/createRouteURL.tsx
frontend/src/lib/router/index.tsx

This PR fixes getRouteURL to work with routes registered from plugins.
Currently getStore() returns null resulting in createRouteURL not being able to lookup any routes registered by plugins
I also had to fix NavigationTabs since it started crashing as soon as createRouteURL was fixed
1. Open headlamp app
2. Go to App Catalog
3. Click on helm charts

frontend: Fix createRouteURL not being able to lookup routes from redux

---

frontend/src/App.test.tsx
frontend/src/components/App/Layout.tsx

On Mac it causes the app on Mac to show error page when switching
branches or sometimes on first load of compiled mac app.
Additionally it flashes white on a dark theme during this error.

frontend: Layout: Disable backend loader for now

---

frontend/src/components/common/Table/Table.tsx

This PR fixes a bug where clicking checkboxes inside dialog ("Force Delete" checkbox) incorrectly triggers table row selection instead of toggling the dialog's checkbox.
Fixes #3980 
- Updated `frontend/src/components/common/Table/Table.tsx`
1. Navigate to any resource list view (e.g., Workloads → Deployments)
2. Click the three-dot menu (actions) on any resource row
3. Click 'Delete'
4. In the "Delete item" confirmation dialog, click the "Force Delete" checkbox
5. Only the Force Delete checkbox should toggle
**Before**
https://github.com/user-attachments/assets/ad8ebdf1-aa8a-4974-a468-08fea5da0299
**After**
https://github.com/user-attachments/assets/7d75b1ee-99ae-4918-8c8c-0424de3dae89

frontend: Table: Prevent dialog checkbox clicks from triggering table row selection

---

plugins/examples/dynamic-clusters/package-lock.json

This change updates the form-data dependency to 4.0.4 as desired.

plugins: Bump form-data to 4.0.4

---

frontend/src/components/monaco/MonacoEditorLoaderInitializer.tsx

Sorry, I should have caught this issue the last version
* I added support for the Monaco Editor to work in offline mode in 0.35 https://github.com/kubernetes-sigs/headlamp/pull/3818
* In 0.35 using a custom baseURL was broken because of the rspack changes
* In 0.36 I fixed baseUrl support https://github.com/kubernetes-sigs/headlamp/pull/3883 but the fix didn't quite work for the offline Monaco Editor support.
Using the `makeUrl` function here handles the URL generation a bit better, adding missing slashes and removing duplicate slashes - this was the issue with the prior implementation.
- Fixed the url generation to handle missing/extra slashes `/`
Monaco editor working via webpack dev server with base url set
```sh
make run-backend
npm run start
```
Monaco editor working via docker image …

fix Monaco Editor with custom base url
