kubernetes-sigs/headlamp

frontend/.eslintrc.yml
frontend/src/App.js
frontend/src/components/Sidebar.js
frontend/src/components/cluster/Chooser.js
frontend/src/components/common/Chart.js
frontend/src/components/common/EditorDialog.js
frontend/src/components/common/Label.js
frontend/src/components/common/Link.js
frontend/src/components/common/LogViewer.js
frontend/src/components/common/Resource.js
frontend/src/components/common/SectionFilterHeader.js
frontend/src/components/common/SimpleTable.js
frontend/src/components/common/Tab.js
frontend/src/components/ingress/Details.js
frontend/src/components/role/BindingDetails.js
frontend/src/components/role/Details.js
frontend/src/components/workload/Charts.js
frontend/src/lib/api.js
frontend/src/lib/apiProxy.js
frontend/src/lib/router.js
frontend/src/plugin/registry.js
frontend/src/redux/actions/actions.js
frontend/src/redux/sagas/sagas.js

These rules are again consistent with the Nebraska project but were missing.

Add more linter rules (and fix issues)

---

frontend/src/components/common/EditorDialog.tsx
frontend/src/components/common/EmptyContent.tsx

Show error when no documentation

---

frontend/src/components/workload/Charts.tsx

Add legend for empty charts in workloads

---

frontend/src/components/cluster/Overview.tsx
frontend/src/components/common/SimpleTable.tsx

fixes #44 
Here's a screenshot of what happens when the data is changed:

Don't auto refresh tables automatically when new data is passed to it

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Sidebar.tsx

The cluster may be upgraded or downgraded while the user is using it,
but that change is silent because we only fetch the version once.
These changes make the version be fetched every minute, and if it
changes then a snackbar notification is shown informing the user about
that.

frontend: Notify the user when the cluster version changes

---

backend/cmd/server.go
frontend/src/plugin/index.tsx
frontend/src/plugin/loadPlugins.ts
frontend/src/plugin/plugins/.gitignore

This PR allows to build local plugins + changes the default plugins dir.

Improve plugins development

---

backend/cmd/cluster.go
backend/cmd/headlamp.go
backend/cmd/kubeconfig.go
frontend/src/App.tsx
frontend/src/components/account/Auth.tsx
frontend/src/components/cluster/Chooser.tsx
frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/k8s/index.ts
frontend/src/lib/router.tsx
frontend/src/redux/reducers/config.tsx

Allow to use client certificates for authenticating + make token requirement dependent on whether the auth fails.
fixes #4

Use context auth

---

frontend/src/lib/k8s/crd.ts
frontend/src/lib/k8s/index.ts

Fix class names

---

frontend/src/components/common/CreateButton.tsx
frontend/src/components/common/DeleteButton.tsx
frontend/src/components/common/EditButton.tsx
frontend/src/lib/k8s/cluster.ts
frontend/src/redux/sagas/sagas.tsx

Fix exceptions in cluster actions

---

frontend/src/App.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/cluster/Chooser.tsx
frontend/src/lib/k8s/index.ts

Add a useCluster hook and a logout button.
These functionalities weren't supposed to go in the same PR but the hook was needed also for the log out functionality so here it goes.

useCluster + Logout button

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

New version of Go and actions@checkout are available.
Signed-off-by: knrt10 <tripathi.kautilya@gmail.com>

Update github actions

---

app/electron/main.js

On desktop app quit kill the backend server on app close
Yes

Desktop: Kill the server running process on app quit

---

frontend/src/components/Sidebar.tsx
frontend/src/components/cronjob/List.tsx
frontend/src/components/daemonset/List.tsx
frontend/src/components/deployments/List.tsx
frontend/src/components/job/List.tsx
frontend/src/components/statefulset/List.tsx
frontend/src/lib/router.tsx

This patch adds seperate list views for workload types such as deployments,jobs,statefulset etc.
Testing
Done

Add dedicated list view to different  workload types

---

frontend/src/components/authchooser/index.tsx
frontend/src/lib/k8s/apiProxy.ts

Fixes some issues and improves the UX a bit in the login dialog.

Login improvements

---

app/electron/main.js

Log errors when something goes wrong executing or running the server process in the app.
With this PR the app logs stderr, and stdout from the `server` process.
Additionally the signal, and return code of the `server` process are logged.
related: https://github.com/kinvolk/headlamp/issues/112
What's not in this PR:
- updating the UI when there's a `server` related error.
- restarting or retrying server process start
Should we be logging the server.stderr URLs it prints out?
1. log when server process crashes or is killed.
```bash
make app-mac
```
run with logging enabled.
```bash
app/dist/mac/Headlamp.app/Contents/MacOS/Headlamp --enable-logging
```
In a separate terminal you can kill the `server` process.
```bash
while true; do killall server ; done
```
Now you should see an error log …

App server logging

---

app/electron/main.js
app/package-lock.json
app/package.json

Adds headless mode to the desktop app which allows user to open the app in there default browser
Run the headlamp desktop app with headless flag
example:
On linux use 
./Headlamp.AppImage headless to start the desktop app in headless mode(opening in your default browser)
Yes

Add headless mode

---

app/electron/main.js

fixes a lint problem that snuck through CI somehow

app: lint fix in main

---

app/electron/main.js

app: lint fix

---

app/package.json

Enable sourceMap for frontend build

---

app/electron/main.js
app/package.json

If we are in dev mode we set an env flag otherwise we assume we are in prod mode.
Testing Done 
Yes.

app: Update how we check dev mode for desktop app

---

frontend/.storybook/main.js
frontend/.storybook/preview.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/account/Auth.tsx
frontend/src/components/account/AuthToken.stories.tsx
frontend/src/components/common/Chart.stories/PercentageCircle.stories.tsx
frontend/src/components/common/Chart.tsx
frontend/src/components/common/Dialog.stories.tsx
frontend/src/components/common/Dialog.tsx
frontend/src/components/common/Label.stories/DateLabel.stories.tsx
frontend/src/components/common/Label.stories/HeaderLabel.stories.tsx
frontend/src/components/common/Label.stories/HoverInfoLabel.stories.tsx
frontend/src/components/common/Label.stories/InfoLabel.stories.tsx
frontend/src/components/common/Label.stories/NameLabel.stories.tsx
frontend/src/components/common/Label.stories/StatusLabel.stories.tsx
frontend/src/components/common/Label.stories/ValueLabel.stories.tsx
frontend/src/components/common/Label.tsx
frontend/src/components/common/SimpleTable.stories.tsx
frontend/src/components/common/Tab.tsx
frontend/src/components/common/Tabs.stories.tsx

Basic .storybook configuration, and some stories using https://storybook.js.org/ for:
- Chart
- Dialog
- SimpleTable
- Tab
- Label
- AuthToken
```bash
cd frontend
yarn install
yarn storybook
```

Storybook, start adding stories for frontend development

---

app/electron/main.ts

Change the default windows size for desktop app

---

backend/cmd/cluster.go

for https://github.com/kinvolk/headlamp/issues/180
Where relative paths are also supported in the kubectl config.
related https://github.com/kinvolk/headlamp/issues/112
In .kube/config we add a relative path.
```yaml
- cluster:
certificate-authority: ca.crt
```
Tried a relative path "ca.crt", and an absolute path "/Users/rene/.kube/ca.crt", and it loads the correct file.

Support relative certificate-authority paths in config

---

frontend/src/components/account/Auth.tsx

Help link for authentication docs

---

backend/go.mod

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

backend: correct the golang module name

---

frontend/src/components/cluster/Overview.tsx

Add namespace column to events table.

---

frontend/src/components/authchooser/AuthChooser.stories.tsx
frontend/src/components/authchooser/index.tsx
frontend/src/components/common/Chart.stories/PercentBar.stories.tsx
frontend/src/components/common/Chart.tsx
frontend/src/components/common/ConfirmButton.stories.tsx
frontend/src/components/common/ConfirmButton.tsx
frontend/src/components/common/LogViewer.stories.tsx
frontend/src/components/common/LogViewer.tsx

- Charts/PercentBar
- AuthChooser
- ConfirmButton
- LogViewer 
```
cd frontend
npm run storybook
```

Add  storybooks (PercentBar, AuthChooser, ConfirmButton, LogViewer) for frontend

---

app/.gitignore
app/electron/main.ts
app/package-lock.json
app/package.json
app/scripts/after-pack.js
app/scripts/build-backend.js

The app was relying on the use of the node_modules from the frontend and was shipping the electron js twice by mistake.

App refactoring

---

backend/cmd/headlamp.go

This issue caused the AppImage build to fail to run.
```bash
rm -rf app/dist
make app-linux 
cd app/dist
./Headlamp-0.2.1-linux-x86_64.AppImage --headless
```
```bash
./backend/server -dev -base-url /headlamp
PUBLIC_URL="/headlamp" make run-frontend
```
```bash
cd frontend
npm install 
npm run build
cd ..
./backend/server -dev -base-url /headlamp -html-static-dir frontend/build
```

Fix baseURLReplace on read only fs

---

app/package.json

Add arm64 and armv7l arch builds.

More app arches

---

frontend/package-lock.json
frontend/package.json

@ashu8912 I've moved them to the devDependencies

Move prettier, husky, lint-staged to devDependencies

---

backend/cmd/headlamp.go

As reported in https://github.com/kinvolk/headlamp/issues/209#issuecomment-801329837 , a mismatch between the OIDC issuer's returned URL and the one the client is configured with was crashing the server because the errors were not being treated.
I looked also into how to be tolerant to the URL difference of a trailing slash, but I noticed that it's a hard comparison within the OIDC lib we use, and any examples on Github were not working around this, so I think for now it's safer to keep the error reporting alone and expect users to set up the matching URLs (any solution for a tolerant comparison should be implemented in the OIDC lib IMO).

backend: Don't continue OIDC logic on errors

---

.github/workflows/build-container.yml
.github/workflows/container-publish.yml
.github/workflows/frontend.yml
Dockerfile

* Add image publishing on a new tag.
* Build an image for every frontend/backend change.
* Fix an issue when building the image (again)

Auto image publishing

---

app/package.json
app/scripts/build-backend.js

Fix app icons

---

backend/cmd/headlamp.go

If Headlamp is running with a base URL and uses OIDC, the redirect
URL doesn't take into account the base URL which leads to an error.
fixes #238

backend: Consider the base URL for OIDC's redirect URL

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Link.tsx
frontend/src/components/common/Resource/MetadataDisplay.stories.tsx
frontend/src/components/common/Resource/MetadataDisplay.tsx
frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/common/Resource/__snapshots__/MetadataDisplay.stories.storyshot
frontend/src/components/common/Resource/index.tsx
frontend/src/components/common/SimpleTable.tsx
frontend/src/components/pod/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/pod.ts
frontend/src/lib/util.ts

- frontend: Add link to node in Pod details view
- frontend: Use StatusLabel component for the Pod status in details view

Add more resource info to Pod details

---

frontend/src/components/common/Resource/EditorDialog.tsx

Fix editor, which was breaking after typing

---

frontend/src/components/authchooser/index.tsx
frontend/src/lib/router.tsx

... so there is a way to change the locale if only the auth chooser dialog is chosen.

Add a LocaleSelect to AuthChooser

---

frontend/src/components/authchooser/index.tsx
frontend/src/i18n/locales/en/auth.json
frontend/src/i18n/locales/es/auth.json
frontend/src/i18n/locales/pt/auth.json

And update the existing locales.

frontend: Make authchooser's titles translatable

---

frontend/src/components/common/SimpleTable.tsx
frontend/src/i18n/LocaleSelect/LocaleSelect.tsx

Fixes a couple of errors printed to the dev console.

Fix some console.error key issues

---

.github/workflows/container-publish.yml
Makefile
docs/development/_index.md
kubernetes-headlamp.yaml

Use ghcr.io instead of quay.io for Headlamp's container image

---

.github/workflows/app.yml
Makefile
app/mac/scripts/notarize.js
app/package.json

For testing the linux app build to start with.
I looked into seeing if there's a "--fail-with-warnings" that the electron builder gives us, which I hoped to use to catch issues like the icons missing one... but it doesn't exist.
I want to add a very simple test to that PR to see if the executable runs and then exits. A --run-and-exit type command, which runs and then exits. So we can confirm executable is working.

Add app.yml workflow

---

app/package-lock.json
frontend/package-lock.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

- frontend: Update refractor for fixing security issues
- frontend: Update prismjs for security fixes
- app: Update glob-parent for security fixes
- plugins/headlamp-plugin: Update packages with npm audit fix

Security updates

---

app/.gitignore
app/electron/main.ts
app/electron/preload.ts
app/package-lock.json
app/package.json
app/tsconfig.json
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/releasenotes/index.tsx
frontend/src/components/updatepopup/index.tsx
frontend/src/i18n/electronI18n.tsx

Add update popup and release notes

---

frontend/package-lock.json

Fixes some build time `npm audit` found issues with the "url-parse", and "tar" dependencies.

frontend: Do npm audit fix

---

frontend/src/components/configmap/Details.tsx
frontend/src/components/crd/Details.tsx
frontend/src/components/daemonset/Details.tsx
frontend/src/components/ingress/Details.tsx
frontend/src/components/namespace/Details.tsx
frontend/src/components/node/Details.tsx
frontend/src/components/pod/Details.tsx
frontend/src/components/role/BindingDetails.tsx
frontend/src/components/role/Details.tsx
frontend/src/components/secret/Details.tsx
frontend/src/components/service/Details.tsx
frontend/src/components/serviceaccount/Details.tsx
frontend/src/components/statefulset/Details.tsx
frontend/src/components/storage/ClaimDetails.tsx
frontend/src/components/storage/ClassDetails.tsx
frontend/src/components/storage/VolumeDetails.tsx
frontend/src/components/workload/Details.tsx
frontend/src/helpers/renderHelpers.tsx
frontend/src/plugin/registry.tsx
frontend/src/redux/actions/actions.tsx
frontend/src/redux/reducers/ui.tsx

Allow to append more details view via plugins

Add facility to override details view

---

backend/cmd/headlamp.go
frontend/package-lock.json
frontend/package.json
frontend/src/components/TestHelpers/theme.ts
frontend/src/helpers/renderHelpers.test.tsx
frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/k8s/customresource.ts
frontend/src/lib/k8s/index.ts

Allow patch requests and provide handlers for it

Provide patch functionality

---

frontend/src/helpers/renderHelpers.tsx
frontend/src/plugin/index.tsx

add a component via a plugin  registerDetailsViewSection method place a useEffect with unmount handler inside it to see if it gets called each time the parent state changes

Fix render issues and add more modules to pluginLib

---

.github/workflows/app-artifacts-linux.yml
.github/workflows/app-artifacts-mac.yml
.github/workflows/app-artifacts-win.yml
.github/workflows/draft-release.yml

This is a PR towards automating the release process a bit more.
It builds and uploads the apps as an action artifact, so we can test them, and creates a release draft with the format we've been using.

Upload app artifacts & draft release

---

README.md
docs/development/plugins/building.md

- README.md: Rearrange feature list to highlight important features
- README.md: Replace docs' links to point to the new github page
- README.md: Add plugin development section
- docs: Link video on how to develop plugins

Readme improvements

---

frontend/src/components/App/RouteSwitcher.tsx
frontend/src/lib/router.tsx

Fix missing plugins routes

---

frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/components/crd/Details.tsx
frontend/src/lib/k8s/crd.ts

- frontend: Fix hook usage in EditorDialog
- frontend: Fix listing objects in CRDs

Fix showing CRD objects

---

frontend/src/lib/k8s/apiProxy.ts

Headlamp was using its resource classes in order to apply the
configurations desired by the user (in the Create/Edit dialog).
However, if the user used a configuration of a Custom Resource
Definition, it would fail as the kind would not be known to Headlamp.
This patch fixes that by not requiring the use of resource classes
for the mentioned uses.
fixes #364

frontend: Allow to apply unknown resource configurations

---

frontend/src/components/TestHelpers/theme.ts
frontend/src/components/common/Resource/MetadataDisplay.tsx
frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/common/SectionBox.tsx
frontend/src/components/common/SectionHeader.tsx
frontend/src/components/common/__snapshots__/SectionBox.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.stories.storyshot
frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
frontend/src/components/pod/Details.tsx
frontend/src/components/pod/Volumedetails.stories.tsx
frontend/src/components/pod/__snapshots__/Volumedetails.stories.storyshot
frontend/src/lib/themes.ts

Add Volume list to Pod view
Add Volume mounts and livenessProbe details to container section
fixes some parts of #173

Pod view changes

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/pod/List.tsx

- frontend: Add a container status label to the Pod details view
- frontend: Make the Pod status better show its real status
- frontend: Show more details about the container status in Pod details

Show more detailed container statuses

---

frontend/src/components/common/SectionFilterHeader.tsx

- frontend: Fix focusing the filter's search entry
- frontend: Make strings in the SectionFilterHeader translatable

Fix focus on search

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/daemonset/Details.tsx
frontend/src/components/namespace/Details.tsx
frontend/src/components/node/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/pod/Pod.stories.tsx
frontend/src/components/pod/__snapshots__/Pod.stories.storyshot
frontend/src/components/workload/Details.tsx

Add the list of pods which belongs to a deployment under deployment view and remove container section from Deployment Detail view

Add pod list deployments

---

app/.gitignore
app/electron/main.ts
app/electron/windowSize.test.ts
app/electron/windowSize.ts
app/package-lock.json
app/package.json

still needs to be tested on larger screens

Limit the window size for desktop app, setup jest test framework

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/Resource/MetadataDisplay.tsx
frontend/src/components/cronjob/Details.tsx
frontend/src/components/cronjob/List.tsx
frontend/src/components/daemonset/Details.tsx
frontend/src/components/job/List.tsx
frontend/src/components/pod/Details.tsx
frontend/src/components/pod/List.tsx
frontend/src/components/statefulset/Details.tsx
frontend/src/components/workload/Details.tsx
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/cronJob.ts
frontend/src/lib/router.tsx

This PR adds more information to different workflow details views as well as a couple of bug fixes related to that.

Better info for workloads

---

backend/cmd/headlamp.go

Testing not done yet, this would be an opportunity to test with the recent oidc fixes on keycloak and dex as well

backend: Encode state in base64, use this rather than plain cluster name

---

backend/cmd/plugins.go

build headlamp on windows, then use a headlamp plugin
fixes #458

backend: Fix plugins path on windows

---

backend/cmd/headlamp.go

When running in the desktop, there is no big advantage to allowing the
plugins to be cached, and we have hit issues where the plugins were
being cached while the user is attempting to reload them (for
development). So this patch prevents that by adding a no-cache header
to the /plugins/ request responses.
It's complicated, since I haven't hit the cache issue 100% of the times.
I have noticed that it's easier to get it if you have Headlamp running for a while (dev version on WSL at least) and you start modifying the plugin (there are reloads but the plugins' contents aren't changed).
fixes #473

backend: Add no-cache header for plugins when running in desktop

---

plugins/examples/pod-counter/package.json
plugins/examples/pod-counter/tsconfig.json
plugins/examples/sidebar/.gitignore
plugins/examples/sidebar/README.md
plugins/examples/sidebar/jsconfig.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/examples/sidebar/src/index.tsx
plugins/examples/sidebar/tsconfig.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json
plugins/headlamp-plugin/template/tsconfig.json

* Bumps headlamp-plugin to 0.4.4 (already published).
* Updates pod-counter to use the above.
* Introduces a new sidebar-icons plugin.
Build the plugins, verify they're using the tsconfig.json as an extend.
Verify the plugins are shown in Headlamp when used.

Plugin changes

---

frontend/src/redux/stores/store.tsx

Fix integration with [redux devtools](https://github.com/reduxjs/redux-devtools).

Fix integration with redux devtools

---

charts/headlamp/templates/clusterrolebinding.yaml

Co-authored-by: S Santhosh Nagaraj <nssvlr@gmail.com>
Based on #374 .

helm chart: Support deploying the ServiceAccount in different namespaces

---

frontend/src/components/App/__snapshots__/TopBar.stories.storyshot
frontend/src/components/cluster/Chooser.tsx
frontend/src/plugin/registry.tsx
frontend/src/redux/actions/actions.tsx
frontend/src/redux/reducers/ui.tsx
plugins/examples/clusterchooserbuttonoverride/.gitignore
plugins/examples/clusterchooserbuttonoverride/README.md
plugins/examples/clusterchooserbuttonoverride/jsconfig.json
plugins/examples/clusterchooserbuttonoverride/package-lock.json
plugins/examples/clusterchooserbuttonoverride/package.json
plugins/examples/clusterchooserbuttonoverride/src/index.tsx
plugins/examples/clusterchooserbuttonoverride/tsconfig.json

we allow the flexibility to a plugin developer to change the chooser component and replace it with something they want to add.
Added an example plugin that has been tested with the current PR headlamp-plugin types build

Plugin: allow cluster chooser button overriding

---

plugins/examples/clusterchooserbuttonoverride/package-lock.json
plugins/examples/clusterchooserbuttonoverride/package.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/dynamic-clusters/package.json
plugins/examples/pod-counter/package.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

Bumping version numbers for headlamp-plugin 0.4.8.

headlamp-plugin 0.4.8

---

frontend/src/components/common/Terminal.tsx
frontend/src/lib/k8s/pod.ts

Main features:
* Tty window auto resize
* Add shell support for different containers (Windows & Linux)

Improve terminal user experience

---

Dockerfile
Makefile

Update to latest alpine image which has some security fixes.
- https://alpinelinux.org/posts/Alpine-3.15.1-released.html
- https://alpinelinux.org/posts/Alpine-3.15.2-released.html
- https://alpinelinux.org/posts/Alpine-3.12.11-3.13.9-3.14.5-3.15.3-released.html
- https://alpinelinux.org/posts/Alpine-3.12.12-3.13.10-3.14.6-3.15.4-released.html

Makefile Dockerfile: Bump alpine 3.15.4

---

frontend/src/components/common/SimpleTable.tsx
frontend/src/components/service/Details.tsx
frontend/src/components/service/List.tsx
frontend/src/i18n/locales/en/glossary.json
frontend/src/i18n/locales/es/glossary.json
frontend/src/i18n/locales/pt/glossary.json
frontend/src/lib/k8s/service.ts

- frontend: Add status to Service class
- frontend: Add external IP to the Service list/details views
fixes #521

Show external addresses for Service

---

frontend/package.json
frontend/src/plugin/index.ts
frontend/src/plugin/lib.ts
plugins/headlamp-plugin/config/webpack.config.js
plugins/headlamp-plugin/lib/additional.d.ts
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json
plugins/headlamp-plugin/template/src/headlamp-plugin.d.ts
plugins/headlamp-plugin/template/src/index.tsx
plugins/headlamp-plugin/test-plugins-examples.sh

So can import SVG as components like create react app does.
Also a plugin testing fix along with a new version of headlamp-plugin.

SVG fix, headlamp-plugin 0.4.9

---

app/electron/main.ts
app/electron/preload.ts
frontend/src/plugin/lib.ts
plugins/examples/app-menus/.gitignore
plugins/examples/app-menus/README.md
plugins/examples/app-menus/jsconfig.json
plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/app-menus/src/index.tsx
plugins/examples/app-menus/tsconfig.json

@illume , I have not touched the README of the app-menus plugin since it should be consistent with whatever new format you're going to land.
Testing:
- Run the app-menus plugin and see that it creates a new menu called "Chat with us".

Allow to override app menus from plugins

---

frontend/src/components/common/index.ts

Ran into issues while trying to access chart elements during plugin development

Update index.ts with Chart exports

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/k8s/token.ts

This patch adds logic to check if the token
is about to expire and refreshes it.
Signed-off-by: yolossn <nssvlr@gmail.com>

frontend: Add refresh token logic

---

app/electron/main.ts

We add a custom protocol that can be used as the redirect URI, this is because we want to allow users to use there default browser for auth rather than the electron chromium window. Right now we only allow microsoft login auth to open in the default browser.

Handle custom auth for desktop app

---

docs/development/plugins/functionality.md

docs: Fix cluster-chooser.png image path

---

plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/change-logo/package-lock.json
plugins/examples/change-logo/package.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/cluster-chooser/package.json
plugins/examples/details-view/package.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/dynamic-clusters/package.json
plugins/examples/pod-counter/package.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json

Without it, the plugins fail to run.

plugins/examples: Update headlamp-plugin for all example plugins

---

frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/crd.ts
frontend/src/lib/k8s/ingress.ts

Testing:
* For example the one at #609 .
fixes #609

Fix applying ingresses

---

frontend/src/components/crd/CustomResourceDetails.tsx
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/crd.ts
frontend/src/lib/k8s/index.test.ts
frontend/src/lib/k8s/storageClass.ts
frontend/src/lib/router.tsx

I have noticed that my pluralName PR's last changes introduced a bug in the routes. So this PR fixes that and adds a new test to check for the routes.

Fix routes

---

plugins/headlamp-plugin/package.json

Just bumps the version to 0.5.1

plugins/headlamp-plugin: Bump version to 0.5.1

---

frontend/src/components/common/LogViewer.tsx

We want to let the log view scroll to remain at the current viewing
point only and not scroll to the bottom of the log.
Go to the log viewer in pod detail view and you will see the logs show up without getting scrolled to the bottom

frontend: Don't scroll log viewer to the bottom

---

app/package.json

Add Debian package

---

frontend/src/components/common/AlertNotification.tsx

Was causing an error in the app.
Run the app.
Run the app, check the dev console.

frontend AlertNotification: Fix rule-of-hooks issues

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

Testing:
choco pack
choco install headlamp -d -v -s .

app: Bump Chocolatey's Headlamp version to 0.12.0

---

.github/workflows/app-artifacts-win.yml
app/package.json
app/windows/codesign.js
app/windows/sign.js

I will add instructions separately since this is an admin-only action.

app: Add Windows signing

---

plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/app-menus/src/headlamp-plugin.d.ts
plugins/examples/change-logo/package-lock.json
plugins/examples/change-logo/package.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/cluster-chooser/package.json
plugins/examples/cluster-chooser/src/headlamp-plugin.d.ts
plugins/examples/details-view/package-lock.json
plugins/examples/details-view/package.json
plugins/examples/dynamic-clusters/package.json
plugins/examples/dynamic-clusters/src/headlamp-plugin.d.ts
plugins/examples/pod-counter/package-lock.json
plugins/examples/pod-counter/package.json
plugins/examples/pod-counter/src/headlamp-plugin.d.ts
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/examples/sidebar/src/headlamp-plugin.d.ts

Upgrades the plugin examples.
- upgrade latest headlamp-plugin
- adds missing files and config
- npm audit fix
Plugins pass lint/tsc checks.

plugins/examples: upgrade plugins/examples

---

frontend/src/components/cluster/Chooser.tsx
frontend/src/components/cluster/ClusterChooser.tsx

Fixes: #654
Before:
After:
Before:
After:

frontend: Fix cluster button extending issue

---

frontend/src/components/role/BindingDetails.tsx
frontend/src/lib/router.tsx

Fixes: https://github.com/kinvolk/headlamp/issues/663

Add Link to reference objects from Role/ClusterRole details view

---

.github/workflows/docker-extension-release.yml

To Do:
Add docker creds to secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`

ci: Fix the trigger for docker extension gh action

---

frontend/src/components/common/Resource/ResourceTable.stories.tsx
frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/common/Resource/__snapshots__/ResourceTable.stories.storyshot
frontend/src/components/common/SimpleTable.stories.tsx
frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot
frontend/src/components/role/BindingList.tsx

Fix table filter

---

frontend/src/components/App/Notifications/index.tsx
frontend/src/lib/notification.tsx

Adds cluster name to each notification list item in the popup
Go to notification popup and you will find cluster name on each list item

Add cluster name to notification area

---

docker-extension/Dockerfile
docker-extension/metadata.json

docker-ext: Changes to pass extension validation

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/App/__snapshots__/VersionDialog.stories.storyshot
frontend/src/components/common/Chart.stories/__snapshots__/PercentageCircle.stories.storyshot
frontend/src/setupTests.ts

Dependency updates, based on npm audit report.

frontend: dependency updates

---

frontend/src/components/common/SectionFilterHeader.tsx
frontend/src/components/common/__snapshots__/SimpleTable.stories.storyshot

Before:
https://user-images.githubusercontent.com/22731013/196707719-c14c87de-b21b-488b-9653-d4ed74f7180e.mp4
After:
https://user-images.githubusercontent.com/22731013/196707641-e2089d51-3d93-4aec-a8c0-b7dcb1be3f6b.mp4

frontend: Fix unexpected scroll on filter change

---

.github/workflows/build-container.yml
e2e-tests/.gitignore
e2e-tests/README.md
e2e-tests/package-lock.json
e2e-tests/package.json
e2e-tests/playwright.config.ts
e2e-tests/tests/headlamp.spec.ts

e2e-tests: Add basic e2e test with playwright and minikube

---

Dockerfile

Update to latest alpine image which has some security fixes.
- https://alpinelinux.org/posts/Alpine-3.13.11-3.14.7-3.15.5-released.html
- https://alpinelinux.org/posts/Alpine-3.13.12-3.14.8-3.15.6-3.16.2-released.html

Makefile Dockerfile: Bump alpine 3.15.6

---

frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/i18n/locales/en/resource.json
frontend/src/i18n/locales/es/resource.json
frontend/src/i18n/locales/pt/resource.json

"Use minimal editor" was missing

little i18n fix

---

frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot

Since somehow we merged a commit that broke them.

frontend: Update the test snapshots

---

frontend/src/components/common/Resource/CreateButton.tsx
frontend/src/components/common/Resource/DocsViewer.tsx
frontend/src/components/common/Resource/EditorDialog.tsx
frontend/src/helpers/index.ts
frontend/src/index.tsx

This patch allows the editor to apply multiple resources at once and also shows docs for all the available resources
fixes #737 
fixes #712

Apply multiple resources at once 

---

frontend/src/components/common/ActionButton/ActionButton.tsx
frontend/src/components/common/LogViewer.tsx

This allows us to be more flexible when using the action button

Action button quick improvements

---

frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot

A snapshot file was not added into git.

frontend: Add missing PodLogs test snapshot

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

app: Bump Chocolatey version to Headlamp 0.14.1

---

charts/headlamp/Chart.yaml

charts: Bump Headlamp to 0.14.1

charts: Bump Headlamp to 0.14.1

---

backend/cmd/headlamp.go
backend/cmd/kubeconfig.go
frontend/src/components/App/Layout.tsx
frontend/src/components/App/RouteSwitcher.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/helpers/index.ts
frontend/src/lib/k8s/index.ts

Kubeconfig refresh

---

frontend/src/components/common/Resource/CreateButton.tsx

Go to the Editor Dialog and paste the following yaml which contains a v1/List resource 
https://gist.githubusercontent.com/ashu8912/d2e9e7e0c34309dbe26d0f3bac5960c7/raw/e983d2483f03fe2ff1a107bc417a007c4678d973/list.yaml
Press the apply button and see this getting applied

Apply v1/list resources

---

frontend/src/lib/util.ts

The NaN check was done in a wrong way  for useURLState, this PR fixes that

FIx a small issue with how we check for NaN values in useURLState

---

backend/cmd/headlamp.go
frontend/src/components/App/RouteSwitcher.tsx
frontend/src/components/Sidebar/SidebarItem.tsx
frontend/src/components/Sidebar/prepareRoutes.ts
frontend/src/components/common/Resource/PortForward.tsx
frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/portforward/index.tsx
frontend/src/components/service/Details.tsx
frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/router.tsx

Adds start portforward button to service details view

Add portforward to service

---

frontend/src/components/App/Notifications/__snapshots__/List.stories.storyshot
frontend/src/components/common/SimpleTable.stories.tsx
frontend/src/components/common/SimpleTable.tsx

This was missing after a story update.

frontend: Update Notifications' snapshot

---

frontend/src/components/crd/CustomResourceDefinition.stories.tsx
frontend/src/components/crd/CustomResourceDetails.stories.tsx
frontend/src/components/crd/Details.tsx
frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
frontend/src/components/crd/storyHelper.ts
frontend/src/test/index.tsx

This PR:
- Adds coverage for CRD list testing;
- Simplifies how the CRD objects are shown and enables testing them more easily (see examples)
- Simplifies the testing for CRD and CR objects
How to test:
Check out the `CRD` sections after running storybook.

Improve CustomResource and CustomResourceDefinition testing

---

frontend/src/components/App/settings/Settings.stories.tsx
frontend/src/components/App/settings/__snapshots__/Settings.stories.storyshot
frontend/src/components/App/settings/hook.tsx
frontend/src/components/App/settings/index.tsx
frontend/src/components/common/Resource/ResourceTable.stories.tsx
frontend/src/components/common/SimpleTable.stories.tsx
frontend/src/lib/util.ts
frontend/src/redux/actions/actions.tsx
frontend/src/redux/reducers/config.tsx
frontend/src/redux/reducers/ui.tsx
frontend/src/setupTests.ts

These changes move the settings entries to the config redux story.
More context in the commit messages.
A new story is also added.

Move settings in redux store

---

frontend/src/components/App/Notifications/List.stories.tsx
frontend/src/components/App/settings/__snapshots__/Settings.stories.storyshot

Fix settings and notifications snapshot

---

frontend/src/components/common/Resource/AuthVisible.tsx
frontend/src/components/common/Resource/EditButton.tsx
frontend/src/components/crd/__snapshots__/CustomResourceDefinition.stories.storyshot
frontend/src/components/crd/__snapshots__/CustomResourceDetails.stories.storyshot
frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot
frontend/src/components/endpoints/__snapshots__/EndpointDetails.stories.storyshot
frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot

The EditButton was never reaching its inner `AuthVisible` component.
How to test:
Follow the instructions at https://github.com/headlamp-k8s/headlamp/pull/870

Fix edit button visibility

---

docs/development/_index.md
docs/platforms.md

This should help people to get started by telling them the dependencies.

Getting started dependencies, and updated platforms doc to include browsers/OS

---

.github/workflows/container-publish.yml

This patch fixes the tags for manual trigger
of container publish action.
Signed-off-by: yolossn <sannagaraj@microsoft.com>

ci: Fix tags in container publish action

---

kubernetes-headlamp.yaml

Update the container image to be headlamp-k8s/headlamp

---

frontend/src/components/common/Resource/PortForward.tsx

frontend: Fix service resource checking for port forwarding

---

frontend/src/lib/k8s/cronJob.ts

For Issue #976
Added links to official Kubernetes API docs.

frontend KubeCronJob: Created documentation comments

---

frontend/src/components/common/ReleaseNotes/ReleaseNotes.tsx
frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.stories.tsx
frontend/src/components/common/ReleaseNotes/ReleaseNotesModal.tsx
frontend/src/components/common/ReleaseNotes/UpdatePopup.stories.tsx
frontend/src/components/common/ReleaseNotes/UpdatePopup.tsx
frontend/src/components/common/ReleaseNotes/__snapshots__/ReleaseNotesModal.stories.storyshot
frontend/src/components/common/ReleaseNotes/__snapshots__/UpdatePopup.stories.storyshot

For Issue #931
Change the GitHub owner from "kinvolk" to "headlamp-k8s".
Adds Release Notes Modal Story.

Release notes modal story

---

backend/cmd/headlamp.go

There are few bugs in externalproxy: 
* proxy-to will be removed from header by browser fetch method
* devMode should add Forward-To to AllowedHeaders
* r.URL.Path should set to empty

backend: Fix unable to fetch through externalproxy

---

app/electron/main.ts

How to test:
- Run the app in a Linux+ARM device: verify that the text is shown

Disable GPU on ARM Linux

---

app/package-lock.json
app/package.json

(Just so we keep this bump in the main branch too)

app: Bump version to 0.16.0

---

frontend/src/components/Sidebar/__snapshots__/Sidebar.stories.storyshot
frontend/src/components/Sidebar/prepareRoutes.ts
frontend/src/components/lease/Details.stories.tsx
frontend/src/components/lease/Details.tsx
frontend/src/components/lease/List.stories.tsx
frontend/src/components/lease/List.tsx
frontend/src/components/lease/__snapshots__/Details.stories.storyshot
frontend/src/components/lease/__snapshots__/List.stories.storyshot
frontend/src/components/lease/storyHelper.ts
frontend/src/components/limitRange/Details.stories.tsx
frontend/src/components/limitRange/Details.tsx
frontend/src/components/limitRange/List.stories.tsx
frontend/src/components/limitRange/List.tsx
frontend/src/components/limitRange/__snapshots__/Details.stories.storyshot
frontend/src/components/limitRange/__snapshots__/List.stories.storyshot
frontend/src/components/limitRange/storyHelper.ts
frontend/src/components/runtimeClass/Details.stories.tsx
frontend/src/components/runtimeClass/Details.tsx
frontend/src/components/runtimeClass/List.stories.tsx
frontend/src/components/runtimeClass/List.tsx
frontend/src/components/runtimeClass/__snapshots__/Details.stories.storyshot
frontend/src/components/runtimeClass/__snapshots__/List.stories.storyshot
frontend/src/components/runtimeClass/storyHelper.ts
frontend/src/lib/k8s/lease.ts
frontend/src/lib/k8s/limitRange.tsx
frontend/src/lib/k8s/runtime.ts
frontend/src/lib/router.tsx

This patch adds ```LimitRange```, ```Leases``` and ```ResourceClass``` sections which can be accessed from  ```Configuration``` menu in sidebar
Acceptance Criteria

Add new sections

---

backend/cmd/cluster.go
backend/cmd/headlamp.go
backend/cmd/kubeconfig.go

fixes:https://github.com/headlamp-k8s/headlamp/issues/961

backend: Use client-go to generate tls

---

docs/installation/desktop/linux-installation.md
docs/installation/desktop/mac-installation.md
docs/installation/desktop/win-installation.md

Windows was the one desperately needing an update, but the others also needed some care.

Installer docs

---

frontend/src/components/Sidebar/NavigationTabs.tsx

frontend: Don't show tabs that are meant to be hidden

---

frontend/src/components/Sidebar/__snapshots__/Sidebar.stories.storyshot
frontend/src/components/Sidebar/prepareRoutes.ts
frontend/src/components/networkpolicy/Details.tsx
frontend/src/components/networkpolicy/List.tsx
frontend/src/lib/k8s/index.ts
frontend/src/lib/k8s/networkpolicy.tsx
frontend/src/lib/router.tsx

Add network policy view

---

frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodList.stories.storyshot

continued on from https://github.com/headlamp-k8s/headlamp/pull/1058

frontend: Add more details in Pod list by @lijianzhi01

---

frontend/src/plugin/index.ts
frontend/src/plugin/updateSettingsPackages.test.ts

So we don't break with the previous behavior.

frontend: Enable plugins by default

---

Makefile
app/app-build-manifest.json
app/electron/main.ts
app/package-lock.json
app/package.json
app/scripts/setup-plugins.js
docs/development/_index.md

This PR allows us to easily bundle plugins and set up proxy-urls.

Bundle plugins

---

frontend/src/components/authchooser/index.tsx

Due to how the test-auth logic in the AuthChooser was designed, it
led to many requests to the API server, especially if the response
was not valid.
This is due to the clusters dependency in the related useEffect hook
being constantly changed. Even though this is worth an investigation
on its own, making sure these requests only happen when needed is
needed, so this patch ensures only one test auth request happens
unless the clusters are actually changed.
fixes #1100 
How to test:

frontend: Prevent multiple auth test requests at login

---

frontend/src/components/node/List.tsx

frontend: Add node version to node list

---

MAINTAINERS
MAINTAINERS.md

Updates MAINTAINER file to be in markdown and updates maintainer list.

Update MAINTAINER file

---

frontend/src/components/common/Resource/Resource.tsx

frontend: Fix how we get namespace for OwnedPodSection

---

frontend/src/components/Sidebar/Sidebar.stories.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/__snapshots__/Sidebar.stories.storyshot
frontend/src/redux/actions/actions.tsx
plugins/examples/sidebar/src/index.tsx

- frontend: Allow setting up sidebar as null when no sidebar is needed
- frontend: Refactor and add more cases to the sidebar stories

Fix always visible sidebar

---

frontend/src/components/horizontalPodAutoscaler/Details.tsx
frontend/src/components/horizontalPodAutoscaler/List.tsx
frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.stories.storyshot
frontend/src/components/podDisruptionBudget/Details.tsx
frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
frontend/src/components/resourceQuota/Details.tsx
frontend/src/components/resourceQuota/List.tsx
frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.stories.storyshot
frontend/src/lib/k8s/resourceQuota.ts
frontend/src/lib/util.ts

Cleaned https://github.com/headlamp-k8s/headlamp/pull/1050 and updated snapshots
Changes:
This PR contains following changes:
1. Fix more lable missing in HPA target
2. Remove duplicated HPA detail event table and add contdition table
3. Improve unit of request and limit in resource quota and make them human readable
4. Improve UX fro RQ and HPA
5. Fix null reference error in resource quota status

frontend: Improve HPA, PDB, Resource Quota

---

charts/headlamp/README.md

The badges were outdated and would have to be manually changed.

charts: Remove badges from README.md

---

backend/cmd/headlamp.go

#1156 #292 
A quick fix for the issue. Sorry for opening duplicated issue.

backend: Consider the base URL for OIDC-callback's redirect URL

---

docs/development/oidc.md
docs/installation/in-cluster/oidc.md

OIDC doc fix

---

frontend/src/components/common/Resource/ResourceTable.tsx

frontend: Fix namespace sorting

---

CODE_OF_CONDUCT.md

Update to CNCF Code of Conduct

---

docs/installation/in-cluster/_index.md

* Add information on how to install headlamp via helm
Closes #296

docs: Helm installation

---

.github/workflows/build-container.yml

The container test job started failing, and with this PR it's not.

github: build-container: Fix wait issue and add more logging

---

frontend/src/components/node/Details.tsx

frontend node/Details: Fix back link spacing on mobile

---

.gitignore
backend/cmd/headlamp.go
backend/cmd/plugins.go

docs:add headlamp & plugins & README_CN
fixes https://github.com/headlamp-k8s/headlamp/issues/930

docs:add headlamp & plugins

---

docs/contributing.md

docs: Add section about filing security bugs

---

frontend/src/components/priorityClass/Details.tsx
frontend/src/components/priorityClass/List.tsx
frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
frontend/src/components/priorityClass/__snapshots__/priorityClassList.stories.storyshot
frontend/src/components/priorityClass/priorityClassDetails.stories.tsx
frontend/src/components/priorityClass/priorityClassList.stories.tsx
frontend/src/lib/k8s/clusterRole.ts
frontend/src/lib/k8s/index.test.ts
frontend/src/lib/k8s/index.ts
frontend/src/lib/k8s/ingress.ts
frontend/src/lib/k8s/limitRange.tsx
frontend/src/lib/k8s/priorityClass.ts
frontend/src/lib/k8s/priorityClasses.ts
frontend/src/lib/k8s/runtime.ts
frontend/src/lib/k8s/storageClass.ts

This PR adds a few fixes to the k8s classes we have as ResourceClasses in Headlamp.
It also adds a new test to prevent related regressions. This new test checks whether certain classes 1. have the listRoute correctly set, 2. are namespaced or not; and 3. are being tested or not.
How to test:

Misc fixes to k8s classes to the ResourceClasses object and new tests

---

backend/pkg/kubeconfig/watcher_test.go

The backend test job is failing intermittently on CI.
As a side effect, it seems the job runs a bit quicker than before because it doesn't have to sleep as long now.
I restarted the "backend test job" several times and it worked every time.

backend: kubeconfig: Fix intermittent issue with TestWatchAndLoadFiles

---

frontend/src/components/App/Notifications/index.tsx
frontend/src/components/cluster/Overview.tsx
frontend/src/lib/k8s/apiProxy.ts
frontend/src/lib/k8s/cluster.ts
frontend/src/lib/k8s/event.ts

Event list optimization

---

backend/pkg/kubeconfig/kubeconfig.go

For in-cluster with OIDC auth mode the websockets were getting closed with a 502 error, this was happening due to the in-cluster OIDC conf being stored in the AuthProvider and the client-go rest package picked it up and expected the websockets to have a Bearer token.

backend: Fix websocket issue in-cluster + OIDC

---

frontend/src/components/pod/Details.tsx
frontend/src/components/pod/__snapshots__/PodDetails.stories.storyshot
frontend/src/components/pod/__snapshots__/PodLogs.stories.storyshot

These are:
* Tolerations;
* QoS Class
* Priority
* Service Account

Add more details to pods

---

frontend/src/components/common/Resource/MainInfoSection/MainInfoSection.tsx
frontend/src/components/cronjob/CronJobDetails.stories.tsx
frontend/src/components/cronjob/Details.tsx
frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot

Fix spawn button

---

frontend/src/components/common/Resource/DocsViewer.tsx
frontend/src/components/common/Resource/EditorDialog.tsx

We need to test this with the list of objects to be set.
**Update:** After @callmevladik clarified the issue (#1168 ) , I was able to reproduce and fix it.
fixes #1168

Fix editing resources without a resource version

---

plugins/README.md

Improve plugins/README.md with a Quickstart and better docs intro.

plugins: Improve README with a Quickstart and better docs intro

---

backend/cmd/headlamp.go

Otherwise the frontend gets the compressed data when it assumes it's JSON content.
This resulted in the app details (app-catalog) never being loaded, as it wanted JSON and was given compressed data. Maybe decompressing in the client would be better, but I am not sure if that's feasible.
How to test:
Run Headlamp with the app-catalog plugin and click on an app in the Apps page: it goes to the app's details and should stop loading and show the contents of that app.

backend: Decrompress data from external-proxy when needed

---

app/windows/chocolatey/choco-bump.sh
app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

- chocolatey choco-bump.sh: Fix typo in post-bump message
- chocolatey: Update to Headlamp 0.20.0

Update Chocolatey to Headlamp 0.20.0

---

frontend/src/lib/router.tsx

- frontend: Use MutatingWebhookConfigList for its route
- frontend: Add missing MutatingWebhookConfig details view to the router

Fix mutating webhook config list

---

plugins/headlamp-plugin/template/.vscode/extensions.json
plugins/headlamp-plugin/template/.vscode/settings.json
plugins/headlamp-plugin/template/.vscode/tasks.json

This includes some task runners for building and testing.
It also suggests some extensions (prettier and eslint).

headlamp-plugin: Add .vscode folder for vscode integration

---

plugins/examples/pod-counter/package-lock.json
plugins/examples/pod-counter/package.json
plugins/examples/pod-counter/src/Message.test.tsx

Run the test added in this PR.
```bash
cd plugins/examples/pod-counter/
npm i
npm run test
```

plugins/examples/pod-counter: Add react testing lib example

---

.github/workflows/pr-to-update-chart.yml

There's been a few times where we've forgotten to update the Headlamp version for its Helm Chart, so this PR aims at preventing that by opening the PR automatically.

Add action to open PR for updating chart automatically

---

README.md

A cncf sandbox requirement, see https://github.com/cncf/toc/issues/1056
It looks like this:
We have "passing" status. See below for requirements to get silver or gold:
- passing https://www.bestpractices.dev/en/projects/7551
- silver requirements https://www.bestpractices.dev/en/projects/7551?criteria_level=1
- gold requirements https://www.bestpractices.dev/en/projects/7551?criteria_level=2

README: Add openssf best practices badge

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/cronjob/Details.tsx
frontend/src/components/cronjob/__snapshots__/CronJobDetails.stories.storyshot

Fix cronjob details

---

app/app-build-manifest.json
app/package-lock.json
app/package.json

This is the release commits for the 0.21.0 version.

Add Prometheus plugin + bump version to 0.21.0

---

.github/workflows/pr-to-update-chart.yml

github: Fix update chart by adding the missing GH token env var

---

.github/workflows/backend-test.yml

this patch adds check for headlamp add
on to be up and running, adds cleanup
after first test to avoid failure on
subsequent run and removes unwanted
branch check.

github: Fix backend test action

---

frontend/src/components/portforward/index.tsx

This patch fixes the start portforward function
is not working issue in the portforward list
view.

frontend: Fix start portforward breaking in list view

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.21.0

---

frontend/package-lock.json
plugins/headlamp-plugin/package-lock.json

- frontend: headlamp-plugin: Update deps with npm audit fix

frontend: headlamp-plugin: Update dependencies with npm audit fix

---

frontend/src/lib/k8s/apiProxy.ts

If we call a function like "list" with the "limit" request param, that will work in the first call that the listing performs internally, but then it connects through a websocket (to stream any changes to that list), and from that point the limit is no longer respected. This means that a listing with a limit of X can get way more items as it remains streaming.
This patch fixes that by doing a client side limiting on the results coming from the streaming, guaranteeing that only the most recent X items are returned. If no limit has been set, then it behaves as previously (no limits are applied at all).
This fixes the case we found out where the UI gets very slow in the cluster overview when the cluster has loads of events getting fired, since our request for limiting the events to 2000 was …

frontend apiProxy: Add limitting to the streamResults function

---

frontend/src/components/common/SimpleTable.tsx

rontend SimpleTable: Show first/last page buttons in pagination

---

frontend/src/components/common/NameValueTable/NameValueTable.tsx
frontend/src/components/common/Resource/MatchExpressions.tsx
frontend/src/components/horizontalPodAutoscaler/HPADetails.stories.tsx
frontend/src/components/horizontalPodAutoscaler/HPAList.stories.tsx
frontend/src/components/horizontalPodAutoscaler/List.tsx
frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.stories.storyshot
frontend/src/components/ingress/Details.tsx
frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.stories.storyshot
frontend/src/components/podDisruptionBudget/pdbDetails.stories.tsx
frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.stories.storyshot
frontend/src/components/priorityClass/priorityClassDetails.stories.tsx
frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.stories.storyshot
frontend/src/components/resourceQuota/resourceQuotaDetails.stories.tsx
frontend/src/components/resourceQuota/resourceQuotaList.stories.tsx
frontend/src/components/webhookconfiguration/Details.tsx
frontend/src/lib/k8s/cluster.ts

Part of #1612
@illume Would you like to look into this?

frontend: Fix some console warnings

---

backend/cmd/headlamp.go
frontend/src/lib/k8s/apiProxy.ts

Refresh OIDC token if they are about to expire and use it.

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/configmap/Details.stories.tsx
frontend/src/components/configmap/Details.tsx
frontend/src/components/configmap/List.stories.tsx
frontend/src/components/configmap/__snapshots__/Details.stories.storyshot
frontend/src/components/configmap/__snapshots__/List.stories.storyshot
frontend/src/components/configmap/storyHelper.ts
frontend/src/components/secret/Details.stories.tsx
frontend/src/components/secret/Details.tsx
frontend/src/components/secret/List.stories.tsx
frontend/src/components/secret/__snapshots__/Details.stories.storyshot
frontend/src/components/secret/__snapshots__/List.stories.storyshot
frontend/src/components/secret/storyHelper.ts
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json

* add tests
* simlar look for secrets and confimaps
* secret add type to details view
secret:
configmap:

frontend: Use NameValueTable for ConfigMap and Secret

---

frontend/src/lib/k8s/apiProxy.ts

We need ot be able to specify the cluster so we can later call the
apiProxy related methods on any cluster instead of just the currently
set up one.
fixes #1472

frontend: Add the ability to specify the cluster in apiProxy methods

---

docs/development/testing.md
load-tests/scripts/create-deployments.js

Adds a load test for deployments up to 500
Also fixes typo for load test documents

load-tests: docs: Add create deployments load test

---

frontend/src/components/App/Notifications/notificationsSlice.test.ts
frontend/src/components/App/Notifications/notificationsSlice.ts

Fixes and adds test for issue 1684 where notification logic was not being checking for null array
Fixes issue #1684

frontend: Add fix and test for notifcations

---

charts/headlamp/Chart.yaml
charts/headlamp/README.md
charts/headlamp/templates/deployment.yaml
charts/headlamp/values.yaml

Add ability to use environment variables in helm chart

chart: Added ability to use environment variables

---

backend/pkg/plugins/plugins.go

this patch fixes the backend build
failure that occurred due import missing 
issue.

backend: Fix backend build fail

---

frontend/src/components/common/Resource/Resource.tsx
frontend/src/components/common/SectionFilterHeader.tsx
frontend/src/components/limitRange/List.tsx
frontend/src/components/namespace/Details.tsx
frontend/src/components/namespace/__snapshots__/NamespaceDetails.stories.storyshot
frontend/src/components/pod/List.tsx
frontend/src/components/resourceQuota/List.tsx

based on #1611 
From workflow perspective, it could be interesting to see ResourceQuotas and LimitRanges per Namespace. As they are mainly for all stuff inside the namespace.
What does anyone think?

frontend: Include LimitRange and ResourceQuota on Namespace Details

---

frontend/src/components/App/runCommand.ts

For https://github.com/headlamp-k8s/headlamp/issues/1744

frontend: runCommand: Disable unless env var is set

---

.github/workflows/build-container.yml
e2e-tests/tests/dynamicCluster.spec.ts
e2e-tests/tests/headlamp.spec.ts
e2e-tests/tests/headlampPage.ts
e2e-tests/tests/pluginSetting.spec.ts

This fixes bug for authentication test for headlamp.
Adds e2e tests for plugin settings.
Fixes: #1752

e2e-tests: Add more tests for plugins

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

app: Update Chocolatey Headlamp version to 0.23.0

---

backend/pkg/helm/release.go
backend/pkg/utils/utils.go

Refactored code in [headlamp/backend/pkg/helm/release.go](https://github.com/headlamp-k8s/headlamp/blob/main/backend/pkg/helm/release.go#L628) file.
backend: Refactor release.go UpgradeRelease to be shorter #1793
_Abstracted out repetitive parts, made the code shorter and more-readable._
backend: Refactor, Add returnResponse method for HTTP responses
_Abstracted out repetitive parts, made the code shorter and more-readable._

backend: Refactor backend/pkg/helm/release.go

---

frontend/.gitignore
frontend/package.json
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/template/.gitignore

This improves frontend linting time from about 13 seconds to 2.

frontend: plugins: Add cache option to lint

---

frontend/src/components/Sidebar/prepareRoutes.ts
frontend/src/components/workload/Overview.tsx

The PR fix the issue #1791 by ordering the workload elements by name.

Workload order fix issue 1791

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.23.1

---

.github/workflows/pr-to-update-minikube.yml

minikube contributor here, just updating the PR title to include the before version and matching the title to the rest of our automated dependency update PRs to assist when generating changelogs, thanks!

Update minikube PR title

---

frontend/src/components/cluster/__snapshots__/Overview.stories.storyshot
frontend/src/components/common/TileChart/TileChart.tsx
frontend/src/components/common/TileChart/__snapshots__/TileChart.stories.storyshot
frontend/src/components/node/Details.tsx
frontend/src/components/node/List.tsx
frontend/src/components/node/__snapshots__/List.stories.storyshot
frontend/src/components/node/storyHelper.ts
frontend/src/components/node/utils.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/lib/k8s/node.ts

improve node views

---

frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
frontend/src/lib/k8s/apiProxy.ts

A summary of things marked for fixing.
- Return types are missing in places.
- Some types are "any".
- No docs on some functions and interfaces.
- Async is missing on some functions that need to be marked as so.
- Some of the users of the functions are not handling errors.

frontend: apiProxy: Fix some types and add review comments

---

.github/workflows/pr-to-update-winget.yml

This PR introduces a GitHub Action to automate the creation of pull requests for the winget-pkgs clone, utilizing our existing `create-winget.js` script.
fixes #1631

winget: Add automated winget draft pr

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.23.2

---

docs/platforms.md

Co-authored-by: Joaquim Rocha <joaquim.rocha@microsoft.com>

docs: Update platforms.md to include Azure

---

frontend/src/components/statefulset/List.tsx

Based on #1999 . Tested and it works fine.

frontend statefulset/list: fix List view broken

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

Already tested and submitted to registry.

chocolatey: Bump Headlamp version to 0.24.0

---

charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/values.yaml

charts: Add example docs for ingress

---

charts/headlamp/values.schema.json
charts/headlamp/values.yaml

fix for helm chart ingress

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

I have tested it and also already published it.

chocolatey: Bump Headlamp version to 0.24.1

---

.github/workflows/app.yml
.github/workflows/backend-test.yml
.github/workflows/backend.yml
.github/workflows/build-container.yml
.github/workflows/frontend.yml
.github/workflows/helm-chart-lint-test.yml
.github/workflows/helm-chart-template-test.yml

So we can run our tests on the rc branches as well.

github: Adding rc- and testing-rc- branches to be tested

---

charts/headlamp/values.schema.json

k8s wanted it in a different way, earlier we were validating wrong input.
Fixes: #2113

charts: Fix imagePullSecrets in value schema

---

frontend/src/components/App/AppContainer.tsx
frontend/src/lib/themes.ts

Randomly noticed that reduced motion styles weren't applying, used GlobalStyles component instead

frontend: Fix reduced motion styles

---

frontend/src/lib/k8s/apiProxy.ts

Fixes https://github.com/headlamp-k8s/headlamp/issues/1834

Add authorization header only if token exists

---

app/electron/plugin-management.ts
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/plugin-management/plugin-management.js
plugins/headlamp-plugin/plugin-management/plugin-management.test.js

So release tar.gz files can be put on there.

app: plugins: Fix validateArchiveURL to support github/gitlab/bitbucket

---

app/scripts/setup-plugins.js

The new plugin structure is slightly different, so we add support for it in the setup-plugins.js script.

app setup-plugins.js: Add support for new plugin tarball structure

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

It wasn't used and was depending on a bunch of unsupported polyfills

frontend: plugins: Remove unused if-env package

---

docs/development/plugins/how-to.md
docs/installation/desktop/index.mdx
docs/installation/desktop/mac-installation.md
docs/installation/desktop/win-installation.md

Because it's better for people wanting to know how to use Headlamp today.

docs: Fix wording to explain how things are now

---

app/package-lock.json
app/package.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/cluster/ClusterChooser.tsx
frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
frontend/tsconfig.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

Typescript version is inconsistent across packages, and the one in the frontend/ is quite old
Having latest typescript version would help with some issues I'm having while refactoring apiProxy and KubeObject type

app: frontend: plugins: Update typescript version to 5.5.4 and typedoc

---

frontend/src/components/App/Home/RecentClusters.tsx
frontend/src/components/App/Settings/NumRowsInput.tsx
frontend/src/components/account/Auth.tsx
frontend/src/components/cluster/Chooser.tsx
frontend/src/components/cluster/ClusterChooserPopup.tsx
frontend/src/components/common/ConfirmDialog.tsx
frontend/src/components/common/Dialog.tsx
frontend/src/components/common/LogViewer.tsx
frontend/src/components/pod/Details.tsx

By Oleksandr Dubenko
This is needed for React 18.
- https://github.com/headlamp-k8s/headlamp/pull/2230

frontend: Fix some missing types

---

app/electron/main.ts

This patch improves the approach for capturing and using the shell environment vars, particularly for non-Windows platforms.
Platforms tested:
Related to: 
- https://github.com/headlamp-k8s/headlamp/issues/1716

app: Improve shell env capture for better cross-platform support

---

frontend/src/lib/themes.ts

frontend: Fix dark theme error colors to be lighter

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

Already published to the registry.

chocolatey: Bump Headlamp version to 0.25.1

---

docs/contributing.md

This is a good bookmark till we have the solution for the meeting link.

docs/contributing.md: Add section about the monthly call

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This library is required for material react table
Adding it explicitly to fix inconsistencies with package-lock
Needed for #2231

frontend: Explicitly add mui date pickers

---

frontend/src/lib/k8s/apiProxy/apiProxy.test.ts
frontend/src/lib/k8s/apiProxy/index.ts

frontend: Move apiProxy to a separate folder

---

backend/cmd/headlamp_test.go
backend/cmd/stateless_test.go

This increases code coverage for backend by adding unit tests for functions.

backend: Add tests

---

backend/cmd/headlamp.go

This change validates user-provided data.

backend: Validate path from user

---

ADOPTERS.md

New ADOPTERS file with EPAM + Virginia Tech, as agreed with their representatives.

Add adopters file

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/common/__snapshots__/ActionsNotifier.Some.stories.storyshot
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

Changelog: https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md#notistack301
Migration guide: https://notistack.com/migration

frontend: Upgrade notistack to 3.0.1

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

https://github.com/JohannesKlauss/react-hotkeys-hook/releases
- LogViewer, with ctrl+shift+f to see search dialog.

frontend: headlamp-plugin: Update react-hotkeys-hook to 4.5.1

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/k8s/api/v2/hooks.ts
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/

frontend: headlamp-plugin: Update typescript to 5.6.2

---

frontend/package-lock.json
frontend/package.json
frontend/public/mockServiceWorker.js
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

https://github.com/mswjs/msw/releases

frontend: headlamp-plugin: Upgrade msw to 2.4.9

---

charts/headlamp/README.md
charts/headlamp/templates/clusterrolebinding.yaml
charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/values.schema.json
charts/headlamp/values.yaml

This adds custom configuration of clusterRole. User can now modify the settings by changing the default value.

chart: Add change ClusterRole option

---

frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Error.stories.storyshot
frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Success.stories.storyshot
frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Warning.stories.storyshot
frontend/src/components/common/Label.tsx
frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.Default.stories.storyshot
frontend/src/components/job/JobList.stories.tsx
frontend/src/components/job/List.tsx
frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
frontend/src/components/namespace/__snapshots__/NamespaceDetails.Active.stories.storyshot
frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.Default.stories.storyshot
frontend/src/components/storage/__snapshots__/ClaimDetails.Base.stories.storyshot
frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
frontend/src/components/storage/__snapshots__/VolumeDetails.Base.stories.storyshot

Fixes #2389  
In 1.31 Job has a new "SuccessCriteriaMet" condition which would case a page crash.
This PR adds a check for known conditions.
Also fixed vertical alignment in the status label

frontend: Fix crashing due to unknown Job condition

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

This is left over from CRA, and not used now.

frontend: headlamp-plugin: Remove unused vfile

---

Dockerfile
Dockerfile.plugins

This change pins the alpine dependency by hash.

Dockerfile: Pin alpine by hash

---

frontend/src/components/common/Resource/Resource.tsx

This is in preparation for multi cluster.

frontend: ResourceLink: Add cluster param automatically

---

frontend/src/lib/k8s/cluster.ts

This is so clusters can be used instead of the single cluster
if multi clusters are being used.
By default it will just use the single cluster as before.

frontend: k8s/cluster: Add clusters field to ApiListOptions

---

app/package-lock.json
frontend/package-lock.json
plugins/headlamp-plugin/package-lock.json

- frontend/
- app/
- plugins/headlamp-plugin/

frontend: Fix deps with npm audit fix

---

frontend/src/components/common/Resource/ResourceTable.tsx

This only uses the new cluster column on the resource table in multi cluster mode.

frontend: ResourceTable: Add cluster column

---

frontend/src/lib/k8s/api/v1/apply.ts

frontend: allow apply with update permissions

---

frontend/src/components/common/Resource/CreateButton.tsx
frontend/src/lib/k8s/index.ts

Update cluster on change in create button

---

frontend/src/components/pod/List.tsx
frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot

frontend: Fix Pod status label icon alignment

---

frontend/src/lib/util.ts

This was causing a crash sometimes.

frontend: util filterFunc: Fix for when item is null

---

frontend/src/lib/k8s/KubeObject.ts

So this uses the cluster group when it's there.

frontend: cluster: Fix useCluster to use the cluster group

---

frontend/src/lib/k8s/api/v2/hooks.ts

This fixes a bug where the cluster being sent in is not being passed along to lower level functions.

frontend: hooks: Fix some hooks to pass through cluster

---

frontend/src/lib/k8s/index.ts

frontend Home: Refresh clusters versions/errors on interval

---

frontend/src/components/resourceMap/graph/graphFiltering.test.ts
frontend/src/components/resourceMap/graph/graphFiltering.ts
frontend/src/components/resourceMap/graph/graphGrouping.test.ts
frontend/src/components/resourceMap/graph/graphGrouping.tsx
frontend/src/components/resourceMap/graph/graphModel.tsx
frontend/src/components/resourceMap/nodes/KubeObjectStatus.tsx

Create the base graph model and basic operations like grouping and filtering for the resource map
Part of https://github.com/headlamp-k8s/headlamp/issues/198 and https://github.com/headlamp-k8s/headlamp/pull/2225

frontend: Add graph model, grouping and filtering

---

frontend/src/components/resourceMap/useQueryParamsState.tsx

This hooks is needed for the map
https://github.com/headlamp-k8s/headlamp/pull/2225
https://github.com/headlamp-k8s/headlamp/issues/198

frontend: Add useQueryParamsState hook

---

frontend/src/lib/k8s/KubeObject.ts

Fixes #2500
apiEndpoint.scale was missing in Deployment/ReplicaSet/StatefulSet because factory that handles multiple endpoints doesn't create scale API.
Getter was passing array in every case, even the length was 1, but that resulted in multipleApiFactory always being called (the one that doesn't handle scale api)

frontend KubeObject: Fix missing scale api in apiEndpoint getter

---

frontend/src/lib/k8s/api/v1/apiProxy.test.ts
frontend/src/lib/k8s/api/v1/clusterApi.ts

Stop a cluster that was working, and this should give an alert error.

frontend: clusterApi: Fix testClusterHealth for multi cluster

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

Already tested and submitted to chocolatey.

chocolatey: Bump Headlamp version to 0.26.0

---

frontend/src/components/App/Settings/Settings.tsx
frontend/src/components/App/Settings/ThemeChangeButton.tsx
frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
frontend/src/components/common/TimezoneSelect/TimezoneSelect.tsx
frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
frontend/src/i18n/LocaleSelect/__snapshots__/LocaleSelect.Initial.stories.storyshot

* let general settings looks similar to cluster settings

frontend: cleanup general settings

---

frontend/src/components/resourceMap/details/GraphNodeDetails.tsx

frontend Map: Fix border on the side details panel

---

frontend/src/components/common/Resource/DeleteMultipleButton.tsx
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/fr/translation.json
frontend/src/i18n/locales/pt/translation.json
frontend/src/i18n/locales/zh-tw/translation.json

frontend DeleteMultipleButton: Fix typo in bulk deletion

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

Already tested and pushed to Chocolatey.

app: Bump Chocolatey to Headlamp 0.27.0

---

charts/headlamp/README.md

- Add a more detailed introduction with key features.
- Add a Prerequisites section.
- Improve installation instructions with common configurations.
- Add a Quick Start Guide with examples.
- Better organization of configuration tables with grouping.
Signed-off-by: Kautilya Tripathi <ktripathi@microsoft.com>

charts: Reorganize and Enhance the Structure

---

backend/cmd/multiplexer.go
backend/cmd/multiplexer_test.go

The WSConnLock struct now provides a robust wrapper around WebSocket connections, ensuring thread-safe write operations while maintaining efficient read access. This helps prevent race conditions in concurrent WebSocket operations throughout the multiplexer.
Thanks to @farodin91 for the help and wrapper code.
- Create 50 clusters using our load testing script. (Note this will be resource consuming)
```bash
cd load-tests
npm i
node scripts/create-clusters.js 50 0
```
- Start the frontend `cd frontend && npm i && npm start`
- Start the backend `cd backend && go run ./cmd -dev -enable-dynamic-clusters`
- Go to any cluster backend should not panic and stop

backend: enhance WSConnLock with thread-safety

---

docs/installation/desktop/linux-installation.md
docs/platforms.md

And link from platforms.
After https://github.com/headlamp-k8s/headlamp/pull/2762#issuecomment-2605294175 .

docs: Add section on running external tools in flatpak to installation

---

frontend/.storybook/baseMocks.ts
frontend/src/components/gateway/ClassDetails.stories.tsx
frontend/src/components/gateway/ClassList.stories.tsx
frontend/src/components/gateway/GRPCRouteDetails.stories.tsx
frontend/src/components/gateway/GatewayDetails.stories.tsx
frontend/src/components/gateway/GatewayList.stories.tsx
frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
frontend/src/components/gateway/__snapshots__/ClassDetails.Basic.stories.storyshot
frontend/src/lib/k8s/api/v2/hooks.ts
frontend/src/lib/k8s/api/v2/useKubeObjectList.ts

This is the smallest change that can fix the https://github.com/headlamp-k8s/headlamp/issues/2738 
There are other areas where error handling is not the best or not working at all and will be handled in a separate PR
Opened an issue for it here https://github.com/headlamp-k8s/headlamp/issues/2767

frontend: Quick fix for a case when no endpoints are available for the resource

---

Dockerfile
Dockerfile.plugins

This fixes some CVEs mentioned on the artifact hub helm chart page for headlamp.

Dockerfile: Update alpine to 3.20.4

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.28.0

---

plugins/headlamp-plugin/template/package.json

Just a quick change since 0.0.1 is not really a good 1st version.

headlamp-plugin: Change the version for the template's package.json

---

charts/headlamp/templates/service.yaml
charts/headlamp/values.schema.json
charts/headlamp/values.yaml

Adds more exposure options for plain services, hope it's okay i did not go all out on the schema validation for the IPs

feat(helm): add extended service values

---

frontend/src/components/common/NamespacesAutocomplete.tsx

Fixes #1522
Adds a hooks that will to try fallback to a default namespace (if any set in the kubeconfig) when we failed to load namespaces
Testing done:
configured default namespace in the kubeconfig and tried using service account that has access only to pods in default namespace

frontend: Fallback to default namespace found in the kubeconfig when all namespaces fail to load

---

charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/extra-manifests.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml
charts/headlamp/values.schema.json

helm charts installation was failing used to missing "," in schema

charts: Fix value.schema.json

---

frontend/src/components/common/Resource/RestartButton.stories.tsx
frontend/src/components/common/Resource/ScaleButton.stories.tsx
frontend/src/components/common/Resource/__snapshots__/RestartButton.DeploymentExample.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/RestartButton.StatefulSetExample.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/ScaleButton.DeploymentExample.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/ScaleButton.ReplicaSetExample.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/ScaleButton.StatefulSetExample.stories.storyshot

Added Storybook for Below component files
1. `Resource/ScaleButton.tsx`
2. `Resource/RestartButton.tsx`
[Screencast from 2025-02-04 18-39-32.webm](https://github.com/user-attachments/assets/b3591c35-ad81-493c-a02d-c57faa54d41a)
[Screencast from 2025-02-04 19-02-45.webm](https://github.com/user-attachments/assets/08e12850-c4f8-4ab2-9e86-52b46880becd)

frontend: ScaleButton and RestartButton: Storybook added

---

frontend/src/components/networkpolicy/NextworkPolicy.stories.tsx
frontend/src/components/networkpolicy/__snapshots__/NextworkPolicy.Default.stories.storyshot

Adding storybooks for NetworkPolicyList and its snapshots
[Screencast from 2025-02-02 02-17-10.webm](https://github.com/user-attachments/assets/088d79c1-246b-4339-9f55-70bbe84c2430)

Frontend: NetworkPolicyList Story added

---

frontend/src/components/common/BackLink/BackLink.stories.tsx
frontend/src/components/common/BackLink/__snapshots__/BackLink.CustomLink.stories.storyshot
frontend/src/components/common/BackLink/__snapshots__/BackLink.Default.stories.storyshot

Adding storybooks for BackLink component.
[Screencast from 2025-02-01 21-43-32.webm](https://github.com/user-attachments/assets/3d0ccb25-a7c6-469f-a085-4d404e7881ed)

Frontend: BackLink: StoryBooks and its snapshots added

---

frontend/src/lib/cluster.test.ts
frontend/src/lib/cluster.ts
frontend/src/lib/units.test.ts

Added unit tests for below files:
1. `lib/units.ts`
2. `lib/cluster.ts`

frontend: added tests for lib/units.ts and lib/cluster.ts files

---

frontend/src/components/deployments/List.stories.tsx
frontend/src/components/deployments/__snapshots__/List.Deployments.stories.storyshot

frontend: Add story for `Deployments`

---

frontend/src/components/oidcauth/OauthPopup.stories.tsx
frontend/src/components/oidcauth/__snapshots__/OauthPopup.Default.stories.storyshot
frontend/src/components/oidcauth/__snapshots__/OauthPopup.WithDimensions.stories.storyshot

Adding OauthPopup component stories and snapshots
[Screencast from 2025-02-02 20-07-00.webm](https://github.com/user-attachments/assets/824e8116-918b-422b-b447-d3c95ac7b0cb)

frontend: OauthPopup: Added stories

---

frontend/src/components/common/Resource/MatchExpressions.stories.tsx
frontend/src/components/common/Resource/__snapshots__/MatchExpressions.Default.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/MatchExpressions.WithExpressions.stories.storyshot

Adds storybooks for MatchExpressions component.
[Screencast from 2025-02-05 23-28-31.webm](https://github.com/user-attachments/assets/9b9f4596-5d01-4b84-a174-0124cc2d9d02)

frontend: MatchExpressions: Add storybook

---

frontend/src/components/networkpolicy/__snapshots__/NextworkPolicy.Default.stories.storyshot

This fixes main frontend/tests CI job.
(There was some merge issue, and the main branch forntend/tests CI job is failing on main.)

frontend: NextworkPolicy: Fix story snapshot issue

---

frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx

`App/PluginSettingsDetail.tsx` file was having a pending ToDo for error handling resolved that do by adding a catch block and setting up a notification system in it.

frontend: PluginSettingsDetail: ToDo completed

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.28.1

---

frontend/src/components/common/Resource/DocsViewer.stories.tsx
frontend/src/components/common/Resource/DocsViewer.tsx
frontend/src/components/common/Resource/__snapshots__/DocsViewer.CommentOnlyDocumentation.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/DocsViewer.ErrorDocumentation.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/DocsViewer.IncompleteDocumentation.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/DocsViewer.TypicalDocumentation.stories.storyshot

Fixes #2869 
https://github.com/user-attachments/assets/4d6c517c-76bd-4abe-a727-007c20a6e03e

frontend: Add story for `DocsViewer` component

---

.github/workflows/pr-to-update-choco.yml

Tested already from branch and it works.

github: Chocolatey needs to be updated always on the main branch

---

frontend/src/components/common/Resource/CreateButton.stories.tsx
frontend/src/components/common/Resource/__snapshots__/CreateButton.Default.stories.storyshot
frontend/src/components/common/Resource/__snapshots__/CreateButton.NarrowButton.stories.storyshot

Adds storybook and its snapshots for the CreateButton component.
[Screencast from 2025-02-08 13-53-26.webm](https://github.com/user-attachments/assets/3069c5cf-09f8-4b5e-9d99-2cdcb48d2afb)

frontend: CreateButton: Add Storybook

---

eslint-config/package-lock.json
eslint-config/package.json

This change updates cross-spawn to the desired 7.0.6 version.

eslint-config: Update cross-spawn to 7.0.6

---

app/.gitignore
app/electron/main.ts
app/electron/runCmd.ts
app/package.json

Move functionality for this feature into its own module.

app: runCmd: Extract handleRunCommand functionality from main.ts

---

Makefile
docs/development/index.md

docs: document running the app while backend, frontend are running externally

---

frontend/src/components/common/TimezoneSelect/TimezoneSelect.stories.tsx
frontend/src/components/common/TimezoneSelect/__snapshots__/TimezoneSelect.Default.stories.storyshot
frontend/src/components/common/TimezoneSelect/__snapshots__/TimezoneSelect.NoInitialValue.stories.storyshot

Adds Storybooks for `TimeZoneSelect` component
[Screencast from 2025-02-15 01-36-34.webm](https://github.com/user-attachments/assets/92627f0c-b97c-49d3-a8cf-435a6f354590)

frontend: TimeZoneSelect: Add Storybooks

---

frontend/src/lib/k8s/cronJob.ts

frontend: remove obsolete API call for CronJobs

---

frontend/src/redux/actionButtonsSlice.test.ts
frontend/src/redux/configSlice.test.ts
frontend/src/redux/overviewChartsSlice.test.ts

Adds units tests for redux slices:
1. actionButtonSlice
2. configSlice
3. overciewChartsSlice
All existing and newly added tests are running perfectly

frontend: redux: add unit tests

---

frontend/package-lock.json
frontend/package.json
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

These changes update dependencies in frontend and headlamp-plugin to the desired versions, addressing vulnerabilities.

frontend: headlamp-plugin: Update dependencies

---

frontend/src/lib/docs.test.ts

frontend: Add tests for `docs.ts`

---

Makefile
app/electron/main.ts
app/scripts/start.js
backend/cmd/headlamp.go
backend/cmd/server.go
backend/pkg/config/config.go
backend/pkg/config/config_test.go

backend: Add app mode flag to fix network exposure

---

Dockerfile.plugins

To verify the sha...
```
docker pull alpine:3.20.5
docker inspect --format='{{index .RepoDigests 0}}' alpine:3.20.5
```

Dockerfile: Update alpine to 3.20.5

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.29.0

---

app/scripts/push-release-assets/package.json
app/scripts/push-release-assets/push-release-assets.js

There were issues related to trying to import an ESM package using require (ERR_REQUIRE_ESM).

app/scrips/push-release-assets: Fix running the script

---

.github/workflows/build-container.yml
e2e-tests/kubernetes-headlamp-ci.yaml
e2e-tests/tests/dynamicCluster.spec.ts
e2e-tests/tests/headlamp.spec.ts
e2e-tests/tests/headlampPage.ts
e2e-tests/tests/multiCluster.spec.ts
e2e-tests/tests/namespaces.spec.ts
e2e-tests/tests/namespacesPage.ts
e2e-tests/tests/pluginSetting.spec.ts
e2e-tests/tests/podsPage.spec.ts
e2e-tests/tests/podsPage.ts

Fixes #2460 
Once this gets merged, #2831 can also be unblocked.

frontend: Add e2e-tests for multiple clusters

---

.github/workflows/push-release-assets.yml
app/scripts/push-release-assets/push-release-assets.js

Got to test the action and had to fix many things. There's also a commit for fixing the push-release-assets.js script.

Simplify push release assets

---

plugins/examples/update-deps.sh

This new script updates the deps for plugins using npm audit fix + adds the latest version of the @kinvolk/headlamp-plugin to the plugins that use it.

plugin/examples: Add update script

---

plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/change-logo/package-lock.json
plugins/examples/change-logo/package.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/cluster-chooser/package.json
plugins/examples/details-view/package-lock.json
plugins/examples/details-view/package.json
plugins/examples/dynamic-clusters/package-lock.json
plugins/examples/dynamic-clusters/package.json
plugins/examples/headlamp-events/package-lock.json
plugins/examples/headlamp-events/package.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/pod-counter/package.json
plugins/examples/resource-charts/package-lock.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/examples/tables/package-lock.json
plugins/examples/tables/package.json

This is the result of running the script to update the example plugins deps from the https://github.com/headlamp-k8s/headlamp/pull/2964 branch.

Update plugins deps

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
OWNERS
OWNERS_ALIASES
README.md
SECURITY_CONTACTS
code-of-conduct.md

This branch adds/edits a few files related to the format that Kubernetes projects use.
File templates at https://github.com/kubernetes/kubernetes-template-project

Add root files for SIG UI alignment

---

frontend/src/helpers/index.ts

frontend: Disable multiplexer due to an issue

---

frontend/src/components/common/Link.tsx
frontend/src/components/common/Resource/DetailsDrawer.tsx
frontend/src/components/crd/CustomResourceDetails.stories.tsx
frontend/src/components/crd/CustomResourceDetails.tsx
frontend/src/components/crd/Details.tsx
frontend/src/components/crd/__snapshots__/CustomResourceDetails.ErrorGettingCR.stories.storyshot
frontend/src/components/crd/__snapshots__/CustomResourceDetails.ErrorGettingCRD.stories.storyshot
frontend/src/components/resourceMap/details/KubeNodeDetails.tsx
frontend/src/redux/drawerModeSlice.ts

Adds support for the CR and CRD in drawer

frontend: Open Custom Resources and Custom Resource Definition in a drawer

---

docs/development/plugins/publishing.md

They should be .yml not .yaml.

docs: publishing: Fix extensions for yml files

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

- **headlamp-plugin: Update dependencies with audit fix**
- **headlamp-plugin: Bump to version 0.11.2**

headlamp-plugin: Update dependencies with audit fix

---

Dockerfile
Dockerfile.plugins

To fix some reported security issues in older version.

Dockerfile: Update to alpine:3.20.6

---

plugins/headlamp-plugin/bin/headlamp-plugin.js

This is needed for adding extra dist files like the wasm file for the IG plugin.
cc/ @ashu8912 
Used like: 
```
{
"name": "my-headlamp-plugin",
"version": "1.0.0",
"headlamp": {
"extraDist": {
"configs/defaults.json": "./src/configs/defaults.json",
"assets/": "./assets/",
"README.md": "./README.md"
}
}
}
```

headlamp-plugin: Allow to copy extra dist files into dist folder

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.30.0

---

frontend/src/components/Sidebar/useSidebarItems.ts

This change updates the sidebar item dependency list to reflect locale changes in the UI.
Fixes: #3088

frontend: Update sidebar when locale changes

---

docs/development/plugins/how-to.md

This fixes some broken links in the document

docs: Fix links refs

---

app/windows/codesign.js
frontend/src/make-env.test.js
plugins/headlamp-plugin/bin/headlamp-plugin.js
plugins/headlamp-plugin/test-headlamp-plugin.js

This change prevents the shell from interpreting special characters in the arguments.
Follow-up from #3020

app: frontend: plugins: Modify exec and run commands

---

plugins/examples/ui-panels/src/index.tsx

another fix for e2e a11y tests

plugins: examples: ui-panels: add aria-label attributes for improved accessibility

---

charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml

Current ci test is failing, ran `make helm-template-test` to update the snapshot

frontend: Update helm test snapshot

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

headlamp-plugin: 0.12.0-alpha.1

---

plugins/headlamp-plugin/config/vite.config.mjs

Fixes #3291
- See issue for reproducer, build on windows with cmd.

headlamp-plugin: Fix windows path issue with node polyfill

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

headlamp-plugin: 0.12.0-alpha.2

---

frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot

CI tests failing after themes got merged

frontend: Update Settings snapshot

---

README.md

So people might discover plugins more easily.

README: Add links to plugin repo and artifact hub

---

docs/installation/in-cluster/aks-cluster-oauth/index.md

Added guide for AKS cluster using Entra Login and Entra RBAC with OAuthProxy2
Fixes :- #3209
Attached Screenshot for reference:-

docs: Add guide for AKS cluster using Entra Login and Entra RBAC with OauthProxy2

---

plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

headlamp-plugin: 0.12.0

---

SECURITY.md

This change adds security policy specific text in the SECURITY file to meet the desired specification.

SECURITY.md: Add security policy specific text

---

frontend/src/components/deployments/List.tsx
frontend/src/components/endpoints/Details.tsx
frontend/src/components/resourceMap/GraphRenderer.tsx
frontend/src/components/resourceMap/GraphView.tsx
frontend/src/components/resourceMap/KubeObjectGlance/DeploymentGlance.tsx
frontend/src/components/resourceMap/KubeObjectGlance/EndpointsGlance.tsx
frontend/src/components/resourceMap/KubeObjectGlance/PodGlance.tsx
frontend/src/components/resourceMap/KubeObjectGlance/ReplicaSetGlance.tsx
frontend/src/components/resourceMap/KubeObjectGlance/ServiceGlance.tsx
frontend/src/components/resourceMap/details/GraphNodeDetails.tsx

in this PR  i have refactored ``/common`` imports to their direct address. 
However there any many other ``/common`` imports that are still there i will make further commits.

frontend: common: Refactoring common/ imports in frontend directory

---

backend/pkg/portforward/handler_test.go

Addressed Function Length Issue:
Refactored TestStartPortForward to reduce statement count (from 97 to well below the 40 limit)
Removed the //nolint:funlen comment as it's no longer needed
Created Helper Functions for Test Segments:
testStartPortForward: Starts port forwarding
testVerifyPortForward: Verifies connection works
testStopPortForward: Tests stopping functionality
testListPortForwards: Tests listing port forwards
testGetPortForwardByID: Tests retrieving specific port forward
testDeletePortForward: Tests deletion functionality
Added Utility Helper Functions:
Created findPodWithPort: Extracts pod selection logic
Created makeJSONRequest: Simplifies JSON request creation
Fixes: #3280

backend: Refactor portforward/handler_test.go TestStartPortForward 

---

frontend/src/components/workload/Charts.stories.tsx
frontend/src/components/workload/Charts.tsx
frontend/src/components/workload/Overview.stories.tsx
frontend/src/components/workload/__snapshots__/Charts.AllFailedDeployment.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.AllFailedStatefulSet.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.AllRunningDeployment.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.AllRunningStatefulSet.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.DefaultDeployment.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.DefaultStatefulSet.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.Empty.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.LoadingWorkload.stories.storyshot
frontend/src/components/workload/__snapshots__/Charts.MixedWorkloads.stories.storyshot
frontend/src/components/workload/__snapshots__/Overview.Workloads.stories.storyshot

Add Storybook for `workload/Overview.tsx` and `workload/Charts.tsx`.
<details>
<summary>workload/Overview.tsx</summary>
</details>
<details>
<summary>workload/Charts.tsx</summary>
1. Default 
2. Loading 
3. All Running
4. All Failed
5. Mixed
6. Empty
</details>

frontend: Overview and Charts: Storybook added

---

frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
frontend/src/i18n/ThemeProviderNexti18n.tsx

Documented the props, return types, and functionality using TSDoc to improve developer understanding and maintainability.
---
This PR adds TSDoc comments to the `LocaleSelect.tsx` and `ThemeProviderNexti18n.tsx` component to improve code readability and maintainability. The documentation includes descriptions for props, return types, and internal logic.
Adding proper documentation helps:
* Other developers understand the purpose and usage of the component
* Improve editor/IDE autocomplete and type inference
* Reduce onboarding time for new contributors
* Encourage consistent documentation practices
* All exported types and functions in `LocaleSelect.tsx` and `ThemeProviderNexti18n.tsx` 
* Inline comments where clarification is helpful
* No functional or behavioral changes were made.
* …

frontend: docs: Add TSDoc comments for component and helpers

---

frontend/src/components/common/EmptyContent.stories.tsx
frontend/src/components/common/Loader.stories.tsx
frontend/src/components/common/Loader.test.tsx
frontend/src/components/common/Loader.tsx
frontend/src/components/common/SectionHeader.stories.tsx
frontend/src/components/common/SectionHeader.tsx
frontend/src/components/common/__snapshots__/EmptyContent.Default.stories.storyshot
frontend/src/components/common/__snapshots__/EmptyContent.Empty.stories.storyshot
frontend/src/components/common/__snapshots__/EmptyContent.WithCustomColor.stories.storyshot
frontend/src/components/common/__snapshots__/EmptyContent.WithMultipleChildren.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.CustomColor.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.CustomSize.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.DefaultWithContainer.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.InlineNoContainer.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.InsideAComponent.stories.storyshot
frontend/src/components/common/__snapshots__/Loader.NoTitleProvided.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.LabelStyle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.LongTitle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.MainStyle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.NoActionsOrSubtitle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.NormalStyle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.SubSectionStyle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.WithActions.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.WithNoPadding.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.WithReactNodeAsTitle.stories.storyshot
frontend/src/components/common/__snapshots__/SectionHeader.WithTitleSideActions.stories.storyshot

- Refactored loader.tsx for better structure and maintainability
- Improved loader.stories.tsx to showcase various loader states in Storybook
- Enhancements aimed at better developer experience and component reusability

frontend: improve Loader component and update Storybook examples

---

frontend/src/components/service/ServiceList.stories.tsx
frontend/src/components/service/__snapshots__/ServiceList.Default.stories.storyshot
frontend/src/components/service/__snapshots__/ServiceList.Items.stories.storyshot

This PR adds new story for ``Service/List`` component. 
Here i have added mocking to show ``service`` in a list.

frontend: storybook: Added new story for Service/List

---

frontend/src/lib/themes.test.ts

Added test for the file
`themes.ts`

frontend: lib/themes.ts: Add test for getThemeName

---

frontend/src/components/service/ServiceDetails.stories.tsx
frontend/src/components/service/__snapshots__/ServiceDetails.Default.stories.storyshot
frontend/src/components/service/__snapshots__/ServiceDetails.Error.stories.storyshot

This PR adds new story for service/Details with test case :
Default: In which it will show ``Serviceinfo`` , ``ports`` , ``endpoints``
Error: Will show error message if the API endpoint is wrong.

frontend: ServiceDetails: Adding story for Details

---

frontend/src/components/resourceMap/graphViewSlice.tsx
frontend/src/redux/reducers/reducers.tsx
frontend/src/redux/uiSlice.ts

This is just for consistency with the other slices.

frontend: redux: Fix slices to export reducers for consistency

---

frontend/src/lib/auth.test.ts

Added tests for the file
`auth.ts`

frontend: lib/auth.ts: Add tests for getToken

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.31.0

---

docs/installation/desktop/index.mdx

So we can link to it when users run into this issue.

Add notice about apps not being signed

---

.github/pull_request_template.md

Add pull request template to standardize PR descriptions and improve the review process.
Fixes #3409 
- Add `.github/pull_request_template.md` with standard sections for summary, changes, testing, and issue references

Templates: Add a pull request template

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.32.0

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/advancedSearch/utils/searchWithQuery.tsx
plugins/headlamp-plugin/package-lock.json
plugins/headlamp-plugin/package.json

Uses safe parsing and evaluation of expressions for the advanced search

frontend: Use simple-eval for advanced search

---

frontend/src/components/common/AlertNotification.stories.tsx
frontend/src/components/common/__snapshots__/AlertNotification.ErrorOnCheck.stories.storyshot
frontend/src/components/common/__snapshots__/AlertNotification.NoErrorInitially.stories.storyshot
frontend/src/components/common/__snapshots__/AlertNotification.OnExcludedRoute.stories.storyshot
frontend/src/components/common/__snapshots__/AlertNotification.OnNonClusterRoute.stories.storyshot
frontend/src/components/common/__snapshots__/AlertNotification.SimulatingOffline.stories.storyshot

Updated the Storybook for AlertNotification and created new stories.

frontend: AlertNotification: Update Storybook with new stories

---

frontend/src/components/common/Resource/MetadataDisplay.tsx
frontend/src/components/common/SectionHeader.tsx

This PR fixes bug by removing to react key warnings.
Fixes #ISSUE_NUMBER  
- Added/Updated [component/file/logic]
- Fixed [bug/issue/typo]
- Refactored [code/module] for clarity/performance
1. [Step 1: e.g., Navigate to ...]
2. [Step 2: Click on ...]
3. [Step 3: Observe behavior or check logs/output]

frontend: fix two key react warnings

---

.gitignore
backend/.air.toml

This PR fixes the air file argument passing. Updated the air file with the latest configuration, the previous air file failing at the time of argument passing, and the env config ..
Fixes #ISSUE_NUMBER  
- Update the air file with the latest configuration
1. With the previous air file, getting CORS error, which means the args are failing to pass 
2. Now the error is resolved
3. Add more constraints, such as no reload on update test files

backend: update air.toml file with latest tamplate

---

app/app-build-manifest.json
app/package-lock.json
app/package.json

This is the already tested release. Just for the sake of merging from here.

Hl rc 0.33.0

---

.github/workflows/app.yml
Makefile
app/README.md
app/electron/env-paths.ts
app/electron/main.ts
app/electron/plugin-management.test.ts
app/electron/plugin-management.ts
app/electron/preload.ts
app/electron/runCmd.ts
app/electron/windowSize.test.ts
app/package-lock.json
app/package.json
app/tsconfig.json
docs/development/architecture.md

- Runs the type checker and tests for the app/ on win/linux/mac in a GitHub action.
- Fixes some type/test failures.
- Adds `make app-test` and `make app-tsc`

app: .github: Run tests and type checker plus fix broken things

---

app/package-lock.json
frontend/package-lock.json
plugins/headlamp-plugin/package-lock.json

- **app: Update vulnerable form-data package with audit fix**
- **frontend: Update vulnerable form-data package with audit fix**
- **headlamp-plugin: Update vulnerable form-data package with audit fix**

frontend: app: headlamp-plugin: Update vulnerable form-data package with audit fix

---

charts/headlamp/Chart.yaml
charts/headlamp/tests/expected_templates/azure-oidc-with-validators.yaml
charts/headlamp/tests/expected_templates/default.yaml
charts/headlamp/tests/expected_templates/extra-args.yaml
charts/headlamp/tests/expected_templates/extra-manifests.yaml
charts/headlamp/tests/expected_templates/non-azure-oidc.yaml
charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
charts/headlamp/tests/expected_templates/oidc-directly.yaml
charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
charts/headlamp/tests/expected_templates/volumes-added.yaml

This PR adds/fixes [feature/bug] by [brief description of what the change does].
Fixes #ISSUE_NUMBER  
- Added/Updated [component/file/logic]
- Fixed [bug/issue/typo]
- Refactored [code/module] for clarity/performance
1. [Step 1: e.g., Navigate to ...]
2. [Step 2: Click on ...]
3. [Step 3: Observe behavior or check logs/output]

charts: Bump Headlamp version to v0.34.0

---

frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/common/Table/Table.tsx
frontend/src/components/job/List.tsx
frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
frontend/src/components/pod/List.tsx
frontend/src/components/storage/VolumeList.tsx

- Added job and volume sort for column filtering
- Fixed issue confusing sort values

frontend: improve filter table

---

Dockerfile

This PR update Dockerfile for improved readability and consistency, prevent warnning when execute docker build.
- Update Dockerfile

CHORE: Update Dockerfile for improved readability and consistency

---

app/windows/chocolatey/headlamp.nuspec
app/windows/chocolatey/tools/chocolateyinstall.ps1

chocolatey: Bump Headlamp version to 0.35.0

---

backend/cmd/headlamp.go
backend/pkg/auth/auth.go
backend/pkg/auth/auth_test.go

This change extracts the CacheRefreshedToken from headlamp.go into the auth package.
Part of:
- #3482
- Properly set ttl to 10 seconds rather than to token expiry
- Add tests with a custom cache implementation
```shell
cd backend
go test -v ./pkg/auth -run TestCacheRefreshedToken
```

backend: auth: Extract CacheRefreshedToken from headlamp.go

---

plugins/examples/change-logo/package-lock.json
plugins/examples/change-logo/package.json
plugins/examples/cluster-chooser/package-lock.json
plugins/examples/cluster-chooser/package.json
plugins/examples/custom-theme/package-lock.json
plugins/examples/custom-theme/package.json
plugins/examples/custom-theme/src/headlamp-plugin.d.ts
plugins/examples/customizing-map/package-lock.json
plugins/examples/customizing-map/package.json
plugins/examples/details-view/package-lock.json
plugins/examples/details-view/package.json
plugins/examples/details-view/src/index.tsx
plugins/examples/headlamp-events/package-lock.json
plugins/examples/headlamp-events/package.json
plugins/examples/pod-counter/package-lock.json
plugins/examples/pod-counter/package.json
plugins/examples/pod-counter/src/Message.stories.tsx
plugins/examples/pod-counter/src/index.tsx
plugins/examples/resource-charts/package-lock.json
plugins/examples/resource-charts/package.json
plugins/examples/sidebar/package-lock.json
plugins/examples/sidebar/package.json
plugins/examples/tables/package-lock.json
plugins/examples/tables/package.json
plugins/examples/tables/src/index.tsx
plugins/examples/ui-panels/package-lock.json
plugins/examples/ui-panels/package.json

Upgrade these example plugins with new headlamp-plugin
- **plugins/examples/change-logo: Bump headlamp-plugin**
- **plugins/examples/cluster-chooser: Bump headlamp-plugin**
- **plugins/examples/custom-theme: Bump headlamp-plugin**
- **plugins/examples/customizing-map: Bump headlamp-plugin**
- **plugins/examples/sidebar: Bump headlamp-plugin**
- **plugins/examples/ui-panels: Bump headlamp-plugin**
- **plugins/examples/headlamp-events: Bump headlamp-plugin**

plugins/examples: Bump headlamp-plugin 0.13.0-alpha.7

---

plugins/examples/app-menus/package-lock.json
plugins/examples/app-menus/package.json
plugins/examples/app-menus/src/index.tsx

Update to latest headlamp-plugin.

plugins/examples/app-menus: Bump headlamp-plugin 0.13.0-alpha.7

---

frontend/src/components/advancedSearch/__snapshots__/ResourceSearch.Default.stories.storyshot
frontend/src/components/common/Resource/ResourceTable.tsx
frontend/src/components/workload/__snapshots__/Overview.Workloads.stories.storyshot

frontend: ResourceTable: Update header translation from 'Type' to 'Kind'
